// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/nalar/v1/nalar.proto

package nalar

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *RecordSymptomsData) Validate() error {
	if this.Fields != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Fields); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
		}
	}
	return nil
}
func (this *Symptom) Validate() error {
	return nil
}
func (this *RecordDiseaseData) Validate() error {
	if this.Fields != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Fields); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
		}
	}
	return nil
}
func (this *Disease) Validate() error {
	return nil
}
func (this *RecordLabData) Validate() error {
	if this.Fields != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Fields); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
		}
	}
	return nil
}
func (this *Lab) Validate() error {
	return nil
}
func (this *RecordDifferentialData) Validate() error {
	if this.Fields != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Fields); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
		}
	}
	return nil
}
func (this *Differential) Validate() error {
	return nil
}
func (this *RecordTriageData) Validate() error {
	if this.Fields != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Fields); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
		}
	}
	return nil
}
func (this *Triage) Validate() error {
	return nil
}
func (this *RecordProfileData) Validate() error {
	if this.Fields != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Fields); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
		}
	}
	return nil
}
func (this *Profile) Validate() error {
	return nil
}
