// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/baymax/v1/baymax.proto

package prixa_baymax_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PatientId            string   `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId             string   `protobuf:"bytes,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	InboxId              string   `protobuf:"bytes,6,opt,name=inbox_id,json=inboxId,proto3" json:"inbox_id,omitempty"`
	Private              bool     `protobuf:"varint,7,opt,name=private,proto3" json:"private,omitempty"`
	MessageType          string   `protobuf:"bytes,8,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	MessageSubtype       string   `protobuf:"bytes,9,opt,name=message_subtype,json=messageSubtype,proto3" json:"message_subtype,omitempty"`
	ConversationId       string   `protobuf:"bytes,10,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef96f37b1164af8, []int{0}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *MessageData) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

func (m *MessageData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *MessageData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageData) GetInboxId() string {
	if m != nil {
		return m.InboxId
	}
	return ""
}

func (m *MessageData) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *MessageData) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *MessageData) GetMessageSubtype() string {
	if m != nil {
		return m.MessageSubtype
	}
	return ""
}

func (m *MessageData) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type MessageContent struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageContent) Reset()         { *m = MessageContent{} }
func (m *MessageContent) String() string { return proto.CompactTextString(m) }
func (*MessageContent) ProtoMessage()    {}
func (*MessageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef96f37b1164af8, []int{1}
}

func (m *MessageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageContent.Unmarshal(m, b)
}
func (m *MessageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageContent.Marshal(b, m, deterministic)
}
func (m *MessageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageContent.Merge(m, src)
}
func (m *MessageContent) XXX_Size() int {
	return xxx_messageInfo_MessageContent.Size(m)
}
func (m *MessageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageContent.DiscardUnknown(m)
}

var xxx_messageInfo_MessageContent proto.InternalMessageInfo

func (m *MessageContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ConversationMessageRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Private              bool     `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConversationMessageRequest) Reset()         { *m = ConversationMessageRequest{} }
func (m *ConversationMessageRequest) String() string { return proto.CompactTextString(m) }
func (*ConversationMessageRequest) ProtoMessage()    {}
func (*ConversationMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef96f37b1164af8, []int{2}
}

func (m *ConversationMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationMessageRequest.Unmarshal(m, b)
}
func (m *ConversationMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationMessageRequest.Marshal(b, m, deterministic)
}
func (m *ConversationMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationMessageRequest.Merge(m, src)
}
func (m *ConversationMessageRequest) XXX_Size() int {
	return xxx_messageInfo_ConversationMessageRequest.Size(m)
}
func (m *ConversationMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationMessageRequest proto.InternalMessageInfo

func (m *ConversationMessageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConversationMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ConversationMessageRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type ConversationMessageResponse struct {
	Status               string       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *MessageData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConversationMessageResponse) Reset()         { *m = ConversationMessageResponse{} }
func (m *ConversationMessageResponse) String() string { return proto.CompactTextString(m) }
func (*ConversationMessageResponse) ProtoMessage()    {}
func (*ConversationMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef96f37b1164af8, []int{3}
}

func (m *ConversationMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationMessageResponse.Unmarshal(m, b)
}
func (m *ConversationMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationMessageResponse.Marshal(b, m, deterministic)
}
func (m *ConversationMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationMessageResponse.Merge(m, src)
}
func (m *ConversationMessageResponse) XXX_Size() int {
	return xxx_messageInfo_ConversationMessageResponse.Size(m)
}
func (m *ConversationMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationMessageResponse proto.InternalMessageInfo

func (m *ConversationMessageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ConversationMessageResponse) GetData() *MessageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type WidgetMessageRequest struct {
	WebsiteToken         string          `protobuf:"bytes,1,opt,name=website_token,json=websiteToken,proto3" json:"website_token,omitempty"`
	CwConversation       string          `protobuf:"bytes,2,opt,name=cw_conversation,json=cwConversation,proto3" json:"cw_conversation,omitempty"`
	Message              *MessageContent `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WidgetMessageRequest) Reset()         { *m = WidgetMessageRequest{} }
func (m *WidgetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*WidgetMessageRequest) ProtoMessage()    {}
func (*WidgetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef96f37b1164af8, []int{4}
}

func (m *WidgetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WidgetMessageRequest.Unmarshal(m, b)
}
func (m *WidgetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WidgetMessageRequest.Marshal(b, m, deterministic)
}
func (m *WidgetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WidgetMessageRequest.Merge(m, src)
}
func (m *WidgetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_WidgetMessageRequest.Size(m)
}
func (m *WidgetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WidgetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WidgetMessageRequest proto.InternalMessageInfo

func (m *WidgetMessageRequest) GetWebsiteToken() string {
	if m != nil {
		return m.WebsiteToken
	}
	return ""
}

func (m *WidgetMessageRequest) GetCwConversation() string {
	if m != nil {
		return m.CwConversation
	}
	return ""
}

func (m *WidgetMessageRequest) GetMessage() *MessageContent {
	if m != nil {
		return m.Message
	}
	return nil
}

type WidgetMessageResponse struct {
	Status               string       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *MessageData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WidgetMessageResponse) Reset()         { *m = WidgetMessageResponse{} }
func (m *WidgetMessageResponse) String() string { return proto.CompactTextString(m) }
func (*WidgetMessageResponse) ProtoMessage()    {}
func (*WidgetMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef96f37b1164af8, []int{5}
}

func (m *WidgetMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WidgetMessageResponse.Unmarshal(m, b)
}
func (m *WidgetMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WidgetMessageResponse.Marshal(b, m, deterministic)
}
func (m *WidgetMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WidgetMessageResponse.Merge(m, src)
}
func (m *WidgetMessageResponse) XXX_Size() int {
	return xxx_messageInfo_WidgetMessageResponse.Size(m)
}
func (m *WidgetMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WidgetMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WidgetMessageResponse proto.InternalMessageInfo

func (m *WidgetMessageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *WidgetMessageResponse) GetData() *MessageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetActiveTransactionByPatientRequest struct {
	PatientId            string   `protobuf:"bytes,1,opt,name=patientId,proto3" json:"patientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActiveTransactionByPatientRequest) Reset()         { *m = GetActiveTransactionByPatientRequest{} }
func (m *GetActiveTransactionByPatientRequest) String() string { return proto.CompactTextString(m) }
func (*GetActiveTransactionByPatientRequest) ProtoMessage()    {}
func (*GetActiveTransactionByPatientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef96f37b1164af8, []int{6}
}

func (m *GetActiveTransactionByPatientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActiveTransactionByPatientRequest.Unmarshal(m, b)
}
func (m *GetActiveTransactionByPatientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActiveTransactionByPatientRequest.Marshal(b, m, deterministic)
}
func (m *GetActiveTransactionByPatientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActiveTransactionByPatientRequest.Merge(m, src)
}
func (m *GetActiveTransactionByPatientRequest) XXX_Size() int {
	return xxx_messageInfo_GetActiveTransactionByPatientRequest.Size(m)
}
func (m *GetActiveTransactionByPatientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActiveTransactionByPatientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActiveTransactionByPatientRequest proto.InternalMessageInfo

func (m *GetActiveTransactionByPatientRequest) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

type GetActiveTransactionByPatientResponse struct {
	PatientId            string   `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PatientCardNumber    string   `protobuf:"bytes,2,opt,name=patient_card_number,json=patientCardNumber,proto3" json:"patient_card_number,omitempty"`
	TransactionId        string   `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	DoctorId             string   `protobuf:"bytes,5,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	ChatRoomId           string   `protobuf:"bytes,6,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	ConversationId       string   `protobuf:"bytes,7,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	InboxId              string   `protobuf:"bytes,8,opt,name=inbox_id,json=inboxId,proto3" json:"inbox_id,omitempty"`
	WebsiteToken         string   `protobuf:"bytes,9,opt,name=website_token,json=websiteToken,proto3" json:"website_token,omitempty"`
	PubsubToken          string   `protobuf:"bytes,10,opt,name=pubsub_token,json=pubsubToken,proto3" json:"pubsub_token,omitempty"`
	CwToken              string   `protobuf:"bytes,11,opt,name=cw_token,json=cwToken,proto3" json:"cw_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActiveTransactionByPatientResponse) Reset()         { *m = GetActiveTransactionByPatientResponse{} }
func (m *GetActiveTransactionByPatientResponse) String() string { return proto.CompactTextString(m) }
func (*GetActiveTransactionByPatientResponse) ProtoMessage()    {}
func (*GetActiveTransactionByPatientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ef96f37b1164af8, []int{7}
}

func (m *GetActiveTransactionByPatientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActiveTransactionByPatientResponse.Unmarshal(m, b)
}
func (m *GetActiveTransactionByPatientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActiveTransactionByPatientResponse.Marshal(b, m, deterministic)
}
func (m *GetActiveTransactionByPatientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActiveTransactionByPatientResponse.Merge(m, src)
}
func (m *GetActiveTransactionByPatientResponse) XXX_Size() int {
	return xxx_messageInfo_GetActiveTransactionByPatientResponse.Size(m)
}
func (m *GetActiveTransactionByPatientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActiveTransactionByPatientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActiveTransactionByPatientResponse proto.InternalMessageInfo

func (m *GetActiveTransactionByPatientResponse) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetPatientCardNumber() string {
	if m != nil {
		return m.PatientCardNumber
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetInboxId() string {
	if m != nil {
		return m.InboxId
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetWebsiteToken() string {
	if m != nil {
		return m.WebsiteToken
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetPubsubToken() string {
	if m != nil {
		return m.PubsubToken
	}
	return ""
}

func (m *GetActiveTransactionByPatientResponse) GetCwToken() string {
	if m != nil {
		return m.CwToken
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageData)(nil), "prixa.baymax.v1.MessageData")
	proto.RegisterType((*MessageContent)(nil), "prixa.baymax.v1.MessageContent")
	proto.RegisterType((*ConversationMessageRequest)(nil), "prixa.baymax.v1.ConversationMessageRequest")
	proto.RegisterType((*ConversationMessageResponse)(nil), "prixa.baymax.v1.ConversationMessageResponse")
	proto.RegisterType((*WidgetMessageRequest)(nil), "prixa.baymax.v1.WidgetMessageRequest")
	proto.RegisterType((*WidgetMessageResponse)(nil), "prixa.baymax.v1.WidgetMessageResponse")
	proto.RegisterType((*GetActiveTransactionByPatientRequest)(nil), "prixa.baymax.v1.GetActiveTransactionByPatientRequest")
	proto.RegisterType((*GetActiveTransactionByPatientResponse)(nil), "prixa.baymax.v1.GetActiveTransactionByPatientResponse")
}

func init() { proto.RegisterFile("proto/baymax/v1/baymax.proto", fileDescriptor_4ef96f37b1164af8) }

var fileDescriptor_4ef96f37b1164af8 = []byte{
	// 988 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x66, 0x37, 0x7f, 0xf6, 0x71, 0xec, 0x96, 0x49, 0x41, 0x8e, 0x9b, 0x28, 0xee, 0xd2, 0x90,
	0x62, 0x6a, 0x4f, 0x63, 0x44, 0x25, 0xc2, 0x05, 0xb5, 0x4d, 0x40, 0x96, 0x4a, 0x89, 0x9c, 0x48,
	0x20, 0x6e, 0xcc, 0xec, 0xee, 0x68, 0x3d, 0xd4, 0xde, 0x59, 0x76, 0xc6, 0x76, 0x4c, 0xd5, 0x1b,
	0x9e, 0x00, 0x95, 0x0b, 0x84, 0xb8, 0x40, 0x3c, 0x06, 0x5c, 0x70, 0xcb, 0x2d, 0x12, 0x0f, 0x80,
	0x84, 0x78, 0x10, 0xb4, 0x33, 0xe3, 0x64, 0xfd, 0x53, 0x1a, 0x24, 0xae, 0xb2, 0xf3, 0x9d, 0xef,
	0xcc, 0x39, 0xe7, 0xf3, 0xf9, 0x76, 0x03, 0x3b, 0x51, 0xcc, 0x25, 0xc7, 0x2e, 0x99, 0x0c, 0xc8,
	0x39, 0x1e, 0x1d, 0x9a, 0xa7, 0x9a, 0x82, 0xd1, 0xb5, 0x28, 0x66, 0xe7, 0xa4, 0x66, 0xb0, 0xd1,
	0x61, 0x69, 0x27, 0xe0, 0x3c, 0xe8, 0x53, 0x4c, 0x22, 0x86, 0x49, 0x18, 0x72, 0x49, 0x24, 0xe3,
	0xa1, 0xd0, 0xf4, 0xd2, 0x5d, 0xf5, 0xc7, 0xab, 0x06, 0x34, 0xac, 0x8a, 0x31, 0x09, 0x02, 0x1a,
	0x63, 0x1e, 0x29, 0xc6, 0x12, 0xf6, 0xfd, 0x80, 0xc9, 0xde, 0xd0, 0xad, 0x79, 0x7c, 0x80, 0x07,
	0x63, 0x26, 0x1f, 0xf3, 0x31, 0x0e, 0x78, 0x55, 0x05, 0xab, 0x23, 0xd2, 0x67, 0x3e, 0x91, 0x3c,
	0x16, 0xf8, 0xe2, 0x51, 0xe7, 0x39, 0xbf, 0xd8, 0x90, 0xfb, 0x88, 0x0a, 0x41, 0x02, 0xfa, 0x3e,
	0x91, 0x04, 0x15, 0xc0, 0x66, 0x7e, 0xd1, 0x2a, 0x5b, 0x77, 0xb2, 0x1d, 0x9b, 0xf9, 0xe8, 0x26,
	0x64, 0xbd, 0x3e, 0xa3, 0xa1, 0xec, 0x32, 0xbf, 0x68, 0x2b, 0x38, 0xa3, 0x81, 0xb6, 0x8f, 0x76,
	0x01, 0x22, 0x22, 0xa7, 0xd1, 0x15, 0x15, 0xcd, 0x1a, 0xa4, 0xad, 0x72, 0x7d, 0xee, 0x49, 0x1e,
	0x27, 0xd1, 0x55, 0x9d, 0xab, 0x81, 0xb6, 0x8f, 0x8a, 0xb0, 0xe1, 0xf1, 0x50, 0xd2, 0x50, 0x16,
	0xd7, 0x54, 0x68, 0x7a, 0x44, 0xdb, 0x90, 0x61, 0xa1, 0xcb, 0xcf, 0x93, 0xac, 0x75, 0x1d, 0x52,
	0x67, 0x9d, 0x14, 0xc5, 0x6c, 0x44, 0x24, 0x2d, 0x6e, 0x94, 0xad, 0x3b, 0x99, 0xce, 0xf4, 0x88,
	0x6e, 0xc1, 0xe6, 0x40, 0x8f, 0xd1, 0x95, 0x93, 0x88, 0x16, 0x33, 0x2a, 0x31, 0x67, 0xb0, 0xb3,
	0x49, 0x44, 0xd1, 0x01, 0x5c, 0x9b, 0x52, 0xc4, 0xd0, 0x55, 0xac, 0xac, 0x62, 0x15, 0x0c, 0x7c,
	0xaa, 0xd1, 0x84, 0xe8, 0xf1, 0x70, 0x44, 0x63, 0xa1, 0x24, 0x4e, 0xfa, 0x00, 0x4d, 0x4c, 0xc3,
	0x6d, 0xdf, 0xa9, 0x40, 0xc1, 0x68, 0xd7, 0x32, 0xbd, 0xa7, 0xa6, 0xb2, 0x66, 0xa6, 0x72, 0x3e,
	0x87, 0x52, 0x2b, 0x95, 0x6d, 0xf2, 0x3a, 0xf4, 0xcb, 0x21, 0x15, 0x72, 0x41, 0xf6, 0xd4, 0x3d,
	0xf6, 0xac, 0x3a, 0x29, 0x09, 0x56, 0x66, 0x24, 0x70, 0x02, 0xb8, 0xb9, 0xb4, 0x82, 0x88, 0x78,
	0x28, 0x28, 0x7a, 0x15, 0xd6, 0x85, 0x24, 0x72, 0x28, 0x4c, 0x19, 0x73, 0x42, 0xf7, 0x60, 0xd5,
	0x27, 0x92, 0xa8, 0x3a, 0xb9, 0xfa, 0x4e, 0x6d, 0x6e, 0x4b, 0x6b, 0xa9, 0xed, 0xe8, 0x28, 0xa6,
	0xf3, 0xa3, 0x05, 0x37, 0x3e, 0x61, 0x7e, 0x40, 0xe5, 0xdc, 0x14, 0xaf, 0x41, 0x7e, 0x4c, 0x5d,
	0xc1, 0x24, 0xed, 0x4a, 0xfe, 0x98, 0x86, 0xa6, 0xd2, 0xa6, 0x01, 0xcf, 0x12, 0x4c, 0xa9, 0x3b,
	0xee, 0xa6, 0x95, 0x34, 0x23, 0x16, 0xbc, 0x71, 0xba, 0x7f, 0xf4, 0x0e, 0x6c, 0x98, 0x1f, 0x46,
	0x4d, 0x9a, 0xab, 0xef, 0x3d, 0xaf, 0x37, 0xa3, 0x7e, 0x67, 0xca, 0x77, 0x08, 0xbc, 0x32, 0xd7,
	0xe0, 0xff, 0x2e, 0xc2, 0xc7, 0x70, 0xfb, 0x43, 0x2a, 0x1b, 0x9e, 0x64, 0x23, 0x7a, 0x16, 0x93,
	0x50, 0x10, 0x2f, 0xe9, 0xba, 0x39, 0x39, 0xd1, 0xfb, 0x3f, 0xd5, 0xe4, 0x00, 0x2e, 0x1d, 0xa1,
	0x8b, 0x36, 0xb3, 0x7f, 0xfd, 0xb9, 0xb7, 0xf6, 0xa9, 0xf5, 0x8d, 0xb5, 0x9a, 0x72, 0x8b, 0xf3,
	0xfd, 0x0a, 0xec, 0xbf, 0xe0, 0x46, 0x33, 0xc4, 0xac, 0xed, 0xac, 0x79, 0xdb, 0xd5, 0x60, 0x6b,
	0x1a, 0xf6, 0x48, 0xec, 0x77, 0xc3, 0xe1, 0xc0, 0xa5, 0xb1, 0x11, 0xf9, 0x65, 0x13, 0x6a, 0x91,
	0xd8, 0x7f, 0xa4, 0x02, 0x68, 0x1f, 0x0a, 0xf2, 0xb2, 0xdc, 0xa5, 0x93, 0xf3, 0x29, 0xb4, 0xed,
	0xa3, 0x1b, 0xb0, 0x96, 0x88, 0x45, 0x8d, 0x93, 0xf5, 0x61, 0xd6, 0xe3, 0x6b, 0x73, 0x1e, 0x2f,
	0xc3, 0xa6, 0xd7, 0x23, 0xb2, 0x1b, 0x73, 0x3e, 0xb8, 0x74, 0x33, 0x24, 0x58, 0x87, 0xf3, 0x41,
	0xdb, 0x5f, 0x66, 0xb5, 0x8d, 0x65, 0x56, 0x9b, 0x79, 0x29, 0x64, 0x66, 0x5f, 0x0a, 0x0b, 0x5b,
	0x97, 0x5d, 0xb2, 0x75, 0xb7, 0x60, 0x33, 0x1a, 0xba, 0x62, 0xe8, 0x1a, 0x8e, 0x36, 0x74, 0x4e,
	0x63, 0x9a, 0xb2, 0x0d, 0x19, 0x6f, 0x6c, 0xc2, 0x39, 0x63, 0xba, 0xb1, 0x0a, 0xd5, 0x7f, 0x5b,
	0x85, 0x7c, 0x53, 0x2d, 0xc3, 0x29, 0x8d, 0x47, 0xcc, 0xa3, 0xe8, 0x57, 0x0b, 0xb6, 0x5b, 0x31,
	0x25, 0x92, 0x2e, 0xf1, 0x1c, 0x7a, 0x73, 0x61, 0x81, 0x9e, 0xef, 0xfd, 0xd2, 0xdd, 0xab, 0x91,
	0xf5, 0x8f, 0xef, 0x7c, 0xf0, 0xac, 0x51, 0x70, 0x37, 0x01, 0x60, 0xbd, 0x49, 0x49, 0x4c, 0x63,
	0xf4, 0xd2, 0xd7, 0x7f, 0xfc, 0xfd, 0xad, 0x8d, 0x9d, 0x8a, 0xfa, 0x8e, 0x5c, 0x7c, 0x74, 0x70,
	0x5a, 0x40, 0x81, 0x9f, 0x30, 0xff, 0x29, 0x36, 0xf6, 0x10, 0x47, 0x56, 0x05, 0xfd, 0x64, 0xc1,
	0x96, 0x1e, 0x60, 0xc6, 0x29, 0x68, 0x7f, 0xa1, 0x9b, 0x65, 0x56, 0x2f, 0xbd, 0xfe, 0x22, 0x9a,
	0x69, 0xf7, 0xdd, 0xe5, 0xed, 0xde, 0x76, 0xf6, 0xe6, 0xda, 0x1d, 0xab, 0x74, 0x31, 0xd3, 0xe3,
	0xef, 0x16, 0xec, 0xfe, 0xab, 0x25, 0xd0, 0xdb, 0x0b, 0x6d, 0x5c, 0xc5, 0x94, 0xa5, 0xfb, 0xff,
	0x35, 0xcd, 0x4c, 0xf3, 0x60, 0xf9, 0x34, 0x6f, 0xa0, 0x83, 0xb9, 0x69, 0x52, 0xd6, 0x11, 0xf8,
	0xc9, 0x85, 0x37, 0x9f, 0x36, 0x7f, 0xb0, 0x9f, 0x35, 0xbe, 0xb3, 0xd1, 0xcf, 0x16, 0x6c, 0x9f,
	0x24, 0x2d, 0x94, 0x9b, 0xc4, 0x9d, 0xf4, 0x79, 0x58, 0x36, 0x8b, 0x55, 0x6e, 0x9c, 0xb4, 0x9d,
	0x63, 0x00, 0x1d, 0x3c, 0xa3, 0x5e, 0x0f, 0x1d, 0xf4, 0xa4, 0x8c, 0xc4, 0x11, 0xc6, 0xa9, 0x4f,
	0xbc, 0x6a, 0xbf, 0x4a, 0x98, 0x79, 0xd0, 0xff, 0x03, 0x14, 0x24, 0xf5, 0x7a, 0x0f, 0xf4, 0x64,
	0x1e, 0x1f, 0x54, 0x4e, 0x20, 0xaf, 0xaf, 0x79, 0xc8, 0x3c, 0x9a, 0xbc, 0x38, 0xde, 0xbb, 0xe2,
	0x4d, 0xd8, 0xed, 0x73, 0x17, 0x0f, 0x88, 0x90, 0x34, 0xc6, 0x0f, 0xdb, 0xad, 0xe3, 0x47, 0xa7,
	0xc7, 0x35, 0x79, 0x2e, 0xeb, 0x2b, 0x87, 0xb5, 0x7b, 0xa5, 0xeb, 0x34, 0x0c, 0x58, 0x48, 0xeb,
	0x46, 0x43, 0xc2, 0x2a, 0xb6, 0x65, 0xd7, 0xaf, 0x93, 0x28, 0xea, 0x33, 0x4f, 0xad, 0x1b, 0xfe,
	0x42, 0xf0, 0xf0, 0x68, 0x01, 0xf9, 0x6c, 0x0f, 0x76, 0x2f, 0x94, 0xdb, 0xca, 0xd8, 0xa5, 0x7c,
	0x63, 0x28, 0x7b, 0x3c, 0x66, 0x5f, 0x29, 0x4e, 0xd9, 0x76, 0xd7, 0x55, 0xf9, 0xb7, 0xfe, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x61, 0x16, 0x73, 0xac, 0x49, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BaymaxServiceClient is the client API for BaymaxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BaymaxServiceClient interface {
	CreateConversationMessage(ctx context.Context, in *ConversationMessageRequest, opts ...grpc.CallOption) (*ConversationMessageResponse, error)
	CreateWidgetMessage(ctx context.Context, in *WidgetMessageRequest, opts ...grpc.CallOption) (*WidgetMessageResponse, error)
	GetActiveTransactionByPatient(ctx context.Context, in *GetActiveTransactionByPatientRequest, opts ...grpc.CallOption) (*GetActiveTransactionByPatientResponse, error)
}

type baymaxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaymaxServiceClient(cc grpc.ClientConnInterface) BaymaxServiceClient {
	return &baymaxServiceClient{cc}
}

func (c *baymaxServiceClient) CreateConversationMessage(ctx context.Context, in *ConversationMessageRequest, opts ...grpc.CallOption) (*ConversationMessageResponse, error) {
	out := new(ConversationMessageResponse)
	err := c.cc.Invoke(ctx, "/prixa.baymax.v1.BaymaxService/CreateConversationMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baymaxServiceClient) CreateWidgetMessage(ctx context.Context, in *WidgetMessageRequest, opts ...grpc.CallOption) (*WidgetMessageResponse, error) {
	out := new(WidgetMessageResponse)
	err := c.cc.Invoke(ctx, "/prixa.baymax.v1.BaymaxService/CreateWidgetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baymaxServiceClient) GetActiveTransactionByPatient(ctx context.Context, in *GetActiveTransactionByPatientRequest, opts ...grpc.CallOption) (*GetActiveTransactionByPatientResponse, error) {
	out := new(GetActiveTransactionByPatientResponse)
	err := c.cc.Invoke(ctx, "/prixa.baymax.v1.BaymaxService/GetActiveTransactionByPatient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaymaxServiceServer is the server API for BaymaxService service.
type BaymaxServiceServer interface {
	CreateConversationMessage(context.Context, *ConversationMessageRequest) (*ConversationMessageResponse, error)
	CreateWidgetMessage(context.Context, *WidgetMessageRequest) (*WidgetMessageResponse, error)
	GetActiveTransactionByPatient(context.Context, *GetActiveTransactionByPatientRequest) (*GetActiveTransactionByPatientResponse, error)
}

// UnimplementedBaymaxServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBaymaxServiceServer struct {
}

func (*UnimplementedBaymaxServiceServer) CreateConversationMessage(ctx context.Context, req *ConversationMessageRequest) (*ConversationMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversationMessage not implemented")
}
func (*UnimplementedBaymaxServiceServer) CreateWidgetMessage(ctx context.Context, req *WidgetMessageRequest) (*WidgetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWidgetMessage not implemented")
}
func (*UnimplementedBaymaxServiceServer) GetActiveTransactionByPatient(ctx context.Context, req *GetActiveTransactionByPatientRequest) (*GetActiveTransactionByPatientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveTransactionByPatient not implemented")
}

func RegisterBaymaxServiceServer(s *grpc.Server, srv BaymaxServiceServer) {
	s.RegisterService(&_BaymaxService_serviceDesc, srv)
}

func _BaymaxService_CreateConversationMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaymaxServiceServer).CreateConversationMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.baymax.v1.BaymaxService/CreateConversationMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaymaxServiceServer).CreateConversationMessage(ctx, req.(*ConversationMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaymaxService_CreateWidgetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaymaxServiceServer).CreateWidgetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.baymax.v1.BaymaxService/CreateWidgetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaymaxServiceServer).CreateWidgetMessage(ctx, req.(*WidgetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaymaxService_GetActiveTransactionByPatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTransactionByPatientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaymaxServiceServer).GetActiveTransactionByPatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.baymax.v1.BaymaxService/GetActiveTransactionByPatient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaymaxServiceServer).GetActiveTransactionByPatient(ctx, req.(*GetActiveTransactionByPatientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BaymaxService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prixa.baymax.v1.BaymaxService",
	HandlerType: (*BaymaxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversationMessage",
			Handler:    _BaymaxService_CreateConversationMessage_Handler,
		},
		{
			MethodName: "CreateWidgetMessage",
			Handler:    _BaymaxService_CreateWidgetMessage_Handler,
		},
		{
			MethodName: "GetActiveTransactionByPatient",
			Handler:    _BaymaxService_GetActiveTransactionByPatient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/baymax/v1/baymax.proto",
}
