// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/siloam/v1/Siloam.proto

package prixa_siloam_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAreaResponseData struct {
	Status               string      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AreaData             []*AreaData `protobuf:"bytes,3,rep,name=areaData,proto3" json:"areaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAreaResponseData) Reset()         { *m = GetAreaResponseData{} }
func (m *GetAreaResponseData) String() string { return proto.CompactTextString(m) }
func (*GetAreaResponseData) ProtoMessage()    {}
func (*GetAreaResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{0}
}

func (m *GetAreaResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAreaResponseData.Unmarshal(m, b)
}
func (m *GetAreaResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAreaResponseData.Marshal(b, m, deterministic)
}
func (m *GetAreaResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAreaResponseData.Merge(m, src)
}
func (m *GetAreaResponseData) XXX_Size() int {
	return xxx_messageInfo_GetAreaResponseData.Size(m)
}
func (m *GetAreaResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAreaResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetAreaResponseData proto.InternalMessageInfo

func (m *GetAreaResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetAreaResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAreaResponseData) GetAreaData() []*AreaData {
	if m != nil {
		return m.AreaData
	}
	return nil
}

type AreaData struct {
	AreaId               string   `protobuf:"bytes,1,opt,name=areaId,proto3" json:"areaId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL             string   `protobuf:"bytes,3,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaData) Reset()         { *m = AreaData{} }
func (m *AreaData) String() string { return proto.CompactTextString(m) }
func (*AreaData) ProtoMessage()    {}
func (*AreaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{1}
}

func (m *AreaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaData.Unmarshal(m, b)
}
func (m *AreaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaData.Marshal(b, m, deterministic)
}
func (m *AreaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaData.Merge(m, src)
}
func (m *AreaData) XXX_Size() int {
	return xxx_messageInfo_AreaData.Size(m)
}
func (m *AreaData) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaData.DiscardUnknown(m)
}

var xxx_messageInfo_AreaData proto.InternalMessageInfo

func (m *AreaData) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *AreaData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AreaData) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

type GetHospitalRequestData struct {
	OnImplementation     bool     `protobuf:"varint,1,opt,name=onImplementation,proto3" json:"onImplementation,omitempty"`
	AreaId               string   `protobuf:"bytes,2,opt,name=areaId,proto3" json:"areaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHospitalRequestData) Reset()         { *m = GetHospitalRequestData{} }
func (m *GetHospitalRequestData) String() string { return proto.CompactTextString(m) }
func (*GetHospitalRequestData) ProtoMessage()    {}
func (*GetHospitalRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{2}
}

func (m *GetHospitalRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHospitalRequestData.Unmarshal(m, b)
}
func (m *GetHospitalRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHospitalRequestData.Marshal(b, m, deterministic)
}
func (m *GetHospitalRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHospitalRequestData.Merge(m, src)
}
func (m *GetHospitalRequestData) XXX_Size() int {
	return xxx_messageInfo_GetHospitalRequestData.Size(m)
}
func (m *GetHospitalRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHospitalRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_GetHospitalRequestData proto.InternalMessageInfo

func (m *GetHospitalRequestData) GetOnImplementation() bool {
	if m != nil {
		return m.OnImplementation
	}
	return false
}

func (m *GetHospitalRequestData) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

type GetHospitalResponseData struct {
	Status               string          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HospitalData         []*HospitalData `protobuf:"bytes,3,rep,name=hospitalData,proto3" json:"hospitalData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetHospitalResponseData) Reset()         { *m = GetHospitalResponseData{} }
func (m *GetHospitalResponseData) String() string { return proto.CompactTextString(m) }
func (*GetHospitalResponseData) ProtoMessage()    {}
func (*GetHospitalResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{3}
}

func (m *GetHospitalResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHospitalResponseData.Unmarshal(m, b)
}
func (m *GetHospitalResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHospitalResponseData.Marshal(b, m, deterministic)
}
func (m *GetHospitalResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHospitalResponseData.Merge(m, src)
}
func (m *GetHospitalResponseData) XXX_Size() int {
	return xxx_messageInfo_GetHospitalResponseData.Size(m)
}
func (m *GetHospitalResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHospitalResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetHospitalResponseData proto.InternalMessageInfo

func (m *GetHospitalResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetHospitalResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetHospitalResponseData) GetHospitalData() []*HospitalData {
	if m != nil {
		return m.HospitalData
	}
	return nil
}

type HospitalData struct {
	HospitalId           string   `protobuf:"bytes,1,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	HospitalStatusId     string   `protobuf:"bytes,2,opt,name=hospitalStatusId,proto3" json:"hospitalStatusId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Alias                string   `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber1         string   `protobuf:"bytes,6,opt,name=phoneNumber1,proto3" json:"phoneNumber1,omitempty"`
	Longitude            float32  `protobuf:"fixed32,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Lattitude            float32  `protobuf:"fixed32,8,opt,name=lattitude,proto3" json:"lattitude,omitempty"`
	AreaId               string   `protobuf:"bytes,9,opt,name=areaId,proto3" json:"areaId,omitempty"`
	AreaName             string   `protobuf:"bytes,10,opt,name=areaName,proto3" json:"areaName,omitempty"`
	ImageURL             string   `protobuf:"bytes,11,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HospitalData) Reset()         { *m = HospitalData{} }
func (m *HospitalData) String() string { return proto.CompactTextString(m) }
func (*HospitalData) ProtoMessage()    {}
func (*HospitalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{4}
}

func (m *HospitalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HospitalData.Unmarshal(m, b)
}
func (m *HospitalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HospitalData.Marshal(b, m, deterministic)
}
func (m *HospitalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HospitalData.Merge(m, src)
}
func (m *HospitalData) XXX_Size() int {
	return xxx_messageInfo_HospitalData.Size(m)
}
func (m *HospitalData) XXX_DiscardUnknown() {
	xxx_messageInfo_HospitalData.DiscardUnknown(m)
}

var xxx_messageInfo_HospitalData proto.InternalMessageInfo

func (m *HospitalData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *HospitalData) GetHospitalStatusId() string {
	if m != nil {
		return m.HospitalStatusId
	}
	return ""
}

func (m *HospitalData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HospitalData) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *HospitalData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *HospitalData) GetPhoneNumber1() string {
	if m != nil {
		return m.PhoneNumber1
	}
	return ""
}

func (m *HospitalData) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *HospitalData) GetLattitude() float32 {
	if m != nil {
		return m.Lattitude
	}
	return 0
}

func (m *HospitalData) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *HospitalData) GetAreaName() string {
	if m != nil {
		return m.AreaName
	}
	return ""
}

func (m *HospitalData) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

type GetSpecialityRequestData struct {
	HospitalId           string   `protobuf:"bytes,1,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpecialityRequestData) Reset()         { *m = GetSpecialityRequestData{} }
func (m *GetSpecialityRequestData) String() string { return proto.CompactTextString(m) }
func (*GetSpecialityRequestData) ProtoMessage()    {}
func (*GetSpecialityRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{5}
}

func (m *GetSpecialityRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpecialityRequestData.Unmarshal(m, b)
}
func (m *GetSpecialityRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpecialityRequestData.Marshal(b, m, deterministic)
}
func (m *GetSpecialityRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpecialityRequestData.Merge(m, src)
}
func (m *GetSpecialityRequestData) XXX_Size() int {
	return xxx_messageInfo_GetSpecialityRequestData.Size(m)
}
func (m *GetSpecialityRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpecialityRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpecialityRequestData proto.InternalMessageInfo

func (m *GetSpecialityRequestData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

type GetSpecialityResponseData struct {
	Status               string            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SpecialityData       []*SpecialityData `protobuf:"bytes,3,rep,name=specialityData,proto3" json:"specialityData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSpecialityResponseData) Reset()         { *m = GetSpecialityResponseData{} }
func (m *GetSpecialityResponseData) String() string { return proto.CompactTextString(m) }
func (*GetSpecialityResponseData) ProtoMessage()    {}
func (*GetSpecialityResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{6}
}

func (m *GetSpecialityResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpecialityResponseData.Unmarshal(m, b)
}
func (m *GetSpecialityResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpecialityResponseData.Marshal(b, m, deterministic)
}
func (m *GetSpecialityResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpecialityResponseData.Merge(m, src)
}
func (m *GetSpecialityResponseData) XXX_Size() int {
	return xxx_messageInfo_GetSpecialityResponseData.Size(m)
}
func (m *GetSpecialityResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpecialityResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpecialityResponseData proto.InternalMessageInfo

func (m *GetSpecialityResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetSpecialityResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSpecialityResponseData) GetSpecialityData() []*SpecialityData {
	if m != nil {
		return m.SpecialityData
	}
	return nil
}

type SpecialityData struct {
	SpecialityId         string   `protobuf:"bytes,1,opt,name=specialityId,proto3" json:"specialityId,omitempty"`
	SpecialityNameEn     string   `protobuf:"bytes,2,opt,name=specialityNameEn,proto3" json:"specialityNameEn,omitempty"`
	SpecialityName       string   `protobuf:"bytes,3,opt,name=specialityName,proto3" json:"specialityName,omitempty"`
	IsCoe                bool     `protobuf:"varint,4,opt,name=isCoe,proto3" json:"isCoe,omitempty"`
	ImageURL             string   `protobuf:"bytes,5,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpecialityData) Reset()         { *m = SpecialityData{} }
func (m *SpecialityData) String() string { return proto.CompactTextString(m) }
func (*SpecialityData) ProtoMessage()    {}
func (*SpecialityData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{7}
}

func (m *SpecialityData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecialityData.Unmarshal(m, b)
}
func (m *SpecialityData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecialityData.Marshal(b, m, deterministic)
}
func (m *SpecialityData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecialityData.Merge(m, src)
}
func (m *SpecialityData) XXX_Size() int {
	return xxx_messageInfo_SpecialityData.Size(m)
}
func (m *SpecialityData) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecialityData.DiscardUnknown(m)
}

var xxx_messageInfo_SpecialityData proto.InternalMessageInfo

func (m *SpecialityData) GetSpecialityId() string {
	if m != nil {
		return m.SpecialityId
	}
	return ""
}

func (m *SpecialityData) GetSpecialityNameEn() string {
	if m != nil {
		return m.SpecialityNameEn
	}
	return ""
}

func (m *SpecialityData) GetSpecialityName() string {
	if m != nil {
		return m.SpecialityName
	}
	return ""
}

func (m *SpecialityData) GetIsCoe() bool {
	if m != nil {
		return m.IsCoe
	}
	return false
}

func (m *SpecialityData) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

type GetDoctorsRequestData struct {
	DoctorName           string   `protobuf:"bytes,1,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	DoctorId             string   `protobuf:"bytes,2,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	HospitalId           string   `protobuf:"bytes,3,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	SpecialityId         string   `protobuf:"bytes,4,opt,name=specialityId,proto3" json:"specialityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDoctorsRequestData) Reset()         { *m = GetDoctorsRequestData{} }
func (m *GetDoctorsRequestData) String() string { return proto.CompactTextString(m) }
func (*GetDoctorsRequestData) ProtoMessage()    {}
func (*GetDoctorsRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{8}
}

func (m *GetDoctorsRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDoctorsRequestData.Unmarshal(m, b)
}
func (m *GetDoctorsRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDoctorsRequestData.Marshal(b, m, deterministic)
}
func (m *GetDoctorsRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDoctorsRequestData.Merge(m, src)
}
func (m *GetDoctorsRequestData) XXX_Size() int {
	return xxx_messageInfo_GetDoctorsRequestData.Size(m)
}
func (m *GetDoctorsRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDoctorsRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_GetDoctorsRequestData proto.InternalMessageInfo

func (m *GetDoctorsRequestData) GetDoctorName() string {
	if m != nil {
		return m.DoctorName
	}
	return ""
}

func (m *GetDoctorsRequestData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *GetDoctorsRequestData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *GetDoctorsRequestData) GetSpecialityId() string {
	if m != nil {
		return m.SpecialityId
	}
	return ""
}

type GetDoctorsResponseData struct {
	Status               string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DoctorData           []*DoctorData `protobuf:"bytes,3,rep,name=doctorData,proto3" json:"doctorData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDoctorsResponseData) Reset()         { *m = GetDoctorsResponseData{} }
func (m *GetDoctorsResponseData) String() string { return proto.CompactTextString(m) }
func (*GetDoctorsResponseData) ProtoMessage()    {}
func (*GetDoctorsResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{9}
}

func (m *GetDoctorsResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDoctorsResponseData.Unmarshal(m, b)
}
func (m *GetDoctorsResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDoctorsResponseData.Marshal(b, m, deterministic)
}
func (m *GetDoctorsResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDoctorsResponseData.Merge(m, src)
}
func (m *GetDoctorsResponseData) XXX_Size() int {
	return xxx_messageInfo_GetDoctorsResponseData.Size(m)
}
func (m *GetDoctorsResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDoctorsResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetDoctorsResponseData proto.InternalMessageInfo

func (m *GetDoctorsResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetDoctorsResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetDoctorsResponseData) GetDoctorData() []*DoctorData {
	if m != nil {
		return m.DoctorData
	}
	return nil
}

type DoctorData struct {
	DoctorId             string   `protobuf:"bytes,1,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	SpecializationId     string   `protobuf:"bytes,2,opt,name=specializationId,proto3" json:"specializationId,omitempty"`
	SpecialityId         string   `protobuf:"bytes,3,opt,name=specialityId,proto3" json:"specialityId,omitempty"`
	HospitalId           string   `protobuf:"bytes,4,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SpecializationName   string   `protobuf:"bytes,6,opt,name=specializationName,proto3" json:"specializationName,omitempty"`
	SpecializationNameEn string   `protobuf:"bytes,7,opt,name=specializationNameEn,proto3" json:"specializationNameEn,omitempty"`
	HospitalName         string   `protobuf:"bytes,8,opt,name=hospitalName,proto3" json:"hospitalName,omitempty"`
	ImageURL             string   `protobuf:"bytes,9,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoctorData) Reset()         { *m = DoctorData{} }
func (m *DoctorData) String() string { return proto.CompactTextString(m) }
func (*DoctorData) ProtoMessage()    {}
func (*DoctorData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{10}
}

func (m *DoctorData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoctorData.Unmarshal(m, b)
}
func (m *DoctorData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoctorData.Marshal(b, m, deterministic)
}
func (m *DoctorData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoctorData.Merge(m, src)
}
func (m *DoctorData) XXX_Size() int {
	return xxx_messageInfo_DoctorData.Size(m)
}
func (m *DoctorData) XXX_DiscardUnknown() {
	xxx_messageInfo_DoctorData.DiscardUnknown(m)
}

var xxx_messageInfo_DoctorData proto.InternalMessageInfo

func (m *DoctorData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *DoctorData) GetSpecializationId() string {
	if m != nil {
		return m.SpecializationId
	}
	return ""
}

func (m *DoctorData) GetSpecialityId() string {
	if m != nil {
		return m.SpecialityId
	}
	return ""
}

func (m *DoctorData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *DoctorData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DoctorData) GetSpecializationName() string {
	if m != nil {
		return m.SpecializationName
	}
	return ""
}

func (m *DoctorData) GetSpecializationNameEn() string {
	if m != nil {
		return m.SpecializationNameEn
	}
	return ""
}

func (m *DoctorData) GetHospitalName() string {
	if m != nil {
		return m.HospitalName
	}
	return ""
}

func (m *DoctorData) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

type GetDoctorLeaveHospitalRequestData struct {
	HospitalId           string   `protobuf:"bytes,1,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	DoctorId             string   `protobuf:"bytes,2,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDoctorLeaveHospitalRequestData) Reset()         { *m = GetDoctorLeaveHospitalRequestData{} }
func (m *GetDoctorLeaveHospitalRequestData) String() string { return proto.CompactTextString(m) }
func (*GetDoctorLeaveHospitalRequestData) ProtoMessage()    {}
func (*GetDoctorLeaveHospitalRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{11}
}

func (m *GetDoctorLeaveHospitalRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDoctorLeaveHospitalRequestData.Unmarshal(m, b)
}
func (m *GetDoctorLeaveHospitalRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDoctorLeaveHospitalRequestData.Marshal(b, m, deterministic)
}
func (m *GetDoctorLeaveHospitalRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDoctorLeaveHospitalRequestData.Merge(m, src)
}
func (m *GetDoctorLeaveHospitalRequestData) XXX_Size() int {
	return xxx_messageInfo_GetDoctorLeaveHospitalRequestData.Size(m)
}
func (m *GetDoctorLeaveHospitalRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDoctorLeaveHospitalRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_GetDoctorLeaveHospitalRequestData proto.InternalMessageInfo

func (m *GetDoctorLeaveHospitalRequestData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *GetDoctorLeaveHospitalRequestData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

type GetDoctorLeaveHospitalResponseData struct {
	Status                  string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message                 string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DoctorLeaveHospitalData []*DoctorLeaveHospitalData `protobuf:"bytes,3,rep,name=doctorLeaveHospitalData,proto3" json:"doctorLeaveHospitalData,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                   `json:"-"`
	XXX_unrecognized        []byte                     `json:"-"`
	XXX_sizecache           int32                      `json:"-"`
}

func (m *GetDoctorLeaveHospitalResponseData) Reset()         { *m = GetDoctorLeaveHospitalResponseData{} }
func (m *GetDoctorLeaveHospitalResponseData) String() string { return proto.CompactTextString(m) }
func (*GetDoctorLeaveHospitalResponseData) ProtoMessage()    {}
func (*GetDoctorLeaveHospitalResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{12}
}

func (m *GetDoctorLeaveHospitalResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDoctorLeaveHospitalResponseData.Unmarshal(m, b)
}
func (m *GetDoctorLeaveHospitalResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDoctorLeaveHospitalResponseData.Marshal(b, m, deterministic)
}
func (m *GetDoctorLeaveHospitalResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDoctorLeaveHospitalResponseData.Merge(m, src)
}
func (m *GetDoctorLeaveHospitalResponseData) XXX_Size() int {
	return xxx_messageInfo_GetDoctorLeaveHospitalResponseData.Size(m)
}
func (m *GetDoctorLeaveHospitalResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDoctorLeaveHospitalResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetDoctorLeaveHospitalResponseData proto.InternalMessageInfo

func (m *GetDoctorLeaveHospitalResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetDoctorLeaveHospitalResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetDoctorLeaveHospitalResponseData) GetDoctorLeaveHospitalData() []*DoctorLeaveHospitalData {
	if m != nil {
		return m.DoctorLeaveHospitalData
	}
	return nil
}

type DoctorLeaveHospitalData struct {
	DoctorId             string               `protobuf:"bytes,1,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	HospitalId           string               `protobuf:"bytes,2,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	FromDate             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=fromDate,proto3" json:"fromDate,omitempty"`
	ToDate               *timestamp.Timestamp `protobuf:"bytes,4,opt,name=toDate,proto3" json:"toDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DoctorLeaveHospitalData) Reset()         { *m = DoctorLeaveHospitalData{} }
func (m *DoctorLeaveHospitalData) String() string { return proto.CompactTextString(m) }
func (*DoctorLeaveHospitalData) ProtoMessage()    {}
func (*DoctorLeaveHospitalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{13}
}

func (m *DoctorLeaveHospitalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoctorLeaveHospitalData.Unmarshal(m, b)
}
func (m *DoctorLeaveHospitalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoctorLeaveHospitalData.Marshal(b, m, deterministic)
}
func (m *DoctorLeaveHospitalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoctorLeaveHospitalData.Merge(m, src)
}
func (m *DoctorLeaveHospitalData) XXX_Size() int {
	return xxx_messageInfo_DoctorLeaveHospitalData.Size(m)
}
func (m *DoctorLeaveHospitalData) XXX_DiscardUnknown() {
	xxx_messageInfo_DoctorLeaveHospitalData.DiscardUnknown(m)
}

var xxx_messageInfo_DoctorLeaveHospitalData proto.InternalMessageInfo

func (m *DoctorLeaveHospitalData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *DoctorLeaveHospitalData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *DoctorLeaveHospitalData) GetFromDate() *timestamp.Timestamp {
	if m != nil {
		return m.FromDate
	}
	return nil
}

func (m *DoctorLeaveHospitalData) GetToDate() *timestamp.Timestamp {
	if m != nil {
		return m.ToDate
	}
	return nil
}

type GetSchedulesPerWeeksRequestData struct {
	HospitalId           string   `protobuf:"bytes,1,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	DoctorId             string   `protobuf:"bytes,2,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchedulesPerWeeksRequestData) Reset()         { *m = GetSchedulesPerWeeksRequestData{} }
func (m *GetSchedulesPerWeeksRequestData) String() string { return proto.CompactTextString(m) }
func (*GetSchedulesPerWeeksRequestData) ProtoMessage()    {}
func (*GetSchedulesPerWeeksRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{14}
}

func (m *GetSchedulesPerWeeksRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchedulesPerWeeksRequestData.Unmarshal(m, b)
}
func (m *GetSchedulesPerWeeksRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchedulesPerWeeksRequestData.Marshal(b, m, deterministic)
}
func (m *GetSchedulesPerWeeksRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchedulesPerWeeksRequestData.Merge(m, src)
}
func (m *GetSchedulesPerWeeksRequestData) XXX_Size() int {
	return xxx_messageInfo_GetSchedulesPerWeeksRequestData.Size(m)
}
func (m *GetSchedulesPerWeeksRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchedulesPerWeeksRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchedulesPerWeeksRequestData proto.InternalMessageInfo

func (m *GetSchedulesPerWeeksRequestData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *GetSchedulesPerWeeksRequestData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

type GetSchedulesPerWeeksResponseData struct {
	Status                string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message               string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SchedulesPerWeeksData []*SchedulesPerWeeksData `protobuf:"bytes,3,rep,name=schedulesPerWeeksData,proto3" json:"schedulesPerWeeksData,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *GetSchedulesPerWeeksResponseData) Reset()         { *m = GetSchedulesPerWeeksResponseData{} }
func (m *GetSchedulesPerWeeksResponseData) String() string { return proto.CompactTextString(m) }
func (*GetSchedulesPerWeeksResponseData) ProtoMessage()    {}
func (*GetSchedulesPerWeeksResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{15}
}

func (m *GetSchedulesPerWeeksResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchedulesPerWeeksResponseData.Unmarshal(m, b)
}
func (m *GetSchedulesPerWeeksResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchedulesPerWeeksResponseData.Marshal(b, m, deterministic)
}
func (m *GetSchedulesPerWeeksResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchedulesPerWeeksResponseData.Merge(m, src)
}
func (m *GetSchedulesPerWeeksResponseData) XXX_Size() int {
	return xxx_messageInfo_GetSchedulesPerWeeksResponseData.Size(m)
}
func (m *GetSchedulesPerWeeksResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchedulesPerWeeksResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchedulesPerWeeksResponseData proto.InternalMessageInfo

func (m *GetSchedulesPerWeeksResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetSchedulesPerWeeksResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSchedulesPerWeeksResponseData) GetSchedulesPerWeeksData() []*SchedulesPerWeeksData {
	if m != nil {
		return m.SchedulesPerWeeksData
	}
	return nil
}

type SchedulesPerWeeksData struct {
	ScheduleId           string               `protobuf:"bytes,1,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	HospitalId           string               `protobuf:"bytes,2,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	DoctorId             string               `protobuf:"bytes,3,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	ScheduleStatusId     int32                `protobuf:"varint,4,opt,name=scheduleStatusId,proto3" json:"scheduleStatusId,omitempty"`
	ScheduleTypeId       int32                `protobuf:"varint,5,opt,name=scheduleTypeId,proto3" json:"scheduleTypeId,omitempty"`
	Day                  int32                `protobuf:"varint,6,opt,name=day,proto3" json:"day,omitempty"`
	FromTime             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=fromTime,proto3" json:"fromTime,omitempty"`
	ToTime               *timestamp.Timestamp `protobuf:"bytes,8,opt,name=toTime,proto3" json:"toTime,omitempty"`
	DoctorName           string               `protobuf:"bytes,9,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	HospitalName         string               `protobuf:"bytes,10,opt,name=hospitalName,proto3" json:"hospitalName,omitempty"`
	AreaId               string               `protobuf:"bytes,11,opt,name=areaId,proto3" json:"areaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SchedulesPerWeeksData) Reset()         { *m = SchedulesPerWeeksData{} }
func (m *SchedulesPerWeeksData) String() string { return proto.CompactTextString(m) }
func (*SchedulesPerWeeksData) ProtoMessage()    {}
func (*SchedulesPerWeeksData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{16}
}

func (m *SchedulesPerWeeksData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulesPerWeeksData.Unmarshal(m, b)
}
func (m *SchedulesPerWeeksData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulesPerWeeksData.Marshal(b, m, deterministic)
}
func (m *SchedulesPerWeeksData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulesPerWeeksData.Merge(m, src)
}
func (m *SchedulesPerWeeksData) XXX_Size() int {
	return xxx_messageInfo_SchedulesPerWeeksData.Size(m)
}
func (m *SchedulesPerWeeksData) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulesPerWeeksData.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulesPerWeeksData proto.InternalMessageInfo

func (m *SchedulesPerWeeksData) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *SchedulesPerWeeksData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *SchedulesPerWeeksData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *SchedulesPerWeeksData) GetScheduleStatusId() int32 {
	if m != nil {
		return m.ScheduleStatusId
	}
	return 0
}

func (m *SchedulesPerWeeksData) GetScheduleTypeId() int32 {
	if m != nil {
		return m.ScheduleTypeId
	}
	return 0
}

func (m *SchedulesPerWeeksData) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *SchedulesPerWeeksData) GetFromTime() *timestamp.Timestamp {
	if m != nil {
		return m.FromTime
	}
	return nil
}

func (m *SchedulesPerWeeksData) GetToTime() *timestamp.Timestamp {
	if m != nil {
		return m.ToTime
	}
	return nil
}

func (m *SchedulesPerWeeksData) GetDoctorName() string {
	if m != nil {
		return m.DoctorName
	}
	return ""
}

func (m *SchedulesPerWeeksData) GetHospitalName() string {
	if m != nil {
		return m.HospitalName
	}
	return ""
}

func (m *SchedulesPerWeeksData) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

type GetTimeSlotRequestData struct {
	HospitalId           string               `protobuf:"bytes,1,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	DoctorId             string               `protobuf:"bytes,2,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	AppointmentDate      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=appointmentDate,proto3" json:"appointmentDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetTimeSlotRequestData) Reset()         { *m = GetTimeSlotRequestData{} }
func (m *GetTimeSlotRequestData) String() string { return proto.CompactTextString(m) }
func (*GetTimeSlotRequestData) ProtoMessage()    {}
func (*GetTimeSlotRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{17}
}

func (m *GetTimeSlotRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeSlotRequestData.Unmarshal(m, b)
}
func (m *GetTimeSlotRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeSlotRequestData.Marshal(b, m, deterministic)
}
func (m *GetTimeSlotRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeSlotRequestData.Merge(m, src)
}
func (m *GetTimeSlotRequestData) XXX_Size() int {
	return xxx_messageInfo_GetTimeSlotRequestData.Size(m)
}
func (m *GetTimeSlotRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeSlotRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeSlotRequestData proto.InternalMessageInfo

func (m *GetTimeSlotRequestData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *GetTimeSlotRequestData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *GetTimeSlotRequestData) GetAppointmentDate() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentDate
	}
	return nil
}

type GetTimeSlotResponseData struct {
	Status               string          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TimeSlotData         []*TimeSlotData `protobuf:"bytes,3,rep,name=timeSlotData,proto3" json:"timeSlotData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTimeSlotResponseData) Reset()         { *m = GetTimeSlotResponseData{} }
func (m *GetTimeSlotResponseData) String() string { return proto.CompactTextString(m) }
func (*GetTimeSlotResponseData) ProtoMessage()    {}
func (*GetTimeSlotResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{18}
}

func (m *GetTimeSlotResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeSlotResponseData.Unmarshal(m, b)
}
func (m *GetTimeSlotResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeSlotResponseData.Marshal(b, m, deterministic)
}
func (m *GetTimeSlotResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeSlotResponseData.Merge(m, src)
}
func (m *GetTimeSlotResponseData) XXX_Size() int {
	return xxx_messageInfo_GetTimeSlotResponseData.Size(m)
}
func (m *GetTimeSlotResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeSlotResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeSlotResponseData proto.InternalMessageInfo

func (m *GetTimeSlotResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetTimeSlotResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetTimeSlotResponseData) GetTimeSlotData() []*TimeSlotData {
	if m != nil {
		return m.TimeSlotData
	}
	return nil
}

type TimeSlotData struct {
	ScheduleId           string               `protobuf:"bytes,1,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	HospitalTimeZone     int32                `protobuf:"varint,2,opt,name=hospitalTimeZone,proto3" json:"hospitalTimeZone,omitempty"`
	IsFull               bool                 `protobuf:"varint,3,opt,name=isFull,proto3" json:"isFull,omitempty"`
	FromTime             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=fromTime,proto3" json:"fromTime,omitempty"`
	ToTime               *timestamp.Timestamp `protobuf:"bytes,5,opt,name=toTime,proto3" json:"toTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeSlotData) Reset()         { *m = TimeSlotData{} }
func (m *TimeSlotData) String() string { return proto.CompactTextString(m) }
func (*TimeSlotData) ProtoMessage()    {}
func (*TimeSlotData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{19}
}

func (m *TimeSlotData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSlotData.Unmarshal(m, b)
}
func (m *TimeSlotData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSlotData.Marshal(b, m, deterministic)
}
func (m *TimeSlotData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSlotData.Merge(m, src)
}
func (m *TimeSlotData) XXX_Size() int {
	return xxx_messageInfo_TimeSlotData.Size(m)
}
func (m *TimeSlotData) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSlotData.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSlotData proto.InternalMessageInfo

func (m *TimeSlotData) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *TimeSlotData) GetHospitalTimeZone() int32 {
	if m != nil {
		return m.HospitalTimeZone
	}
	return 0
}

func (m *TimeSlotData) GetIsFull() bool {
	if m != nil {
		return m.IsFull
	}
	return false
}

func (m *TimeSlotData) GetFromTime() *timestamp.Timestamp {
	if m != nil {
		return m.FromTime
	}
	return nil
}

func (m *TimeSlotData) GetToTime() *timestamp.Timestamp {
	if m != nil {
		return m.ToTime
	}
	return nil
}

type PostAppointmentRequestData struct {
	ChannelId            string               `protobuf:"bytes,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	AppointmentDate      *timestamp.Timestamp `protobuf:"bytes,2,opt,name=appointmentDate,proto3" json:"appointmentDate,omitempty"`
	AppointmentFromTime  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=appointmentFromTime,proto3" json:"appointmentFromTime,omitempty"`
	ScheduleId           string               `protobuf:"bytes,4,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	HospitalId           string               `protobuf:"bytes,5,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	DoctorId             string               `protobuf:"bytes,6,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	IsWaitingList        bool                 `protobuf:"varint,7,opt,name=isWaitingList,proto3" json:"isWaitingList,omitempty"`
	Name                 string               `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	BirthDate            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	PhoneNumber1         string               `protobuf:"bytes,10,opt,name=phoneNumber1,proto3" json:"phoneNumber1,omitempty"`
	EmailAddress         string               `protobuf:"bytes,11,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	UserId               string               `protobuf:"bytes,12,opt,name=userId,proto3" json:"userId,omitempty"`
	Source               string               `protobuf:"bytes,13,opt,name=source,proto3" json:"source,omitempty"`
	UserName             string               `protobuf:"bytes,14,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostAppointmentRequestData) Reset()         { *m = PostAppointmentRequestData{} }
func (m *PostAppointmentRequestData) String() string { return proto.CompactTextString(m) }
func (*PostAppointmentRequestData) ProtoMessage()    {}
func (*PostAppointmentRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{20}
}

func (m *PostAppointmentRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAppointmentRequestData.Unmarshal(m, b)
}
func (m *PostAppointmentRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAppointmentRequestData.Marshal(b, m, deterministic)
}
func (m *PostAppointmentRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAppointmentRequestData.Merge(m, src)
}
func (m *PostAppointmentRequestData) XXX_Size() int {
	return xxx_messageInfo_PostAppointmentRequestData.Size(m)
}
func (m *PostAppointmentRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAppointmentRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_PostAppointmentRequestData proto.InternalMessageInfo

func (m *PostAppointmentRequestData) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *PostAppointmentRequestData) GetAppointmentDate() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentDate
	}
	return nil
}

func (m *PostAppointmentRequestData) GetAppointmentFromTime() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentFromTime
	}
	return nil
}

func (m *PostAppointmentRequestData) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *PostAppointmentRequestData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *PostAppointmentRequestData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *PostAppointmentRequestData) GetIsWaitingList() bool {
	if m != nil {
		return m.IsWaitingList
	}
	return false
}

func (m *PostAppointmentRequestData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostAppointmentRequestData) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *PostAppointmentRequestData) GetPhoneNumber1() string {
	if m != nil {
		return m.PhoneNumber1
	}
	return ""
}

func (m *PostAppointmentRequestData) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *PostAppointmentRequestData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PostAppointmentRequestData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *PostAppointmentRequestData) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type PostAppointmentResponseData struct {
	Status               string               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AppointmentData      *PostAppointmentData `protobuf:"bytes,3,opt,name=appointmentData,proto3" json:"appointmentData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostAppointmentResponseData) Reset()         { *m = PostAppointmentResponseData{} }
func (m *PostAppointmentResponseData) String() string { return proto.CompactTextString(m) }
func (*PostAppointmentResponseData) ProtoMessage()    {}
func (*PostAppointmentResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{21}
}

func (m *PostAppointmentResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAppointmentResponseData.Unmarshal(m, b)
}
func (m *PostAppointmentResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAppointmentResponseData.Marshal(b, m, deterministic)
}
func (m *PostAppointmentResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAppointmentResponseData.Merge(m, src)
}
func (m *PostAppointmentResponseData) XXX_Size() int {
	return xxx_messageInfo_PostAppointmentResponseData.Size(m)
}
func (m *PostAppointmentResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAppointmentResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_PostAppointmentResponseData proto.InternalMessageInfo

func (m *PostAppointmentResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PostAppointmentResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostAppointmentResponseData) GetAppointmentData() *PostAppointmentData {
	if m != nil {
		return m.AppointmentData
	}
	return nil
}

type PostAppointmentData struct {
	AppointmentId        string               `protobuf:"bytes,1,opt,name=appointmentId,proto3" json:"appointmentId,omitempty"`
	AppointmentNo        int64                `protobuf:"varint,2,opt,name=appointmentNo,proto3" json:"appointmentNo,omitempty"`
	AppointmentDate      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=appointmentDate,proto3" json:"appointmentDate,omitempty"`
	AppointmentFromTime  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=appointmentFromTime,proto3" json:"appointmentFromTime,omitempty"`
	AppointmentToTime    *timestamp.Timestamp `protobuf:"bytes,5,opt,name=appointmentToTime,proto3" json:"appointmentToTime,omitempty"`
	IsWaitingList        bool                 `protobuf:"varint,6,opt,name=isWaitingList,proto3" json:"isWaitingList,omitempty"`
	Note                 string               `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	ChannelId            string               `protobuf:"bytes,8,opt,name=channelId,proto3" json:"channelId,omitempty"`
	ScheduleId           string               `protobuf:"bytes,9,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	ContactId            string               `protobuf:"bytes,10,opt,name=contactId,proto3" json:"contactId,omitempty"`
	ContactName          string               `protobuf:"bytes,11,opt,name=contactName,proto3" json:"contactName,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,12,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	PlaceOfBirth         string               `protobuf:"bytes,13,opt,name=placeOfBirth,proto3" json:"placeOfBirth,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,14,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	AddressLine1         string               `protobuf:"bytes,15,opt,name=addressLine1,proto3" json:"addressLine1,omitempty"`
	AddressLine2         string               `protobuf:"bytes,16,opt,name=addressLine2,proto3" json:"addressLine2,omitempty"`
	EmailAddress         string               `protobuf:"bytes,17,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	DoctorId             string               `protobuf:"bytes,18,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	HospitalId           string               `protobuf:"bytes,19,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	DoctorName           string               `protobuf:"bytes,20,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	HospitalName         string               `protobuf:"bytes,21,opt,name=hospitalName,proto3" json:"hospitalName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostAppointmentData) Reset()         { *m = PostAppointmentData{} }
func (m *PostAppointmentData) String() string { return proto.CompactTextString(m) }
func (*PostAppointmentData) ProtoMessage()    {}
func (*PostAppointmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{22}
}

func (m *PostAppointmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAppointmentData.Unmarshal(m, b)
}
func (m *PostAppointmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAppointmentData.Marshal(b, m, deterministic)
}
func (m *PostAppointmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAppointmentData.Merge(m, src)
}
func (m *PostAppointmentData) XXX_Size() int {
	return xxx_messageInfo_PostAppointmentData.Size(m)
}
func (m *PostAppointmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAppointmentData.DiscardUnknown(m)
}

var xxx_messageInfo_PostAppointmentData proto.InternalMessageInfo

func (m *PostAppointmentData) GetAppointmentId() string {
	if m != nil {
		return m.AppointmentId
	}
	return ""
}

func (m *PostAppointmentData) GetAppointmentNo() int64 {
	if m != nil {
		return m.AppointmentNo
	}
	return 0
}

func (m *PostAppointmentData) GetAppointmentDate() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentDate
	}
	return nil
}

func (m *PostAppointmentData) GetAppointmentFromTime() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentFromTime
	}
	return nil
}

func (m *PostAppointmentData) GetAppointmentToTime() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentToTime
	}
	return nil
}

func (m *PostAppointmentData) GetIsWaitingList() bool {
	if m != nil {
		return m.IsWaitingList
	}
	return false
}

func (m *PostAppointmentData) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *PostAppointmentData) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *PostAppointmentData) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *PostAppointmentData) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func (m *PostAppointmentData) GetContactName() string {
	if m != nil {
		return m.ContactName
	}
	return ""
}

func (m *PostAppointmentData) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *PostAppointmentData) GetPlaceOfBirth() string {
	if m != nil {
		return m.PlaceOfBirth
	}
	return ""
}

func (m *PostAppointmentData) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *PostAppointmentData) GetAddressLine1() string {
	if m != nil {
		return m.AddressLine1
	}
	return ""
}

func (m *PostAppointmentData) GetAddressLine2() string {
	if m != nil {
		return m.AddressLine2
	}
	return ""
}

func (m *PostAppointmentData) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *PostAppointmentData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *PostAppointmentData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *PostAppointmentData) GetDoctorName() string {
	if m != nil {
		return m.DoctorName
	}
	return ""
}

func (m *PostAppointmentData) GetHospitalName() string {
	if m != nil {
		return m.HospitalName
	}
	return ""
}

type CancelAppointmentRequestData struct {
	AppointmentId        string   `protobuf:"bytes,1,opt,name=appointmentId,proto3" json:"appointmentId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAppointmentRequestData) Reset()         { *m = CancelAppointmentRequestData{} }
func (m *CancelAppointmentRequestData) String() string { return proto.CompactTextString(m) }
func (*CancelAppointmentRequestData) ProtoMessage()    {}
func (*CancelAppointmentRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{23}
}

func (m *CancelAppointmentRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAppointmentRequestData.Unmarshal(m, b)
}
func (m *CancelAppointmentRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAppointmentRequestData.Marshal(b, m, deterministic)
}
func (m *CancelAppointmentRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAppointmentRequestData.Merge(m, src)
}
func (m *CancelAppointmentRequestData) XXX_Size() int {
	return xxx_messageInfo_CancelAppointmentRequestData.Size(m)
}
func (m *CancelAppointmentRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAppointmentRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAppointmentRequestData proto.InternalMessageInfo

func (m *CancelAppointmentRequestData) GetAppointmentId() string {
	if m != nil {
		return m.AppointmentId
	}
	return ""
}

func (m *CancelAppointmentRequestData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CancelAppointmentRequestData) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CancelAppointmentRequestData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type CancelAppointmentResponseData struct {
	Status                string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CancelAppointmentData *CancelAppointmentData `protobuf:"bytes,3,opt,name=cancelAppointmentData,proto3" json:"cancelAppointmentData,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *CancelAppointmentResponseData) Reset()         { *m = CancelAppointmentResponseData{} }
func (m *CancelAppointmentResponseData) String() string { return proto.CompactTextString(m) }
func (*CancelAppointmentResponseData) ProtoMessage()    {}
func (*CancelAppointmentResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{24}
}

func (m *CancelAppointmentResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAppointmentResponseData.Unmarshal(m, b)
}
func (m *CancelAppointmentResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAppointmentResponseData.Marshal(b, m, deterministic)
}
func (m *CancelAppointmentResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAppointmentResponseData.Merge(m, src)
}
func (m *CancelAppointmentResponseData) XXX_Size() int {
	return xxx_messageInfo_CancelAppointmentResponseData.Size(m)
}
func (m *CancelAppointmentResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAppointmentResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAppointmentResponseData proto.InternalMessageInfo

func (m *CancelAppointmentResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CancelAppointmentResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CancelAppointmentResponseData) GetCancelAppointmentData() *CancelAppointmentData {
	if m != nil {
		return m.CancelAppointmentData
	}
	return nil
}

type CancelAppointmentData struct {
	AppointmentId        string   `protobuf:"bytes,1,opt,name=appointmentId,proto3" json:"appointmentId,omitempty"`
	AppointmentStatus    string   `protobuf:"bytes,2,opt,name=appointmentStatus,proto3" json:"appointmentStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAppointmentData) Reset()         { *m = CancelAppointmentData{} }
func (m *CancelAppointmentData) String() string { return proto.CompactTextString(m) }
func (*CancelAppointmentData) ProtoMessage()    {}
func (*CancelAppointmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{25}
}

func (m *CancelAppointmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAppointmentData.Unmarshal(m, b)
}
func (m *CancelAppointmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAppointmentData.Marshal(b, m, deterministic)
}
func (m *CancelAppointmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAppointmentData.Merge(m, src)
}
func (m *CancelAppointmentData) XXX_Size() int {
	return xxx_messageInfo_CancelAppointmentData.Size(m)
}
func (m *CancelAppointmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAppointmentData.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAppointmentData proto.InternalMessageInfo

func (m *CancelAppointmentData) GetAppointmentId() string {
	if m != nil {
		return m.AppointmentId
	}
	return ""
}

func (m *CancelAppointmentData) GetAppointmentStatus() string {
	if m != nil {
		return m.AppointmentStatus
	}
	return ""
}

type PostRescheduleAppointmentRequestData struct {
	AppointmentId        string               `protobuf:"bytes,1,opt,name=appointmentId,proto3" json:"appointmentId,omitempty"`
	ScheduleId           string               `protobuf:"bytes,2,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	AppointmentDate      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=appointmentDate,proto3" json:"appointmentDate,omitempty"`
	AppointmentFromTime  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=appointmentFromTime,proto3" json:"appointmentFromTime,omitempty"`
	HospitalId           string               `protobuf:"bytes,5,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	IsWaitingList        bool                 `protobuf:"varint,6,opt,name=isWaitingList,proto3" json:"isWaitingList,omitempty"`
	Note                 string               `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	ChanelId             int32                `protobuf:"varint,8,opt,name=chanelId,proto3" json:"chanelId,omitempty"`
	UserId               string               `protobuf:"bytes,9,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string               `protobuf:"bytes,10,opt,name=userName,proto3" json:"userName,omitempty"`
	Source               string               `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostRescheduleAppointmentRequestData) Reset()         { *m = PostRescheduleAppointmentRequestData{} }
func (m *PostRescheduleAppointmentRequestData) String() string { return proto.CompactTextString(m) }
func (*PostRescheduleAppointmentRequestData) ProtoMessage()    {}
func (*PostRescheduleAppointmentRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{26}
}

func (m *PostRescheduleAppointmentRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRescheduleAppointmentRequestData.Unmarshal(m, b)
}
func (m *PostRescheduleAppointmentRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRescheduleAppointmentRequestData.Marshal(b, m, deterministic)
}
func (m *PostRescheduleAppointmentRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRescheduleAppointmentRequestData.Merge(m, src)
}
func (m *PostRescheduleAppointmentRequestData) XXX_Size() int {
	return xxx_messageInfo_PostRescheduleAppointmentRequestData.Size(m)
}
func (m *PostRescheduleAppointmentRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRescheduleAppointmentRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_PostRescheduleAppointmentRequestData proto.InternalMessageInfo

func (m *PostRescheduleAppointmentRequestData) GetAppointmentId() string {
	if m != nil {
		return m.AppointmentId
	}
	return ""
}

func (m *PostRescheduleAppointmentRequestData) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *PostRescheduleAppointmentRequestData) GetAppointmentDate() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentDate
	}
	return nil
}

func (m *PostRescheduleAppointmentRequestData) GetAppointmentFromTime() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentFromTime
	}
	return nil
}

func (m *PostRescheduleAppointmentRequestData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *PostRescheduleAppointmentRequestData) GetIsWaitingList() bool {
	if m != nil {
		return m.IsWaitingList
	}
	return false
}

func (m *PostRescheduleAppointmentRequestData) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *PostRescheduleAppointmentRequestData) GetChanelId() int32 {
	if m != nil {
		return m.ChanelId
	}
	return 0
}

func (m *PostRescheduleAppointmentRequestData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PostRescheduleAppointmentRequestData) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PostRescheduleAppointmentRequestData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type PostRescheduleAppointmentResponseData struct {
	Status                    string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message                   string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RescheduleAppointmentData *RescheduleAppointmentData `protobuf:"bytes,3,opt,name=rescheduleAppointmentData,proto3" json:"rescheduleAppointmentData,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *PostRescheduleAppointmentResponseData) Reset()         { *m = PostRescheduleAppointmentResponseData{} }
func (m *PostRescheduleAppointmentResponseData) String() string { return proto.CompactTextString(m) }
func (*PostRescheduleAppointmentResponseData) ProtoMessage()    {}
func (*PostRescheduleAppointmentResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{27}
}

func (m *PostRescheduleAppointmentResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRescheduleAppointmentResponseData.Unmarshal(m, b)
}
func (m *PostRescheduleAppointmentResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRescheduleAppointmentResponseData.Marshal(b, m, deterministic)
}
func (m *PostRescheduleAppointmentResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRescheduleAppointmentResponseData.Merge(m, src)
}
func (m *PostRescheduleAppointmentResponseData) XXX_Size() int {
	return xxx_messageInfo_PostRescheduleAppointmentResponseData.Size(m)
}
func (m *PostRescheduleAppointmentResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRescheduleAppointmentResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_PostRescheduleAppointmentResponseData proto.InternalMessageInfo

func (m *PostRescheduleAppointmentResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PostRescheduleAppointmentResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostRescheduleAppointmentResponseData) GetRescheduleAppointmentData() *RescheduleAppointmentData {
	if m != nil {
		return m.RescheduleAppointmentData
	}
	return nil
}

type RescheduleAppointmentData struct {
	AppointmentId        string               `protobuf:"bytes,1,opt,name=appointmentId,proto3" json:"appointmentId,omitempty"`
	AppointmentStatus    string               `protobuf:"bytes,2,opt,name=appointmentStatus,proto3" json:"appointmentStatus,omitempty"`
	ScheduleId           string               `protobuf:"bytes,3,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	AppointmentDate      *timestamp.Timestamp `protobuf:"bytes,4,opt,name=appointmentDate,proto3" json:"appointmentDate,omitempty"`
	DoctorId             string               `protobuf:"bytes,5,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	CreatedBy            string               `protobuf:"bytes,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreatedFrom          string               `protobuf:"bytes,7,opt,name=createdFrom,proto3" json:"createdFrom,omitempty"`
	ModifiedBy           string               `protobuf:"bytes,8,opt,name=modifiedBy,proto3" json:"modifiedBy,omitempty"`
	ModifiedFrom         string               `protobuf:"bytes,9,opt,name=modifiedFrom,proto3" json:"modifiedFrom,omitempty"`
	ContactId            string               `protobuf:"bytes,10,opt,name=contactId,proto3" json:"contactId,omitempty"`
	HospitalId           string               `protobuf:"bytes,11,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RescheduleAppointmentData) Reset()         { *m = RescheduleAppointmentData{} }
func (m *RescheduleAppointmentData) String() string { return proto.CompactTextString(m) }
func (*RescheduleAppointmentData) ProtoMessage()    {}
func (*RescheduleAppointmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{28}
}

func (m *RescheduleAppointmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RescheduleAppointmentData.Unmarshal(m, b)
}
func (m *RescheduleAppointmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RescheduleAppointmentData.Marshal(b, m, deterministic)
}
func (m *RescheduleAppointmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RescheduleAppointmentData.Merge(m, src)
}
func (m *RescheduleAppointmentData) XXX_Size() int {
	return xxx_messageInfo_RescheduleAppointmentData.Size(m)
}
func (m *RescheduleAppointmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_RescheduleAppointmentData.DiscardUnknown(m)
}

var xxx_messageInfo_RescheduleAppointmentData proto.InternalMessageInfo

func (m *RescheduleAppointmentData) GetAppointmentId() string {
	if m != nil {
		return m.AppointmentId
	}
	return ""
}

func (m *RescheduleAppointmentData) GetAppointmentStatus() string {
	if m != nil {
		return m.AppointmentStatus
	}
	return ""
}

func (m *RescheduleAppointmentData) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *RescheduleAppointmentData) GetAppointmentDate() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentDate
	}
	return nil
}

func (m *RescheduleAppointmentData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *RescheduleAppointmentData) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *RescheduleAppointmentData) GetCreatedFrom() string {
	if m != nil {
		return m.CreatedFrom
	}
	return ""
}

func (m *RescheduleAppointmentData) GetModifiedBy() string {
	if m != nil {
		return m.ModifiedBy
	}
	return ""
}

func (m *RescheduleAppointmentData) GetModifiedFrom() string {
	if m != nil {
		return m.ModifiedFrom
	}
	return ""
}

func (m *RescheduleAppointmentData) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func (m *RescheduleAppointmentData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

type GetAppointmentRequestData struct {
	ContactId            string   `protobuf:"bytes,1,opt,name=contactId,proto3" json:"contactId,omitempty"`
	HospitalId           string   `protobuf:"bytes,2,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	FutureOnly           bool     `protobuf:"varint,3,opt,name=futureOnly,proto3" json:"futureOnly,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppointmentRequestData) Reset()         { *m = GetAppointmentRequestData{} }
func (m *GetAppointmentRequestData) String() string { return proto.CompactTextString(m) }
func (*GetAppointmentRequestData) ProtoMessage()    {}
func (*GetAppointmentRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{29}
}

func (m *GetAppointmentRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppointmentRequestData.Unmarshal(m, b)
}
func (m *GetAppointmentRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppointmentRequestData.Marshal(b, m, deterministic)
}
func (m *GetAppointmentRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppointmentRequestData.Merge(m, src)
}
func (m *GetAppointmentRequestData) XXX_Size() int {
	return xxx_messageInfo_GetAppointmentRequestData.Size(m)
}
func (m *GetAppointmentRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppointmentRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppointmentRequestData proto.InternalMessageInfo

func (m *GetAppointmentRequestData) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func (m *GetAppointmentRequestData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *GetAppointmentRequestData) GetFutureOnly() bool {
	if m != nil {
		return m.FutureOnly
	}
	return false
}

func (m *GetAppointmentRequestData) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAppointmentRequestData) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetAppointmentResponseData struct {
	Status               string              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AppointmentData      *GetAppointmentData `protobuf:"bytes,3,opt,name=appointmentData,proto3" json:"appointmentData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAppointmentResponseData) Reset()         { *m = GetAppointmentResponseData{} }
func (m *GetAppointmentResponseData) String() string { return proto.CompactTextString(m) }
func (*GetAppointmentResponseData) ProtoMessage()    {}
func (*GetAppointmentResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{30}
}

func (m *GetAppointmentResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppointmentResponseData.Unmarshal(m, b)
}
func (m *GetAppointmentResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppointmentResponseData.Marshal(b, m, deterministic)
}
func (m *GetAppointmentResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppointmentResponseData.Merge(m, src)
}
func (m *GetAppointmentResponseData) XXX_Size() int {
	return xxx_messageInfo_GetAppointmentResponseData.Size(m)
}
func (m *GetAppointmentResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppointmentResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppointmentResponseData proto.InternalMessageInfo

func (m *GetAppointmentResponseData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetAppointmentResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAppointmentResponseData) GetAppointmentData() *GetAppointmentData {
	if m != nil {
		return m.AppointmentData
	}
	return nil
}

type GetAppointmentData struct {
	AppointmentId        string               `protobuf:"bytes,1,opt,name=appointmentId,proto3" json:"appointmentId,omitempty"`
	ContactId            string               `protobuf:"bytes,2,opt,name=contactId,proto3" json:"contactId,omitempty"`
	HospitalId           string               `protobuf:"bytes,3,opt,name=hospitalId,proto3" json:"hospitalId,omitempty"`
	DoctorId             string               `protobuf:"bytes,4,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	ScheduleId           string               `protobuf:"bytes,5,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	HospitalName         string               `protobuf:"bytes,6,opt,name=hospitalName,proto3" json:"hospitalName,omitempty"`
	HospitalAlias        string               `protobuf:"bytes,7,opt,name=hospitalAlias,proto3" json:"hospitalAlias,omitempty"`
	AreaId               string               `protobuf:"bytes,8,opt,name=areaId,proto3" json:"areaId,omitempty"`
	AreaName             string               `protobuf:"bytes,9,opt,name=areaName,proto3" json:"areaName,omitempty"`
	DoctorName           string               `protobuf:"bytes,10,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	Specialization       string               `protobuf:"bytes,11,opt,name=specialization,proto3" json:"specialization,omitempty"`
	SpecializationEn     string               `protobuf:"bytes,12,opt,name=specializationEn,proto3" json:"specializationEn,omitempty"`
	ContactName          string               `protobuf:"bytes,13,opt,name=contactName,proto3" json:"contactName,omitempty"`
	AppointmentFromTime  *timestamp.Timestamp `protobuf:"bytes,14,opt,name=appointmentFromTime,proto3" json:"appointmentFromTime,omitempty"`
	AppointmentToTime    *timestamp.Timestamp `protobuf:"bytes,15,opt,name=appointmentToTime,proto3" json:"appointmentToTime,omitempty"`
	AppointmentDate      *timestamp.Timestamp `protobuf:"bytes,16,opt,name=appointmentDate,proto3" json:"appointmentDate,omitempty"`
	IsDelete             bool                 `protobuf:"varint,17,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	StatusId             int32                `protobuf:"varint,18,opt,name=statusId,proto3" json:"statusId,omitempty"`
	IsExpired            bool                 `protobuf:"varint,19,opt,name=isExpired,proto3" json:"isExpired,omitempty"`
	DayDiff              int32                `protobuf:"varint,20,opt,name=dayDiff,proto3" json:"dayDiff,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAppointmentData) Reset()         { *m = GetAppointmentData{} }
func (m *GetAppointmentData) String() string { return proto.CompactTextString(m) }
func (*GetAppointmentData) ProtoMessage()    {}
func (*GetAppointmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88cae9bffbed2d0, []int{31}
}

func (m *GetAppointmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppointmentData.Unmarshal(m, b)
}
func (m *GetAppointmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppointmentData.Marshal(b, m, deterministic)
}
func (m *GetAppointmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppointmentData.Merge(m, src)
}
func (m *GetAppointmentData) XXX_Size() int {
	return xxx_messageInfo_GetAppointmentData.Size(m)
}
func (m *GetAppointmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppointmentData.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppointmentData proto.InternalMessageInfo

func (m *GetAppointmentData) GetAppointmentId() string {
	if m != nil {
		return m.AppointmentId
	}
	return ""
}

func (m *GetAppointmentData) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func (m *GetAppointmentData) GetHospitalId() string {
	if m != nil {
		return m.HospitalId
	}
	return ""
}

func (m *GetAppointmentData) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *GetAppointmentData) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *GetAppointmentData) GetHospitalName() string {
	if m != nil {
		return m.HospitalName
	}
	return ""
}

func (m *GetAppointmentData) GetHospitalAlias() string {
	if m != nil {
		return m.HospitalAlias
	}
	return ""
}

func (m *GetAppointmentData) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *GetAppointmentData) GetAreaName() string {
	if m != nil {
		return m.AreaName
	}
	return ""
}

func (m *GetAppointmentData) GetDoctorName() string {
	if m != nil {
		return m.DoctorName
	}
	return ""
}

func (m *GetAppointmentData) GetSpecialization() string {
	if m != nil {
		return m.Specialization
	}
	return ""
}

func (m *GetAppointmentData) GetSpecializationEn() string {
	if m != nil {
		return m.SpecializationEn
	}
	return ""
}

func (m *GetAppointmentData) GetContactName() string {
	if m != nil {
		return m.ContactName
	}
	return ""
}

func (m *GetAppointmentData) GetAppointmentFromTime() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentFromTime
	}
	return nil
}

func (m *GetAppointmentData) GetAppointmentToTime() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentToTime
	}
	return nil
}

func (m *GetAppointmentData) GetAppointmentDate() *timestamp.Timestamp {
	if m != nil {
		return m.AppointmentDate
	}
	return nil
}

func (m *GetAppointmentData) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *GetAppointmentData) GetStatusId() int32 {
	if m != nil {
		return m.StatusId
	}
	return 0
}

func (m *GetAppointmentData) GetIsExpired() bool {
	if m != nil {
		return m.IsExpired
	}
	return false
}

func (m *GetAppointmentData) GetDayDiff() int32 {
	if m != nil {
		return m.DayDiff
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAreaResponseData)(nil), "prixa.siloam.v1.GetAreaResponseData")
	proto.RegisterType((*AreaData)(nil), "prixa.siloam.v1.AreaData")
	proto.RegisterType((*GetHospitalRequestData)(nil), "prixa.siloam.v1.GetHospitalRequestData")
	proto.RegisterType((*GetHospitalResponseData)(nil), "prixa.siloam.v1.GetHospitalResponseData")
	proto.RegisterType((*HospitalData)(nil), "prixa.siloam.v1.HospitalData")
	proto.RegisterType((*GetSpecialityRequestData)(nil), "prixa.siloam.v1.GetSpecialityRequestData")
	proto.RegisterType((*GetSpecialityResponseData)(nil), "prixa.siloam.v1.GetSpecialityResponseData")
	proto.RegisterType((*SpecialityData)(nil), "prixa.siloam.v1.SpecialityData")
	proto.RegisterType((*GetDoctorsRequestData)(nil), "prixa.siloam.v1.GetDoctorsRequestData")
	proto.RegisterType((*GetDoctorsResponseData)(nil), "prixa.siloam.v1.GetDoctorsResponseData")
	proto.RegisterType((*DoctorData)(nil), "prixa.siloam.v1.DoctorData")
	proto.RegisterType((*GetDoctorLeaveHospitalRequestData)(nil), "prixa.siloam.v1.GetDoctorLeaveHospitalRequestData")
	proto.RegisterType((*GetDoctorLeaveHospitalResponseData)(nil), "prixa.siloam.v1.GetDoctorLeaveHospitalResponseData")
	proto.RegisterType((*DoctorLeaveHospitalData)(nil), "prixa.siloam.v1.DoctorLeaveHospitalData")
	proto.RegisterType((*GetSchedulesPerWeeksRequestData)(nil), "prixa.siloam.v1.GetSchedulesPerWeeksRequestData")
	proto.RegisterType((*GetSchedulesPerWeeksResponseData)(nil), "prixa.siloam.v1.GetSchedulesPerWeeksResponseData")
	proto.RegisterType((*SchedulesPerWeeksData)(nil), "prixa.siloam.v1.SchedulesPerWeeksData")
	proto.RegisterType((*GetTimeSlotRequestData)(nil), "prixa.siloam.v1.GetTimeSlotRequestData")
	proto.RegisterType((*GetTimeSlotResponseData)(nil), "prixa.siloam.v1.GetTimeSlotResponseData")
	proto.RegisterType((*TimeSlotData)(nil), "prixa.siloam.v1.TimeSlotData")
	proto.RegisterType((*PostAppointmentRequestData)(nil), "prixa.siloam.v1.PostAppointmentRequestData")
	proto.RegisterType((*PostAppointmentResponseData)(nil), "prixa.siloam.v1.PostAppointmentResponseData")
	proto.RegisterType((*PostAppointmentData)(nil), "prixa.siloam.v1.PostAppointmentData")
	proto.RegisterType((*CancelAppointmentRequestData)(nil), "prixa.siloam.v1.CancelAppointmentRequestData")
	proto.RegisterType((*CancelAppointmentResponseData)(nil), "prixa.siloam.v1.CancelAppointmentResponseData")
	proto.RegisterType((*CancelAppointmentData)(nil), "prixa.siloam.v1.CancelAppointmentData")
	proto.RegisterType((*PostRescheduleAppointmentRequestData)(nil), "prixa.siloam.v1.PostRescheduleAppointmentRequestData")
	proto.RegisterType((*PostRescheduleAppointmentResponseData)(nil), "prixa.siloam.v1.PostRescheduleAppointmentResponseData")
	proto.RegisterType((*RescheduleAppointmentData)(nil), "prixa.siloam.v1.RescheduleAppointmentData")
	proto.RegisterType((*GetAppointmentRequestData)(nil), "prixa.siloam.v1.GetAppointmentRequestData")
	proto.RegisterType((*GetAppointmentResponseData)(nil), "prixa.siloam.v1.GetAppointmentResponseData")
	proto.RegisterType((*GetAppointmentData)(nil), "prixa.siloam.v1.GetAppointmentData")
}

func init() { proto.RegisterFile("proto/siloam/v1/Siloam.proto", fileDescriptor_f88cae9bffbed2d0) }

var fileDescriptor_f88cae9bffbed2d0 = []byte{
	// 2029 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xcd, 0x6f, 0x1b, 0xc7,
	0x15, 0xc7, 0x92, 0x5c, 0x7a, 0xf9, 0x24, 0xd9, 0xce, 0xd8, 0x8a, 0x69, 0xc5, 0xb1, 0x94, 0x8d,
	0x1c, 0x7f, 0x49, 0x64, 0xad, 0xb6, 0x01, 0x8a, 0xf6, 0x10, 0xc9, 0x72, 0xe4, 0x00, 0xaa, 0x92,
	0x8e, 0x54, 0x24, 0x68, 0xeb, 0x16, 0x23, 0x72, 0x28, 0x2d, 0xbc, 0xdc, 0x65, 0xb9, 0x43, 0x27,
	0x4a, 0xd1, 0x5e, 0x7b, 0x0b, 0x7a, 0xca, 0xad, 0x28, 0x8a, 0xfe, 0x01, 0x05, 0xd2, 0x4b, 0x51,
	0xa0, 0x87, 0xa2, 0xe8, 0xb5, 0xe8, 0x5f, 0x50, 0x03, 0xba, 0xf4, 0xdf, 0x28, 0x66, 0x66, 0x3f,
	0xe6, 0x63, 0x57, 0x62, 0xc4, 0xf8, 0xc6, 0xf7, 0x35, 0x33, 0x3b, 0xef, 0xf7, 0x7e, 0xf3, 0x66,
	0x08, 0xb7, 0x46, 0xe3, 0x98, 0xc5, 0xdd, 0x24, 0x08, 0x63, 0x32, 0xec, 0xbe, 0x78, 0xd4, 0xdd,
	0x17, 0xbf, 0x3a, 0x42, 0x8d, 0xae, 0x8c, 0xc6, 0xc1, 0x67, 0xa4, 0x23, 0xad, 0x9d, 0x17, 0x8f,
	0x96, 0x96, 0x8f, 0xe2, 0xf8, 0x28, 0xa4, 0x5d, 0x61, 0x3e, 0x9c, 0x0c, 0xba, 0x2c, 0x18, 0xd2,
	0x84, 0x91, 0xe1, 0x48, 0x46, 0x2c, 0xbd, 0x7b, 0x14, 0xb0, 0xe3, 0xc9, 0x61, 0xa7, 0x17, 0x0f,
	0xbb, 0xc3, 0x4f, 0x03, 0xf6, 0x3c, 0xfe, 0xb4, 0x7b, 0x14, 0xaf, 0x0b, 0xe3, 0xfa, 0x0b, 0x12,
	0x06, 0x7d, 0xc2, 0xe2, 0x71, 0xd2, 0xcd, 0x7f, 0xca, 0x38, 0xff, 0x37, 0x70, 0x6d, 0x87, 0xb2,
	0xcd, 0x31, 0x25, 0x98, 0x26, 0xa3, 0x38, 0x4a, 0xe8, 0x36, 0x61, 0x04, 0xbd, 0x0e, 0xcd, 0x84,
	0x11, 0x36, 0x49, 0xda, 0xce, 0x8a, 0x73, 0xaf, 0x85, 0x53, 0x09, 0xb5, 0xe1, 0xd2, 0x90, 0x26,
	0x09, 0x39, 0xa2, 0xed, 0x9a, 0x30, 0x64, 0x22, 0xfa, 0x2e, 0x78, 0x64, 0x4c, 0x09, 0x8f, 0x6e,
	0xd7, 0x57, 0xea, 0xf7, 0xe6, 0x36, 0x6e, 0x76, 0x8c, 0xaf, 0xe8, 0x6c, 0xa6, 0x0e, 0x38, 0x77,
	0xf5, 0x31, 0x78, 0x99, 0x96, 0x4f, 0xca, 0xf5, 0x1f, 0xf4, 0xb3, 0x49, 0xa5, 0x84, 0x10, 0x34,
	0x22, 0x32, 0xcc, 0x66, 0x14, 0xbf, 0xd1, 0x12, 0x78, 0xc1, 0x90, 0x1c, 0xd1, 0x1f, 0xe3, 0xdd,
	0x76, 0x5d, 0xe8, 0x73, 0xd9, 0xa7, 0xf0, 0xfa, 0x0e, 0x65, 0x4f, 0xe3, 0x64, 0x14, 0x30, 0x12,
	0x62, 0xfa, 0xcb, 0x09, 0x4d, 0x98, 0x98, 0xe1, 0x01, 0x5c, 0x8d, 0xa3, 0x0f, 0x86, 0xa3, 0x90,
	0x0e, 0x69, 0xc4, 0x08, 0x0b, 0xe2, 0x48, 0xcc, 0xe5, 0x61, 0x4b, 0x8f, 0x96, 0xf3, 0xd5, 0x88,
	0x79, 0xb7, 0x2e, 0x9d, 0xbe, 0x5c, 0xae, 0xff, 0xce, 0x69, 0x64, 0xcb, 0xf2, 0xbf, 0x70, 0xe0,
	0x86, 0x36, 0xcf, 0x4c, 0xfb, 0xb7, 0x09, 0xf3, 0xc7, 0xe9, 0x48, 0xca, 0x1e, 0xbe, 0x69, 0xed,
	0xe1, 0x53, 0xc5, 0x09, 0x6b, 0x21, 0xfe, 0xbf, 0x6b, 0x30, 0xaf, 0x9a, 0xd1, 0x6d, 0x80, 0xcc,
	0x21, 0xdf, 0x54, 0x45, 0xc3, 0xb7, 0x23, 0x93, 0xf6, 0xc5, 0xfa, 0xb2, 0x8f, 0xc5, 0x96, 0x3e,
	0x4f, 0x42, 0x5d, 0x49, 0xc2, 0x75, 0x70, 0x49, 0x18, 0x90, 0xa4, 0xdd, 0x10, 0x4a, 0x29, 0xf0,
	0x6f, 0x24, 0xfd, 0xfe, 0x98, 0x26, 0x49, 0xdb, 0x95, 0xdf, 0x98, 0x8a, 0xc8, 0x87, 0xf9, 0xd1,
	0x71, 0x1c, 0xd1, 0xbd, 0xc9, 0xf0, 0x90, 0x8e, 0x1f, 0xb5, 0x9b, 0xc2, 0xac, 0xe9, 0xd0, 0x2d,
	0x68, 0x85, 0x71, 0x74, 0x14, 0xb0, 0x49, 0x9f, 0xb6, 0x2f, 0xad, 0x38, 0xf7, 0x6a, 0xb8, 0x50,
	0x08, 0x2b, 0x61, 0x4c, 0x5a, 0xbd, 0xd4, 0x9a, 0x29, 0x14, 0x00, 0xb5, 0x34, 0x00, 0x2d, 0x49,
	0x6c, 0xee, 0xf1, 0xf5, 0x83, 0x04, 0x4b, 0x26, 0x6b, 0x40, 0x9a, 0x33, 0x80, 0xf4, 0x18, 0xda,
	0x3b, 0x94, 0xed, 0x8f, 0x68, 0x2f, 0x20, 0x61, 0xc0, 0x4e, 0x54, 0x28, 0xdd, 0xb5, 0xf7, 0xb6,
	0x80, 0x88, 0x62, 0xf2, 0xbf, 0x74, 0xe0, 0xa6, 0x31, 0xca, 0x4c, 0x40, 0xd9, 0x81, 0xcb, 0x49,
	0x3e, 0x96, 0x02, 0x95, 0x65, 0x0b, 0x2a, 0xfb, 0x9a, 0x1b, 0x36, 0xc2, 0xfc, 0xbf, 0x39, 0x70,
	0x59, 0x77, 0xe1, 0x09, 0x2a, 0x9c, 0x72, 0xc8, 0x68, 0x3a, 0x0e, 0x9a, 0x42, 0xe6, 0x5b, 0xf8,
	0x24, 0xca, 0x40, 0x63, 0xea, 0xd1, 0x3b, 0xea, 0x5a, 0xf7, 0x0a, 0xf8, 0x18, 0x5a, 0x0e, 0xa4,
	0x20, 0x79, 0x1c, 0x53, 0x01, 0x24, 0x0f, 0x4b, 0x41, 0x4b, 0x8d, 0x6b, 0xa4, 0xe6, 0x2b, 0x07,
	0x16, 0x77, 0x28, 0xdb, 0x8e, 0x7b, 0x9c, 0xd6, 0xd4, 0xc4, 0xdc, 0x06, 0xe8, 0x0b, 0xad, 0x98,
	0x2f, 0x05, 0x7d, 0xa1, 0x41, 0x6f, 0x83, 0x27, 0x25, 0xbb, 0xb2, 0x73, 0x83, 0x91, 0xdd, 0x7a,
	0x65, 0x76, 0xd1, 0x43, 0x63, 0xc7, 0x1a, 0xba, 0xab, 0x66, 0xf4, 0x7f, 0xeb, 0x08, 0x66, 0xca,
	0x17, 0x3d, 0x13, 0x0e, 0xbe, 0x9f, 0x7d, 0xa7, 0x82, 0x81, 0x37, 0x2c, 0x0c, 0x6c, 0xe7, 0x2e,
	0x58, 0x71, 0xf7, 0xff, 0x53, 0x03, 0x28, 0x4c, 0x7c, 0xa7, 0xf3, 0x3d, 0x91, 0xf3, 0x17, 0x5b,
	0xa1, 0xe4, 0xfb, 0x73, 0xc1, 0x8c, 0x05, 0x49, 0x98, 0x7a, 0x0b, 0x3f, 0xf5, 0x12, 0xfc, 0xe8,
	0xa4, 0xd4, 0xb0, 0x48, 0x29, 0x23, 0x1a, 0x57, 0x21, 0x9a, 0x0e, 0x20, 0x7d, 0x2e, 0x91, 0x5b,
	0x49, 0x1f, 0x25, 0x16, 0xb4, 0x01, 0xd7, 0x6d, 0xed, 0x93, 0x48, 0xf0, 0x49, 0x0b, 0x97, 0xda,
	0xf8, 0xda, 0xb3, 0x55, 0x88, 0xd1, 0x3d, 0xb9, 0x76, 0x55, 0xa7, 0x21, 0xb2, 0x65, 0x20, 0x32,
	0x81, 0xb7, 0xf2, 0xdc, 0xee, 0x52, 0xf2, 0x82, 0x96, 0x1d, 0x40, 0xf7, 0x4b, 0x58, 0xa3, 0x75,
	0xfa, 0x72, 0xd9, 0xfd, 0xc4, 0x31, 0x91, 0x35, 0x0d, 0x4e, 0x79, 0x0d, 0xfb, 0x55, 0xb3, 0xce,
	0x84, 0xae, 0x43, 0xb8, 0xd1, 0xb7, 0x07, 0x55, 0xa0, 0x76, 0xaf, 0x02, 0x6a, 0x96, 0x3f, 0xae,
	0x1a, 0xc8, 0xff, 0x87, 0x03, 0x37, 0x2a, 0x82, 0xce, 0x44, 0xa4, 0x8e, 0xa0, 0x9a, 0x85, 0xa0,
	0x77, 0xc1, 0x1b, 0x8c, 0xe3, 0xe1, 0x36, 0x61, 0x92, 0x6f, 0xe6, 0x36, 0x96, 0x3a, 0xb2, 0x7f,
	0xea, 0x64, 0xfd, 0x53, 0xe7, 0x20, 0xeb, 0x9f, 0x70, 0xee, 0x8b, 0x36, 0xa0, 0xc9, 0x62, 0x11,
	0xd5, 0x38, 0x37, 0x2a, 0xf5, 0xf4, 0x13, 0x58, 0xe6, 0xe4, 0xde, 0x3b, 0xa6, 0xfd, 0x49, 0x48,
	0x93, 0x8f, 0xe8, 0xf8, 0x63, 0x4a, 0x9f, 0x27, 0x17, 0xcc, 0xf9, 0x1d, 0x2b, 0xe7, 0x8a, 0x63,
	0x91, 0xf5, 0xaf, 0x1c, 0x58, 0x29, 0x9f, 0x75, 0xa6, 0x9c, 0xff, 0x0c, 0x16, 0x13, 0x73, 0x48,
	0x25, 0xe3, 0xef, 0xd8, 0x07, 0x4c, 0x99, 0x37, 0x2e, 0x1f, 0xc4, 0xff, 0x63, 0x1d, 0x16, 0x4b,
	0x03, 0x78, 0x3e, 0xb3, 0x90, 0xa2, 0x4d, 0x29, 0x34, 0xe7, 0xe6, 0x5b, 0xc5, 0x4a, 0xbd, 0x84,
	0xbd, 0xd2, 0x91, 0xf2, 0x16, 0x87, 0x67, 0xd7, 0xc5, 0x96, 0x5e, 0x9c, 0x56, 0xa9, 0xee, 0xe0,
	0x64, 0xc4, 0xd7, 0xe2, 0x0a, 0x4f, 0x43, 0x8b, 0xae, 0x42, 0xbd, 0x4f, 0x4e, 0x04, 0xfd, 0xb8,
	0x98, 0xff, 0xcc, 0x10, 0xc7, 0xe1, 0x21, 0x38, 0x66, 0x0a, 0xc4, 0x71, 0x51, 0x22, 0x4e, 0x44,
	0x79, 0xd3, 0x20, 0x4e, 0xc4, 0xe8, 0xe7, 0x5b, 0xcb, 0x3a, 0xdf, 0x4c, 0x1e, 0x83, 0x12, 0x1e,
	0x2b, 0x1a, 0xa5, 0x39, 0xb5, 0x51, 0xf2, 0xff, 0x2a, 0x0f, 0x28, 0x3e, 0xcf, 0x7e, 0x18, 0xb3,
	0x57, 0x8a, 0x62, 0xb4, 0x0b, 0x57, 0xc8, 0x68, 0x14, 0x07, 0x11, 0xe3, 0x4d, 0xf7, 0x74, 0xd5,
	0xba, 0xd5, 0x3c, 0x7d, 0xb9, 0x5c, 0x5b, 0x71, 0xb0, 0x19, 0x9a, 0x75, 0xe3, 0xc5, 0xd2, 0x67,
	0xed, 0xc6, 0x59, 0x3a, 0xd2, 0x99, 0xdd, 0xf8, 0x81, 0xe2, 0x84, 0xb5, 0x10, 0xff, 0xbf, 0x0e,
	0xcc, 0xab, 0xe6, 0x73, 0x61, 0xae, 0x74, 0xe3, 0x3c, 0xee, 0x27, 0x71, 0x24, 0x97, 0xe5, 0x62,
	0x4b, 0xcf, 0xbf, 0x28, 0x48, 0xde, 0x9f, 0x84, 0xa1, 0xd8, 0x32, 0x0f, 0xa7, 0x92, 0x06, 0xc4,
	0xc6, 0x85, 0x80, 0xe8, 0x4e, 0x0b, 0x44, 0xff, 0x5f, 0x2e, 0x2c, 0x7d, 0x14, 0x27, 0x6c, 0xb3,
	0xc8, 0x84, 0x0a, 0x98, 0x55, 0x68, 0xf5, 0x8e, 0x49, 0x14, 0xd1, 0x02, 0x2f, 0x22, 0x79, 0x9f,
	0x38, 0xb8, 0x30, 0x94, 0x81, 0xa0, 0x76, 0x61, 0x10, 0xa0, 0x03, 0xb8, 0xa6, 0xa8, 0xde, 0xcf,
	0x76, 0x62, 0x7a, 0x58, 0x95, 0x85, 0x73, 0xe8, 0x2b, 0x89, 0x6b, 0x58, 0xd0, 0x57, 0x72, 0xa8,
	0x57, 0x89, 0x3b, 0x6d, 0x95, 0x34, 0xab, 0xab, 0x64, 0x0d, 0x16, 0x82, 0xe4, 0x63, 0x12, 0xb0,
	0x20, 0x3a, 0xda, 0x0d, 0x12, 0x26, 0xf8, 0xc5, 0xcb, 0x17, 0xac, 0x1b, 0xd1, 0x52, 0xda, 0x3c,
	0x79, 0xda, 0x7e, 0xcb, 0x26, 0xea, 0x3d, 0x68, 0x1d, 0x06, 0x63, 0x76, 0x2c, 0x36, 0xb9, 0x35,
	0xf5, 0x96, 0x14, 0x41, 0xe8, 0x81, 0x71, 0x7f, 0x03, 0x6d, 0x16, 0xfd, 0x1e, 0xf7, 0x23, 0x98,
	0xa7, 0x43, 0x12, 0x84, 0x9b, 0xe9, 0x55, 0x50, 0x10, 0xcd, 0xd6, 0xfa, 0xe9, 0xcb, 0xe5, 0xfb,
	0x70, 0xf7, 0xe7, 0x3f, 0x25, 0xeb, 0x9f, 0x7f, 0x6b, 0xfd, 0x7b, 0x9d, 0x5f, 0xdc, 0x79, 0xb8,
	0xfe, 0xec, 0xe1, 0x7b, 0x99, 0xb8, 0xfe, 0xec, 0x61, 0x87, 0xff, 0x7e, 0xf6, 0xab, 0x8d, 0xb5,
	0xef, 0xfc, 0x7a, 0x15, 0x6b, 0x43, 0xa0, 0xb7, 0xa0, 0x39, 0x49, 0x28, 0xdf, 0xaf, 0x79, 0x73,
	0xbf, 0x52, 0x83, 0xa8, 0xf4, 0x78, 0x32, 0xee, 0xd1, 0xf6, 0x42, 0x5a, 0xe9, 0x42, 0xe2, 0x47,
	0x04, 0xf7, 0x10, 0x84, 0x78, 0x59, 0x1e, 0x11, 0x99, 0xec, 0xff, 0xc1, 0x81, 0x37, 0x2c, 0x1c,
	0xcf, 0xc4, 0x1e, 0x7b, 0x26, 0xa8, 0x49, 0x0a, 0xc1, 0x55, 0x8b, 0x40, 0x8c, 0x89, 0x05, 0x8f,
	0x98, 0xc1, 0xfe, 0xff, 0x9a, 0x70, 0xad, 0xc4, 0x11, 0xad, 0xc2, 0x82, 0xe2, 0x9a, 0x93, 0x8a,
	0xae, 0x34, 0xbc, 0xf6, 0x62, 0xb1, 0xda, 0x3a, 0xd6, 0x95, 0x68, 0xfb, 0x02, 0x6c, 0x6c, 0x17,
	0xe0, 0x6e, 0x79, 0x01, 0x9e, 0x4f, 0x45, 0xa5, 0x85, 0xf7, 0x14, 0x5e, 0x53, 0xd4, 0x07, 0xd3,
	0x12, 0x94, 0x1d, 0xc4, 0xf7, 0x40, 0xaf, 0xa2, 0xa6, 0xa0, 0x4d, 0xa3, 0x7a, 0xf8, 0xd5, 0x23,
	0x66, 0x34, 0xbd, 0x26, 0x88, 0xdf, 0xe8, 0x96, 0x4a, 0x63, 0xf2, 0x4e, 0xa0, 0xd0, 0x97, 0xce,
	0xe9, 0x2d, 0x8b, 0xd3, 0x79, 0x74, 0x1c, 0x31, 0xd2, 0xe3, 0xd9, 0x81, 0x34, 0x3a, 0x53, 0xa0,
	0x15, 0x98, 0x4b, 0x05, 0x01, 0x4c, 0x79, 0x16, 0xab, 0x2a, 0xf4, 0x03, 0x98, 0xeb, 0x13, 0x46,
	0x3f, 0x1c, 0x6c, 0xf1, 0x22, 0x14, 0xb8, 0x3f, 0xfb, 0xdb, 0x55, 0x77, 0xf1, 0xde, 0x12, 0x92,
	0x5e, 0x1e, 0xbe, 0x90, 0xbe, 0xb7, 0x28, 0x3a, 0xbe, 0x06, 0xa5, 0x6e, 0xd3, 0xe2, 0x50, 0x55,
	0x7c, 0x94, 0xf4, 0x01, 0x67, 0x37, 0x88, 0xe8, 0xa3, 0xf6, 0x15, 0x39, 0x8a, 0xaa, 0x33, 0x7c,
	0x36, 0xda, 0x57, 0x2d, 0x9f, 0x0d, 0xee, 0xa3, 0x31, 0xc2, 0x6b, 0xd2, 0x47, 0x2b, 0x71, 0xb5,
	0x95, 0x43, 0x67, 0xb6, 0xfd, 0xd7, 0xac, 0x36, 0x50, 0x6f, 0x8c, 0xae, 0x9f, 0xdb, 0x18, 0x2d,
	0xda, 0x8d, 0x91, 0xff, 0x27, 0x07, 0x6e, 0x3d, 0x26, 0x51, 0x8f, 0x86, 0x15, 0xa7, 0xda, 0x5a,
	0x69, 0xc9, 0xe5, 0x1c, 0x68, 0x94, 0x5e, 0xc1, 0x58, 0xb5, 0x2a, 0xc6, 0x52, 0x99, 0xa9, 0xae,
	0x33, 0x93, 0xc2, 0x66, 0x0d, 0x95, 0xcd, 0xfc, 0x3f, 0x3b, 0xf0, 0x66, 0xc9, 0x2a, 0x67, 0x6d,
	0xfe, 0x7b, 0xe6, 0x90, 0x0a, 0x73, 0xd9, 0xcd, 0xff, 0xe3, 0x32, 0x6f, 0x5c, 0x3e, 0x88, 0xff,
	0x1c, 0x16, 0x4b, 0xfd, 0xa7, 0xa4, 0xb0, 0x35, 0x8d, 0x08, 0x64, 0xc3, 0x9e, 0x7e, 0x80, 0x6d,
	0xf0, 0xbf, 0x68, 0xc0, 0x2a, 0xa7, 0x4b, 0x4c, 0xb3, 0x4a, 0xac, 0x48, 0x66, 0xb7, 0x3c, 0x99,
	0x4a, 0x96, 0x8c, 0x75, 0xe8, 0x9d, 0x40, 0xed, 0xac, 0x4e, 0xe0, 0x1b, 0xed, 0x6e, 0xab, 0x1a,
	0x9b, 0xc6, 0xcc, 0x8d, 0xcd, 0xb4, 0xdd, 0xca, 0x5a, 0x29, 0x81, 0x56, 0xb5, 0x21, 0x65, 0x44,
	0xea, 0x83, 0xc7, 0x79, 0x33, 0xe7, 0x51, 0x37, 0x0f, 0xce, 0xf5, 0x4a, 0xbd, 0xb4, 0xa6, 0xa9,
	0x17, 0xa8, 0xac, 0x97, 0x39, 0xad, 0x5e, 0xfe, 0xe9, 0xc0, 0x9d, 0x33, 0x00, 0x31, 0x53, 0xdd,
	0x1c, 0xc3, 0xcd, 0x71, 0xd9, 0xb0, 0x4a, 0xed, 0x3c, 0xb0, 0x6a, 0x07, 0x57, 0x45, 0xe0, 0xea,
	0xc1, 0xfc, 0xbf, 0xd4, 0xe1, 0x66, 0x65, 0xe0, 0xab, 0x28, 0x24, 0xe3, 0x74, 0xab, 0x5b, 0xa7,
	0x5b, 0x49, 0xcf, 0xd0, 0xf8, 0xfa, 0x3d, 0x83, 0xca, 0xf9, 0xae, 0xc1, 0xf9, 0xfc, 0xfc, 0x1c,
	0x53, 0xc2, 0x68, 0x7f, 0xeb, 0x24, 0x7d, 0xef, 0x2b, 0x14, 0xe2, 0xfc, 0x94, 0x02, 0x87, 0x74,
	0x8a, 0x36, 0x55, 0xc5, 0xbf, 0x60, 0x18, 0xf7, 0x83, 0x41, 0x20, 0x06, 0x90, 0xc7, 0xb7, 0xa2,
	0xe1, 0x67, 0x42, 0x26, 0x89, 0x21, 0xe4, 0x09, 0xae, 0xe9, 0xce, 0x39, 0xc3, 0xf5, 0x53, 0x69,
	0xce, 0x3c, 0x95, 0xfc, 0xbf, 0xcb, 0xe7, 0xff, 0x0a, 0x06, 0xba, 0xab, 0x8e, 0x6d, 0xb1, 0x8f,
	0x32, 0xcd, 0x7d, 0xfb, 0x0d, 0xa4, 0xaa, 0x54, 0x6f, 0x03, 0x0c, 0x26, 0x6c, 0x32, 0xa6, 0x1f,
	0x46, 0xe1, 0x49, 0x7a, 0x3f, 0x54, 0x34, 0xe8, 0x3a, 0xb8, 0x61, 0x30, 0x0c, 0x58, 0xfa, 0x0e,
	0x22, 0x05, 0x8e, 0xfc, 0x78, 0x30, 0x48, 0x28, 0x4b, 0x1f, 0x3d, 0x52, 0xc9, 0xff, 0xbd, 0x03,
	0x4b, 0xe6, 0xfa, 0x67, 0x2a, 0x98, 0x1f, 0x56, 0x35, 0xc7, 0x6f, 0x5b, 0x65, 0xa2, 0xcf, 0x5b,
	0xde, 0x1b, 0x7f, 0xd9, 0x04, 0x64, 0xfb, 0x4d, 0x59, 0x0e, 0x5a, 0x6a, 0x6b, 0x67, 0xa7, 0xb6,
	0x7e, 0xe6, 0xbb, 0x53, 0xc3, 0x6e, 0x56, 0x94, 0xd2, 0x71, 0xad, 0xd2, 0x31, 0x9b, 0x91, 0x66,
	0xc9, 0x2b, 0xcd, 0x2a, 0x2c, 0x64, 0xf2, 0xa6, 0xf8, 0x9b, 0x4d, 0x02, 0x5c, 0x57, 0x2a, 0x6f,
	0x39, 0x5e, 0xe5, 0x9f, 0x5e, 0x2d, 0xe3, 0x4f, 0x2f, 0xbd, 0x55, 0x02, 0xab, 0x55, 0x52, 0xfe,
	0xb7, 0x91, 0x6f, 0xe4, 0x29, 0xb0, 0x0d, 0xad, 0xfd, 0xdf, 0xc0, 0x93, 0x48, 0xde, 0xcd, 0xb0,
	0xa5, 0x37, 0x9b, 0xdd, 0x05, 0xbb, 0xd9, 0xad, 0xb8, 0x3c, 0x5c, 0xfe, 0x06, 0x2f, 0x0f, 0x57,
	0x2e, 0x72, 0x79, 0x28, 0xa1, 0xb9, 0xab, 0x17, 0xa2, 0xb9, 0x20, 0xd9, 0xa6, 0x21, 0x65, 0x54,
	0xb4, 0xbe, 0x1e, 0xce, 0x65, 0x6e, 0x4b, 0xb2, 0xd7, 0x49, 0x24, 0xca, 0x2f, 0x97, 0x39, 0x46,
	0x83, 0xe4, 0xc9, 0x67, 0xa3, 0x60, 0x4c, 0x65, 0xd7, 0xeb, 0xe1, 0x42, 0xc1, 0xeb, 0xac, 0x4f,
	0x4e, 0xb6, 0x83, 0xc1, 0x40, 0x74, 0xbc, 0x2e, 0xce, 0xc4, 0xc3, 0xa6, 0x58, 0xd4, 0xb7, 0xff,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x4a, 0x17, 0x9e, 0x6a, 0x20, 0x00, 0x00,
}
