// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/myprotection/v1/MyProtection.proto

package prixa_myprotection_v1

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PostStatusTransactionRequestData) Validate() error {
	return nil
}
func (this *GetListTransactionData) Validate() error {
	if this.AccessToken == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("AccessToken", fmt.Errorf(`value '%v' must not be an empty string`, this.AccessToken))
	}
	return nil
}
func (this *TransactionResponseData) Validate() error {
	if this.StatusTransaction != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.StatusTransaction); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("StatusTransaction", err)
		}
	}
	return nil
}
func (this *StatusTransactionData) Validate() error {
	for _, item := range this.TransactionsData {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TransactionsData", err)
			}
		}
	}
	return nil
}
func (this *TransactionData) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.CartData != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CartData); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CartData", err)
		}
	}
	return nil
}
func (this *TransactionCartData) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	for _, item := range this.MemberProductsData {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("MemberProductsData", err)
			}
		}
	}
	return nil
}
func (this *TransactionMemberProductData) Validate() error {
	return nil
}
func (this *MemberData) Validate() error {
	return nil
}
func (this *GetProductPlanResponseData) Validate() error {
	if this.ProductPlan != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ProductPlan); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ProductPlan", err)
		}
	}
	return nil
}
func (this *ProductPlanData) Validate() error {
	if this.Plan != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Plan); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Plan", err)
		}
	}
	return nil
}
func (this *PlanData) Validate() error {
	for _, item := range this.ProtectionList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ProtectionList", err)
			}
		}
	}
	for _, item := range this.OutpatientList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("OutpatientList", err)
			}
		}
	}
	return nil
}
func (this *PlanOutPatientData) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	return nil
}
func (this *ProtectionData) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	return nil
}
func (this *SubmitJalanPrimaRequestData) Validate() error {
	if this.StartDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.StartDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("StartDate", err)
		}
	}
	if this.EndDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EndDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EndDate", err)
		}
	}
	if this.Dob != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Dob); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Dob", err)
		}
	}
	for _, item := range this.Members {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Members", err)
			}
		}
	}
	return nil
}
func (this *GetPremiumStepRequestData) Validate() error {
	if this.StartDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.StartDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("StartDate", err)
		}
	}
	if this.EndDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EndDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EndDate", err)
		}
	}
	for _, item := range this.Members {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Members", err)
			}
		}
	}
	return nil
}
func (this *GetPremiumStepResponseData) Validate() error {
	if this.PremiumData != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PremiumData); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PremiumData", err)
		}
	}
	return nil
}
func (this *GetPremiumStep2RequestData) Validate() error {
	if this.StartDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.StartDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("StartDate", err)
		}
	}
	if this.EndDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EndDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EndDate", err)
		}
	}
	for _, item := range this.Members {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Members", err)
			}
		}
	}
	return nil
}
func (this *GetPremiumStep2ResponseData) Validate() error {
	if this.PremiumData != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PremiumData); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PremiumData", err)
		}
	}
	return nil
}
func (this *PremiumStepData) Validate() error {
	for _, item := range this.Benefits {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Benefits", err)
			}
		}
	}
	if this.OutPatientData != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.OutPatientData); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("OutPatientData", err)
		}
	}
	for _, item := range this.OutPatientBenefits {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("OutPatientBenefits", err)
			}
		}
	}
	if this.StaticBenefitData != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.StaticBenefitData); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("StaticBenefitData", err)
		}
	}
	return nil
}
func (this *StaticBenefitData) Validate() error {
	if this.Outpatient != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Outpatient); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Outpatient", err)
		}
	}
	return nil
}
func (this *StaticBenefitOutPatientData) Validate() error {
	return nil
}
func (this *BenefitData) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	for _, item := range this.Pivots {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Pivots", err)
			}
		}
	}
	return nil
}
func (this *PivotData) Validate() error {
	return nil
}
func (this *OutPatientData) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	for _, item := range this.Benefits {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Benefits", err)
			}
		}
	}
	return nil
}
func (this *OutPatientBenefitData) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	if this.PivotData != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PivotData); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PivotData", err)
		}
	}
	return nil
}
