// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/v1/User.proto

package prixa_user_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthData struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string   `protobuf:"bytes,3,opt,name=passwordConfirmation,proto3" json:"passwordConfirmation,omitempty"`
	DiagnosticSessionID  string   `protobuf:"bytes,4,opt,name=diagnosticSessionID,proto3" json:"diagnosticSessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthData) Reset()         { *m = AuthData{} }
func (m *AuthData) String() string { return proto.CompactTextString(m) }
func (*AuthData) ProtoMessage()    {}
func (*AuthData) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{0}
}

func (m *AuthData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthData.Unmarshal(m, b)
}
func (m *AuthData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthData.Marshal(b, m, deterministic)
}
func (m *AuthData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthData.Merge(m, src)
}
func (m *AuthData) XXX_Size() int {
	return xxx_messageInfo_AuthData.Size(m)
}
func (m *AuthData) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthData.DiscardUnknown(m)
}

var xxx_messageInfo_AuthData proto.InternalMessageInfo

func (m *AuthData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthData) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *AuthData) GetDiagnosticSessionID() string {
	if m != nil {
		return m.DiagnosticSessionID
	}
	return ""
}

type ChronicConditionData struct {
	Hypertensive         bool     `protobuf:"varint,1,opt,name=hypertensive,proto3" json:"hypertensive,omitempty"`
	Diabetic             bool     `protobuf:"varint,2,opt,name=diabetic,proto3" json:"diabetic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChronicConditionData) Reset()         { *m = ChronicConditionData{} }
func (m *ChronicConditionData) String() string { return proto.CompactTextString(m) }
func (*ChronicConditionData) ProtoMessage()    {}
func (*ChronicConditionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{1}
}

func (m *ChronicConditionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChronicConditionData.Unmarshal(m, b)
}
func (m *ChronicConditionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChronicConditionData.Marshal(b, m, deterministic)
}
func (m *ChronicConditionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChronicConditionData.Merge(m, src)
}
func (m *ChronicConditionData) XXX_Size() int {
	return xxx_messageInfo_ChronicConditionData.Size(m)
}
func (m *ChronicConditionData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChronicConditionData.DiscardUnknown(m)
}

var xxx_messageInfo_ChronicConditionData proto.InternalMessageInfo

func (m *ChronicConditionData) GetHypertensive() bool {
	if m != nil {
		return m.Hypertensive
	}
	return false
}

func (m *ChronicConditionData) GetDiabetic() bool {
	if m != nil {
		return m.Diabetic
	}
	return false
}

type ProfileData struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Height               float32  `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	Weight               float32  `protobuf:"fixed32,7,opt,name=weight,proto3" json:"weight,omitempty"`
	SmokingStatus        bool     `protobuf:"varint,8,opt,name=smokingStatus,proto3" json:"smokingStatus,omitempty"`
	AlcoholStatus        bool     `protobuf:"varint,9,opt,name=alcoholStatus,proto3" json:"alcoholStatus,omitempty"`
	EmailVerified        bool     `protobuf:"varint,10,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	PhoneVerified        bool     `protobuf:"varint,11,opt,name=phoneVerified,proto3" json:"phoneVerified,omitempty"`
	Password             string   `protobuf:"bytes,12,opt,name=password,proto3" json:"password,omitempty"`
	Birthdate            string   `protobuf:"bytes,13,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	AvatarURL            string   `protobuf:"bytes,14,opt,name=avatarURL,proto3" json:"avatarURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileData) Reset()         { *m = ProfileData{} }
func (m *ProfileData) String() string { return proto.CompactTextString(m) }
func (*ProfileData) ProtoMessage()    {}
func (*ProfileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{2}
}

func (m *ProfileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileData.Unmarshal(m, b)
}
func (m *ProfileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileData.Marshal(b, m, deterministic)
}
func (m *ProfileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileData.Merge(m, src)
}
func (m *ProfileData) XXX_Size() int {
	return xxx_messageInfo_ProfileData.Size(m)
}
func (m *ProfileData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileData.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileData proto.InternalMessageInfo

func (m *ProfileData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ProfileData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileData) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *ProfileData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ProfileData) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProfileData) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ProfileData) GetSmokingStatus() bool {
	if m != nil {
		return m.SmokingStatus
	}
	return false
}

func (m *ProfileData) GetAlcoholStatus() bool {
	if m != nil {
		return m.AlcoholStatus
	}
	return false
}

func (m *ProfileData) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *ProfileData) GetPhoneVerified() bool {
	if m != nil {
		return m.PhoneVerified
	}
	return false
}

func (m *ProfileData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ProfileData) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *ProfileData) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

type LoginRequest struct {
	AuthData             *AuthData `protobuf:"bytes,1,opt,name=authData,proto3" json:"authData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAuthData() *AuthData {
	if m != nil {
		return m.AuthData
	}
	return nil
}

type LoginResponse struct {
	LoginToken           string   `protobuf:"bytes,1,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
	PersonID             string   `protobuf:"bytes,2,opt,name=personID,proto3" json:"personID,omitempty"`
	SessionID            string   `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	IsVerified           bool     `protobuf:"varint,4,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

func (m *LoginResponse) GetPersonID() string {
	if m != nil {
		return m.PersonID
	}
	return ""
}

func (m *LoginResponse) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *LoginResponse) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

type ConsentResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsentResponse) Reset()         { *m = ConsentResponse{} }
func (m *ConsentResponse) String() string { return proto.CompactTextString(m) }
func (*ConsentResponse) ProtoMessage()    {}
func (*ConsentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{5}
}

func (m *ConsentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsentResponse.Unmarshal(m, b)
}
func (m *ConsentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsentResponse.Marshal(b, m, deterministic)
}
func (m *ConsentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsentResponse.Merge(m, src)
}
func (m *ConsentResponse) XXX_Size() int {
	return xxx_messageInfo_ConsentResponse.Size(m)
}
func (m *ConsentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsentResponse proto.InternalMessageInfo

func (m *ConsentResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RegisterRequest struct {
	AuthData             *AuthData    `protobuf:"bytes,1,opt,name=authData,proto3" json:"authData,omitempty"`
	ProfileData          *ProfileData `protobuf:"bytes,2,opt,name=profileData,proto3" json:"profileData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{6}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAuthData() *AuthData {
	if m != nil {
		return m.AuthData
	}
	return nil
}

func (m *RegisterRequest) GetProfileData() *ProfileData {
	if m != nil {
		return m.ProfileData
	}
	return nil
}

type RegisterResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{7}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResendEmailVerificationResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendEmailVerificationResponse) Reset()         { *m = ResendEmailVerificationResponse{} }
func (m *ResendEmailVerificationResponse) String() string { return proto.CompactTextString(m) }
func (*ResendEmailVerificationResponse) ProtoMessage()    {}
func (*ResendEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{8}
}

func (m *ResendEmailVerificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendEmailVerificationResponse.Unmarshal(m, b)
}
func (m *ResendEmailVerificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendEmailVerificationResponse.Marshal(b, m, deterministic)
}
func (m *ResendEmailVerificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendEmailVerificationResponse.Merge(m, src)
}
func (m *ResendEmailVerificationResponse) XXX_Size() int {
	return xxx_messageInfo_ResendEmailVerificationResponse.Size(m)
}
func (m *ResendEmailVerificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendEmailVerificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResendEmailVerificationResponse proto.InternalMessageInfo

func (m *ResendEmailVerificationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VerifyRegisterRequest struct {
	RegisterToken        string   `protobuf:"bytes,1,opt,name=registerToken,proto3" json:"registerToken,omitempty"`
	DiagnosticSessionID  string   `protobuf:"bytes,2,opt,name=diagnosticSessionID,proto3" json:"diagnosticSessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRegisterRequest) Reset()         { *m = VerifyRegisterRequest{} }
func (m *VerifyRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRegisterRequest) ProtoMessage()    {}
func (*VerifyRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{9}
}

func (m *VerifyRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRegisterRequest.Unmarshal(m, b)
}
func (m *VerifyRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRegisterRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRegisterRequest.Merge(m, src)
}
func (m *VerifyRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRegisterRequest.Size(m)
}
func (m *VerifyRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRegisterRequest proto.InternalMessageInfo

func (m *VerifyRegisterRequest) GetRegisterToken() string {
	if m != nil {
		return m.RegisterToken
	}
	return ""
}

func (m *VerifyRegisterRequest) GetDiagnosticSessionID() string {
	if m != nil {
		return m.DiagnosticSessionID
	}
	return ""
}

type VerifyRegisterResponse struct {
	LoginToken           string   `protobuf:"bytes,1,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
	SessionID            string   `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRegisterResponse) Reset()         { *m = VerifyRegisterResponse{} }
func (m *VerifyRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyRegisterResponse) ProtoMessage()    {}
func (*VerifyRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{10}
}

func (m *VerifyRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRegisterResponse.Unmarshal(m, b)
}
func (m *VerifyRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRegisterResponse.Marshal(b, m, deterministic)
}
func (m *VerifyRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRegisterResponse.Merge(m, src)
}
func (m *VerifyRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyRegisterResponse.Size(m)
}
func (m *VerifyRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRegisterResponse proto.InternalMessageInfo

func (m *VerifyRegisterResponse) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

func (m *VerifyRegisterResponse) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type ForgetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	DiagnosticSessionID  string   `protobuf:"bytes,2,opt,name=diagnosticSessionID,proto3" json:"diagnosticSessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordRequest) Reset()         { *m = ForgetPasswordRequest{} }
func (m *ForgetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordRequest) ProtoMessage()    {}
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{11}
}

func (m *ForgetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordRequest.Merge(m, src)
}
func (m *ForgetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordRequest.Size(m)
}
func (m *ForgetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordRequest proto.InternalMessageInfo

func (m *ForgetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ForgetPasswordRequest) GetDiagnosticSessionID() string {
	if m != nil {
		return m.DiagnosticSessionID
	}
	return ""
}

type ForgetPasswordResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordResponse) Reset()         { *m = ForgetPasswordResponse{} }
func (m *ForgetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordResponse) ProtoMessage()    {}
func (*ForgetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{12}
}

func (m *ForgetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordResponse.Unmarshal(m, b)
}
func (m *ForgetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordResponse.Merge(m, src)
}
func (m *ForgetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordResponse.Size(m)
}
func (m *ForgetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordResponse proto.InternalMessageInfo

func (m *ForgetPasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ForgetPasswordVerifRequest struct {
	ForgetPwdToken       string   `protobuf:"bytes,1,opt,name=forgetPwdToken,proto3" json:"forgetPwdToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordVerifRequest) Reset()         { *m = ForgetPasswordVerifRequest{} }
func (m *ForgetPasswordVerifRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordVerifRequest) ProtoMessage()    {}
func (*ForgetPasswordVerifRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{13}
}

func (m *ForgetPasswordVerifRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordVerifRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordVerifRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordVerifRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordVerifRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordVerifRequest.Merge(m, src)
}
func (m *ForgetPasswordVerifRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordVerifRequest.Size(m)
}
func (m *ForgetPasswordVerifRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordVerifRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordVerifRequest proto.InternalMessageInfo

func (m *ForgetPasswordVerifRequest) GetForgetPwdToken() string {
	if m != nil {
		return m.ForgetPwdToken
	}
	return ""
}

type ForgetPasswordVerifResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordVerifResponse) Reset()         { *m = ForgetPasswordVerifResponse{} }
func (m *ForgetPasswordVerifResponse) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordVerifResponse) ProtoMessage()    {}
func (*ForgetPasswordVerifResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{14}
}

func (m *ForgetPasswordVerifResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordVerifResponse.Unmarshal(m, b)
}
func (m *ForgetPasswordVerifResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordVerifResponse.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordVerifResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordVerifResponse.Merge(m, src)
}
func (m *ForgetPasswordVerifResponse) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordVerifResponse.Size(m)
}
func (m *ForgetPasswordVerifResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordVerifResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordVerifResponse proto.InternalMessageInfo

func (m *ForgetPasswordVerifResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdatePasswordRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,2,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty"`
	DiagnosticSessionID  string   `protobuf:"bytes,3,opt,name=diagnosticSessionID,proto3" json:"diagnosticSessionID,omitempty"`
	ForgetPasswordToken  string   `protobuf:"bytes,4,opt,name=forgetPasswordToken,proto3" json:"forgetPasswordToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{15}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdatePasswordRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *UpdatePasswordRequest) GetDiagnosticSessionID() string {
	if m != nil {
		return m.DiagnosticSessionID
	}
	return ""
}

func (m *UpdatePasswordRequest) GetForgetPasswordToken() string {
	if m != nil {
		return m.ForgetPasswordToken
	}
	return ""
}

type UpdatePasswordResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	LoginToken           string   `protobuf:"bytes,2,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
	SessionID            string   `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{16}
}

func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(m, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

func (m *UpdatePasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdatePasswordResponse) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

func (m *UpdatePasswordResponse) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type UserInfoResponse struct {
	ProfileData          *ProfileData `protobuf:"bytes,1,opt,name=profileData,proto3" json:"profileData,omitempty"`
	IsVerified           bool         `protobuf:"varint,2,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{17}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetProfileData() *ProfileData {
	if m != nil {
		return m.ProfileData
	}
	return nil
}

func (m *UserInfoResponse) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

type ChangePasswordRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,2,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty"`
	OldPassword          string   `protobuf:"bytes,3,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{18}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangePasswordRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{19}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LogoutResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{20}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUserInfoRequest struct {
	ProfileData          *ProfileData `protobuf:"bytes,1,opt,name=profileData,proto3" json:"profileData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateUserInfoRequest) Reset()         { *m = UpdateUserInfoRequest{} }
func (m *UpdateUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoRequest) ProtoMessage()    {}
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{21}
}

func (m *UpdateUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoRequest.Unmarshal(m, b)
}
func (m *UpdateUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoRequest.Merge(m, src)
}
func (m *UpdateUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoRequest.Size(m)
}
func (m *UpdateUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoRequest proto.InternalMessageInfo

func (m *UpdateUserInfoRequest) GetProfileData() *ProfileData {
	if m != nil {
		return m.ProfileData
	}
	return nil
}

type UpdateUserInfoResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserInfoResponse) Reset()         { *m = UpdateUserInfoResponse{} }
func (m *UpdateUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoResponse) ProtoMessage()    {}
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{22}
}

func (m *UpdateUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoResponse.Unmarshal(m, b)
}
func (m *UpdateUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoResponse.Merge(m, src)
}
func (m *UpdateUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoResponse.Size(m)
}
func (m *UpdateUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoResponse proto.InternalMessageInfo

func (m *UpdateUserInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetSignedURLResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSignedURLResponse) Reset()         { *m = GetSignedURLResponse{} }
func (m *GetSignedURLResponse) String() string { return proto.CompactTextString(m) }
func (*GetSignedURLResponse) ProtoMessage()    {}
func (*GetSignedURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{23}
}

func (m *GetSignedURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSignedURLResponse.Unmarshal(m, b)
}
func (m *GetSignedURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSignedURLResponse.Marshal(b, m, deterministic)
}
func (m *GetSignedURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSignedURLResponse.Merge(m, src)
}
func (m *GetSignedURLResponse) XXX_Size() int {
	return xxx_messageInfo_GetSignedURLResponse.Size(m)
}
func (m *GetSignedURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSignedURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSignedURLResponse proto.InternalMessageInfo

func (m *GetSignedURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetSignedURLResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type OauthGoogleURL struct {
	AuthURL              string   `protobuf:"bytes,1,opt,name=authURL,proto3" json:"authURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OauthGoogleURL) Reset()         { *m = OauthGoogleURL{} }
func (m *OauthGoogleURL) String() string { return proto.CompactTextString(m) }
func (*OauthGoogleURL) ProtoMessage()    {}
func (*OauthGoogleURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{24}
}

func (m *OauthGoogleURL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OauthGoogleURL.Unmarshal(m, b)
}
func (m *OauthGoogleURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OauthGoogleURL.Marshal(b, m, deterministic)
}
func (m *OauthGoogleURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OauthGoogleURL.Merge(m, src)
}
func (m *OauthGoogleURL) XXX_Size() int {
	return xxx_messageInfo_OauthGoogleURL.Size(m)
}
func (m *OauthGoogleURL) XXX_DiscardUnknown() {
	xxx_messageInfo_OauthGoogleURL.DiscardUnknown(m)
}

var xxx_messageInfo_OauthGoogleURL proto.InternalMessageInfo

func (m *OauthGoogleURL) GetAuthURL() string {
	if m != nil {
		return m.AuthURL
	}
	return ""
}

type CallbackGoogleRequest struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackGoogleRequest) Reset()         { *m = CallbackGoogleRequest{} }
func (m *CallbackGoogleRequest) String() string { return proto.CompactTextString(m) }
func (*CallbackGoogleRequest) ProtoMessage()    {}
func (*CallbackGoogleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{25}
}

func (m *CallbackGoogleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackGoogleRequest.Unmarshal(m, b)
}
func (m *CallbackGoogleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackGoogleRequest.Marshal(b, m, deterministic)
}
func (m *CallbackGoogleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackGoogleRequest.Merge(m, src)
}
func (m *CallbackGoogleRequest) XXX_Size() int {
	return xxx_messageInfo_CallbackGoogleRequest.Size(m)
}
func (m *CallbackGoogleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackGoogleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackGoogleRequest proto.InternalMessageInfo

func (m *CallbackGoogleRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CallbackGoogleRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AssessmentHistory struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ChiefComplaint       string               `protobuf:"bytes,2,opt,name=chiefComplaint,proto3" json:"chiefComplaint,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string               `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	Gender               string               `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AssessmentHistory) Reset()         { *m = AssessmentHistory{} }
func (m *AssessmentHistory) String() string { return proto.CompactTextString(m) }
func (*AssessmentHistory) ProtoMessage()    {}
func (*AssessmentHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{26}
}

func (m *AssessmentHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssessmentHistory.Unmarshal(m, b)
}
func (m *AssessmentHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssessmentHistory.Marshal(b, m, deterministic)
}
func (m *AssessmentHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssessmentHistory.Merge(m, src)
}
func (m *AssessmentHistory) XXX_Size() int {
	return xxx_messageInfo_AssessmentHistory.Size(m)
}
func (m *AssessmentHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_AssessmentHistory.DiscardUnknown(m)
}

var xxx_messageInfo_AssessmentHistory proto.InternalMessageInfo

func (m *AssessmentHistory) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *AssessmentHistory) GetChiefComplaint() string {
	if m != nil {
		return m.ChiefComplaint
	}
	return ""
}

func (m *AssessmentHistory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AssessmentHistory) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *AssessmentHistory) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type Preconditions struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Height               float32  `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	Weight               float32  `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preconditions) Reset()         { *m = Preconditions{} }
func (m *Preconditions) String() string { return proto.CompactTextString(m) }
func (*Preconditions) ProtoMessage()    {}
func (*Preconditions) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{27}
}

func (m *Preconditions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preconditions.Unmarshal(m, b)
}
func (m *Preconditions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preconditions.Marshal(b, m, deterministic)
}
func (m *Preconditions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preconditions.Merge(m, src)
}
func (m *Preconditions) XXX_Size() int {
	return xxx_messageInfo_Preconditions.Size(m)
}
func (m *Preconditions) XXX_DiscardUnknown() {
	xxx_messageInfo_Preconditions.DiscardUnknown(m)
}

var xxx_messageInfo_Preconditions proto.InternalMessageInfo

func (m *Preconditions) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Preconditions) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Preconditions) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Preconditions) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Preconditions) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type GetAssessmentHistoryResponse struct {
	AssessmentHistory    []*AssessmentHistory `protobuf:"bytes,1,rep,name=assessmentHistory,proto3" json:"assessmentHistory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAssessmentHistoryResponse) Reset()         { *m = GetAssessmentHistoryResponse{} }
func (m *GetAssessmentHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetAssessmentHistoryResponse) ProtoMessage()    {}
func (*GetAssessmentHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453e8749a117a63a, []int{28}
}

func (m *GetAssessmentHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssessmentHistoryResponse.Unmarshal(m, b)
}
func (m *GetAssessmentHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssessmentHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetAssessmentHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssessmentHistoryResponse.Merge(m, src)
}
func (m *GetAssessmentHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetAssessmentHistoryResponse.Size(m)
}
func (m *GetAssessmentHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssessmentHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssessmentHistoryResponse proto.InternalMessageInfo

func (m *GetAssessmentHistoryResponse) GetAssessmentHistory() []*AssessmentHistory {
	if m != nil {
		return m.AssessmentHistory
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthData)(nil), "prixa.user.v1.AuthData")
	proto.RegisterType((*ChronicConditionData)(nil), "prixa.user.v1.ChronicConditionData")
	proto.RegisterType((*ProfileData)(nil), "prixa.user.v1.ProfileData")
	proto.RegisterType((*LoginRequest)(nil), "prixa.user.v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "prixa.user.v1.LoginResponse")
	proto.RegisterType((*ConsentResponse)(nil), "prixa.user.v1.ConsentResponse")
	proto.RegisterType((*RegisterRequest)(nil), "prixa.user.v1.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "prixa.user.v1.RegisterResponse")
	proto.RegisterType((*ResendEmailVerificationResponse)(nil), "prixa.user.v1.ResendEmailVerificationResponse")
	proto.RegisterType((*VerifyRegisterRequest)(nil), "prixa.user.v1.VerifyRegisterRequest")
	proto.RegisterType((*VerifyRegisterResponse)(nil), "prixa.user.v1.VerifyRegisterResponse")
	proto.RegisterType((*ForgetPasswordRequest)(nil), "prixa.user.v1.ForgetPasswordRequest")
	proto.RegisterType((*ForgetPasswordResponse)(nil), "prixa.user.v1.ForgetPasswordResponse")
	proto.RegisterType((*ForgetPasswordVerifRequest)(nil), "prixa.user.v1.ForgetPasswordVerifRequest")
	proto.RegisterType((*ForgetPasswordVerifResponse)(nil), "prixa.user.v1.ForgetPasswordVerifResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "prixa.user.v1.UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "prixa.user.v1.UpdatePasswordResponse")
	proto.RegisterType((*UserInfoResponse)(nil), "prixa.user.v1.UserInfoResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "prixa.user.v1.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "prixa.user.v1.ChangePasswordResponse")
	proto.RegisterType((*LogoutResponse)(nil), "prixa.user.v1.LogoutResponse")
	proto.RegisterType((*UpdateUserInfoRequest)(nil), "prixa.user.v1.UpdateUserInfoRequest")
	proto.RegisterType((*UpdateUserInfoResponse)(nil), "prixa.user.v1.UpdateUserInfoResponse")
	proto.RegisterType((*GetSignedURLResponse)(nil), "prixa.user.v1.GetSignedURLResponse")
	proto.RegisterType((*OauthGoogleURL)(nil), "prixa.user.v1.OauthGoogleURL")
	proto.RegisterType((*CallbackGoogleRequest)(nil), "prixa.user.v1.CallbackGoogleRequest")
	proto.RegisterType((*AssessmentHistory)(nil), "prixa.user.v1.AssessmentHistory")
	proto.RegisterType((*Preconditions)(nil), "prixa.user.v1.Preconditions")
	proto.RegisterType((*GetAssessmentHistoryResponse)(nil), "prixa.user.v1.GetAssessmentHistoryResponse")
}

func init() {
	proto.RegisterFile("proto/user/v1/User.proto", fileDescriptor_453e8749a117a63a)
}

var fileDescriptor_453e8749a117a63a = []byte{
	// 1918 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xdd, 0x6e, 0x1b, 0xc7,
	0x15, 0xce, 0x52, 0x3f, 0xa6, 0x8e, 0x24, 0x5a, 0x1e, 0x4b, 0x32, 0x4b, 0xc9, 0x16, 0x33, 0x51,
	0x6a, 0x57, 0x16, 0xb9, 0x92, 0x12, 0x34, 0xb0, 0x1b, 0x20, 0xa1, 0x69, 0xc5, 0x15, 0x22, 0xa4,
	0xc2, 0xca, 0x0a, 0x82, 0x14, 0x6e, 0x30, 0x5c, 0x0e, 0x97, 0x53, 0x93, 0x3b, 0xdb, 0xdd, 0xa1,
	0x14, 0xc5, 0x48, 0x51, 0x14, 0x6d, 0x6f, 0x8b, 0xba, 0x40, 0x7b, 0xdb, 0x14, 0x68, 0x81, 0x5e,
	0xf4, 0xb6, 0x2f, 0xd1, 0x8b, 0xa2, 0xe8, 0x03, 0x04, 0x08, 0x72, 0xd3, 0xb7, 0x28, 0x66, 0x66,
	0x77, 0xc5, 0xfd, 0xb3, 0x68, 0x24, 0xe8, 0x95, 0x76, 0xce, 0x39, 0x73, 0x7e, 0xbe, 0x39, 0x73,
	0xe6, 0xa3, 0xa0, 0xea, 0xf9, 0x5c, 0x70, 0x73, 0x14, 0x50, 0xdf, 0x3c, 0xdd, 0x35, 0x4f, 0x02,
	0xea, 0x37, 0x95, 0x08, 0x2d, 0x7a, 0x3e, 0xfb, 0x94, 0x34, 0xa5, 0xa6, 0x79, 0xba, 0x5b, 0x5b,
	0x73, 0x38, 0x77, 0x06, 0xd4, 0x54, 0xca, 0xce, 0xa8, 0x67, 0xd2, 0xa1, 0x27, 0xce, 0xb5, 0x6d,
	0x6d, 0x3d, 0x54, 0x12, 0x8f, 0x99, 0xc4, 0x75, 0xb9, 0x20, 0x82, 0x71, 0x37, 0x08, 0xb5, 0x1b,
	0xe9, 0xad, 0x82, 0x0d, 0x69, 0x20, 0xc8, 0xd0, 0x0b, 0x0d, 0xb6, 0xd5, 0x1f, 0xbb, 0xe1, 0x50,
	0xb7, 0x11, 0x9c, 0x11, 0xc7, 0xa1, 0xbe, 0xc9, 0x3d, 0xe5, 0x22, 0xc7, 0xdd, 0xf7, 0x1d, 0x26,
	0xfa, 0xa3, 0x4e, 0xd3, 0xe6, 0x43, 0x73, 0x78, 0xc6, 0xc4, 0x53, 0x7e, 0x66, 0x3a, 0xbc, 0xa1,
	0x94, 0x8d, 0x53, 0x32, 0x60, 0x5d, 0x22, 0xb8, 0x1f, 0x98, 0xf1, 0xa7, 0xde, 0x87, 0xbf, 0x36,
	0xa0, 0xdc, 0x1a, 0x89, 0xfe, 0x43, 0x22, 0x08, 0x7a, 0x0f, 0x66, 0xe8, 0x90, 0xb0, 0x41, 0xd5,
	0xa8, 0x1b, 0x77, 0xe6, 0x1e, 0xec, 0x7c, 0xf5, 0xe5, 0xc6, 0x36, 0x6c, 0xfd, 0xe4, 0xc7, 0xa4,
	0xf1, 0x59, 0xab, 0xf1, 0xf1, 0x4e, 0xe3, 0x5e, 0xf3, 0x93, 0xd7, 0xef, 0x36, 0x9e, 0xdc, 0x7d,
	0x57, 0x4a, 0xe4, 0xb2, 0xf1, 0xe4, 0x6e, 0x53, 0x7e, 0x3f, 0x79, 0xb6, 0xb7, 0xfd, 0xe6, 0xe7,
	0x9b, 0x96, 0xde, 0x8e, 0x30, 0x94, 0x3d, 0x12, 0x04, 0x67, 0xdc, 0xef, 0x56, 0x4b, 0xca, 0xd5,
	0xec, 0x57, 0x5f, 0x6e, 0x94, 0x3e, 0x32, 0xac, 0x58, 0x8e, 0xee, 0xc3, 0x72, 0xf4, 0xdd, 0xe6,
	0x6e, 0x8f, 0xf9, 0x43, 0x55, 0x4f, 0x75, 0x2a, 0x61, 0x9f, 0x6b, 0x83, 0x76, 0xe0, 0x7a, 0x97,
	0x11, 0xc7, 0xe5, 0x81, 0x60, 0xf6, 0x31, 0x0d, 0x02, 0xc6, 0xdd, 0x83, 0x87, 0xd5, 0x69, 0xb9,
	0xd5, 0xca, 0x53, 0xe1, 0x0f, 0x61, 0xb9, 0xdd, 0xf7, 0xb9, 0xcb, 0xec, 0x36, 0x77, 0xbb, 0x4c,
	0x7a, 0x51, 0x15, 0x63, 0x58, 0xe8, 0x9f, 0x7b, 0xd4, 0x17, 0xd4, 0x0d, 0xd8, 0x29, 0x55, 0x85,
	0x97, 0xad, 0x84, 0x0c, 0xd5, 0xa0, 0xdc, 0x65, 0xa4, 0x43, 0x05, 0xb3, 0x55, 0x35, 0x65, 0x2b,
	0x5e, 0xe3, 0xff, 0x4e, 0xc1, 0xfc, 0x91, 0xcf, 0x7b, 0x6c, 0x40, 0xbf, 0x55, 0x04, 0x97, 0x61,
	0xc6, 0xeb, 0x73, 0x97, 0x6a, 0xf8, 0x2c, 0xbd, 0x40, 0x35, 0x98, 0x76, 0xc9, 0x90, 0xa6, 0x30,
	0x52, 0x32, 0x74, 0x0b, 0x66, 0x1d, 0xea, 0x76, 0xa9, 0xaf, 0x61, 0x88, 0xb5, 0xa1, 0x14, 0x55,
	0xe1, 0x0a, 0xe9, 0x76, 0x7d, 0x1a, 0x04, 0xd5, 0x19, 0xe5, 0x33, 0x5a, 0xa2, 0x55, 0x98, 0xed,
	0x53, 0xe6, 0xf4, 0x45, 0x75, 0xb6, 0x6e, 0xdc, 0x29, 0x59, 0xe1, 0x4a, 0xca, 0xcf, 0xb4, 0xfc,
	0x8a, 0x96, 0xeb, 0x15, 0xda, 0x84, 0xc5, 0x60, 0xc8, 0x9f, 0x32, 0xd7, 0x39, 0x16, 0x44, 0x8c,
	0x82, 0x6a, 0x59, 0x81, 0x92, 0x14, 0x4a, 0x2b, 0x32, 0xb0, 0x79, 0x9f, 0x0f, 0x42, 0xab, 0x39,
	0x6d, 0x95, 0x10, 0x4a, 0x2b, 0x55, 0xf0, 0x87, 0xd4, 0x67, 0x3d, 0x46, 0xbb, 0x55, 0xd0, 0x56,
	0x09, 0xa1, 0xb4, 0x52, 0x00, 0xc4, 0x56, 0xf3, 0xda, 0x2a, 0x21, 0x4c, 0x74, 0xdd, 0x42, 0x41,
	0xd7, 0xad, 0xc3, 0x5c, 0x87, 0xf9, 0xa2, 0xdf, 0x25, 0x82, 0x56, 0x17, 0x15, 0x0e, 0x17, 0x02,
	0xa9, 0x25, 0xa7, 0x44, 0x10, 0xff, 0xc4, 0x3a, 0xac, 0x56, 0xb4, 0x36, 0x16, 0xe0, 0x36, 0x2c,
	0x1c, 0x72, 0x87, 0xb9, 0x16, 0xfd, 0xd9, 0x88, 0x06, 0x02, 0xbd, 0x01, 0x65, 0x12, 0xde, 0x1c,
	0x75, 0xdc, 0xf3, 0x7b, 0x37, 0x9a, 0x89, 0xf1, 0xd0, 0x8c, 0x2e, 0x96, 0x15, 0x1b, 0xe2, 0x2f,
	0x0c, 0x58, 0x0c, 0xbd, 0x04, 0x1e, 0x77, 0x03, 0x8a, 0xbe, 0x0b, 0x30, 0x90, 0x82, 0xc7, 0xfc,
	0x29, 0x75, 0xc3, 0xbe, 0x89, 0x12, 0x1f, 0xd3, 0xa8, 0xf2, 0xa8, 0x1f, 0xa8, 0x4e, 0x4f, 0x5f,
	0xaa, 0x50, 0x8e, 0x36, 0x61, 0x2e, 0x88, 0xaf, 0x43, 0xb2, 0x4b, 0x2e, 0x14, 0xe8, 0x16, 0x00,
	0x0b, 0x62, 0x2c, 0xa7, 0x15, 0x96, 0x63, 0x12, 0xdc, 0x80, 0xab, 0x6d, 0x99, 0x9a, 0x2b, 0xe2,
	0x24, 0x6b, 0x30, 0xdd, 0x8d, 0xea, 0x1c, 0xeb, 0x3c, 0x29, 0xc3, 0xbf, 0x32, 0xe0, 0xaa, 0x45,
	0x1d, 0x16, 0x08, 0xea, 0x7f, 0x13, 0x6c, 0xd0, 0xdb, 0x30, 0xef, 0x5d, 0xdc, 0x25, 0x55, 0xe4,
	0xfc, 0x5e, 0x2d, 0xb5, 0x6f, 0xec, 0xb6, 0x59, 0xe3, 0xe6, 0x78, 0x1b, 0x96, 0x2e, 0xb2, 0x08,
	0xd3, 0xae, 0xc2, 0x95, 0x21, 0x0d, 0x02, 0xe2, 0xe8, 0x9b, 0x3d, 0x67, 0x45, 0x4b, 0xfc, 0x03,
	0xd8, 0xb0, 0x68, 0x40, 0xdd, 0xee, 0xfe, 0x45, 0xa7, 0xd9, 0x6a, 0xba, 0x4c, 0xb0, 0xf9, 0x0c,
	0x56, 0xd4, 0x8e, 0xf3, 0x74, 0xd9, 0xdb, 0xb0, 0xe8, 0x87, 0xa2, 0xbc, 0xe3, 0x4c, 0x2a, 0x8b,
	0xc6, 0x58, 0xa9, 0x78, 0x8c, 0xf5, 0x60, 0x35, 0x1d, 0xf8, 0x25, 0xbb, 0x28, 0xd1, 0x21, 0xa5,
	0x82, 0x0e, 0xc1, 0xbf, 0x33, 0x60, 0xe5, 0x3d, 0xee, 0x3b, 0x54, 0x1c, 0x85, 0x37, 0x27, 0xaa,
	0xf0, 0xdb, 0x1a, 0x70, 0x2f, 0x5f, 0xfb, 0x1e, 0xac, 0xa6, 0x53, 0xba, 0xf4, 0xa0, 0x0e, 0xa1,
	0x96, 0xdc, 0xa3, 0xd0, 0x8b, 0x6a, 0x69, 0x42, 0xa5, 0xa7, 0xb5, 0x67, 0xdd, 0x3c, 0xdc, 0x52,
	0x5a, 0xfc, 0x16, 0xac, 0xe5, 0x7a, 0xbb, 0x34, 0x8d, 0x7f, 0x1b, 0xb0, 0x72, 0xe2, 0xc9, 0x11,
	0x93, 0x86, 0x73, 0x7c, 0x66, 0x19, 0x05, 0x33, 0x6b, 0x07, 0xae, 0xda, 0xfa, 0xf5, 0x3b, 0xca,
	0x7f, 0x54, 0xd3, 0xea, 0x22, 0x70, 0xa7, 0x0a, 0xc1, 0x95, 0x3b, 0x7a, 0x89, 0xd2, 0x34, 0x1e,
	0xe1, 0x8b, 0x9a, 0xa3, 0xc2, 0xbf, 0x30, 0x60, 0x35, 0x5d, 0xd3, 0x65, 0x40, 0xa4, 0xba, 0xb4,
	0x34, 0x59, 0x97, 0x16, 0xcd, 0x31, 0xec, 0xc1, 0x92, 0xa4, 0x66, 0x07, 0x6e, 0x8f, 0xc7, 0xb1,
	0x53, 0x33, 0xc4, 0x78, 0xa9, 0x19, 0x92, 0x9a, 0x8c, 0xa5, 0xcc, 0x64, 0xfc, 0xa3, 0x01, 0x2b,
	0xed, 0x3e, 0x71, 0x9d, 0xff, 0xd3, 0x41, 0xde, 0x81, 0x79, 0x3e, 0xe8, 0xc6, 0xd6, 0x49, 0x24,
	0xc6, 0x55, 0xf2, 0x76, 0xa4, 0x13, 0xbb, 0xb4, 0x2d, 0xb7, 0xa0, 0x72, 0xc8, 0x1d, 0x3e, 0x12,
	0x13, 0xd8, 0x9e, 0x44, 0x1d, 0x7c, 0x81, 0xb8, 0x2e, 0xfc, 0x1b, 0x01, 0x2e, 0xd3, 0x4e, 0xbb,
	0xbd, 0x34, 0x95, 0xb7, 0x61, 0xf9, 0x11, 0x15, 0xc7, 0xcc, 0x71, 0x69, 0xf7, 0xc4, 0x3a, 0x8c,
	0x77, 0x2c, 0xc1, 0xd4, 0xc8, 0x0f, 0x07, 0x93, 0x25, 0x3f, 0x11, 0x0a, 0xf9, 0x92, 0x9e, 0x2a,
	0xea, 0x5b, 0x16, 0xfd, 0x23, 0xf9, 0xe2, 0x3c, 0x52, 0xf4, 0xfb, 0xc4, 0x3a, 0x54, 0xcc, 0x68,
	0x24, 0xfa, 0xf2, 0xcd, 0x0f, 0x23, 0x85, 0x4b, 0xdc, 0x82, 0x95, 0x36, 0x19, 0x0c, 0x3a, 0xc4,
	0x7e, 0xaa, 0xcd, 0xa3, 0xa2, 0x97, 0x61, 0x26, 0x10, 0x92, 0x42, 0xe8, 0x0d, 0x7a, 0x21, 0xc3,
	0xd9, 0xbc, 0x1b, 0x87, 0x93, 0xdf, 0xf8, 0x6f, 0x06, 0x5c, 0x6b, 0x05, 0xb2, 0x67, 0x87, 0xd4,
	0x15, 0x3f, 0x64, 0x81, 0xe0, 0xfe, 0x39, 0x6a, 0xaa, 0xe7, 0x94, 0xc6, 0x68, 0xe9, 0xdf, 0x02,
	0xcd, 0xe8, 0xb7, 0x40, 0xf3, 0x71, 0xf4, 0x5b, 0x40, 0x3d, 0xb1, 0xf2, 0xde, 0x54, 0xec, 0x3e,
	0xa3, 0xbd, 0x36, 0x1f, 0x7a, 0x03, 0xc2, 0x5c, 0x11, 0xc6, 0x48, 0x49, 0xe3, 0x82, 0xa7, 0x2e,
	0x0a, 0x96, 0xb0, 0x48, 0x10, 0xf5, 0x55, 0x96, 0x9f, 0x92, 0xd8, 0x85, 0x54, 0x51, 0x33, 0xc1,
	0x70, 0x85, 0x47, 0xb0, 0x78, 0xe4, 0x53, 0x3b, 0x22, 0xc8, 0x01, 0xaa, 0x40, 0x89, 0x85, 0xed,
	0x6c, 0x95, 0x58, 0x57, 0xba, 0x17, 0xe7, 0x5e, 0x5c, 0xa0, 0xfc, 0x8e, 0xdc, 0xcb, 0x88, 0x33,
	0xb1, 0xfb, 0x90, 0x4f, 0x4e, 0x17, 0xf0, 0xc9, 0x99, 0x71, 0x3e, 0x89, 0x5d, 0x58, 0x7f, 0x44,
	0x45, 0x06, 0xa4, 0xf8, 0x5c, 0x3f, 0x80, 0x6b, 0x24, 0xad, 0xac, 0x1a, 0xf5, 0xa9, 0x3b, 0xf3,
	0x7b, 0xf5, 0x34, 0xa9, 0xc8, 0x38, 0xc9, 0x6e, 0xdd, 0xfb, 0xe2, 0x1a, 0xcc, 0xcb, 0x76, 0x3b,
	0xa6, 0xfe, 0x29, 0xb3, 0x29, 0x22, 0x30, 0xa3, 0x18, 0x19, 0x5a, 0x4b, 0x79, 0x1b, 0x67, 0x7b,
	0xb5, 0xf5, 0x7c, 0xa5, 0xce, 0x11, 0xdf, 0xfc, 0xe5, 0x7f, 0xbe, 0xfe, 0x7d, 0xe9, 0x06, 0x46,
	0xea, 0xd7, 0xde, 0xe9, 0xae, 0xfe, 0xed, 0xa8, 0x26, 0xda, 0x7d, 0x63, 0x0b, 0x7d, 0x02, 0x57,
	0x42, 0x46, 0x85, 0x56, 0x33, 0x87, 0xbd, 0x2f, 0x7f, 0x33, 0xd6, 0x6e, 0xa5, 0xfc, 0xa7, 0x18,
	0x18, 0x5e, 0x57, 0x11, 0x56, 0xd1, 0x72, 0x22, 0x82, 0x1d, 0x7a, 0x1d, 0x42, 0x39, 0xa2, 0x04,
	0x28, 0xed, 0x29, 0x45, 0x52, 0x6a, 0x1b, 0x85, 0xfa, 0x30, 0x54, 0x5d, 0x85, 0xaa, 0xe1, 0x95,
	0x44, 0xa8, 0x88, 0xbb, 0xc8, 0x7a, 0x1c, 0x98, 0x1f, 0xbb, 0x44, 0x85, 0x35, 0xdd, 0x4c, 0x45,
	0x4a, 0x5e, 0x3c, 0xfc, 0xaa, 0x8a, 0xb3, 0x86, 0xbe, 0x93, 0x88, 0xc3, 0xa5, 0x91, 0xa9, 0x1d,
	0xa2, 0x5f, 0x1b, 0x70, 0x3d, 0xba, 0x82, 0xe3, 0x11, 0x37, 0xd3, 0x68, 0xe5, 0x5d, 0xd3, 0x4b,
	0xce, 0x6c, 0x4b, 0x85, 0xdf, 0x44, 0xb8, 0x30, 0xbc, 0x69, 0x87, 0x6e, 0xd1, 0x5f, 0x0c, 0xb8,
	0x51, 0xc0, 0x17, 0x0b, 0xab, 0x6f, 0x66, 0x70, 0x7e, 0x21, 0xdf, 0xc4, 0x0f, 0x9e, 0xb7, 0x6e,
	0x75, 0xd6, 0xa1, 0x02, 0xd0, 0xf2, 0xd8, 0xfb, 0xf4, 0x5c, 0x32, 0x64, 0xf4, 0x0a, 0x00, 0xcc,
	0x3e, 0xa0, 0xc4, 0xa7, 0x3e, 0x7a, 0x25, 0x17, 0x2f, 0x5f, 0xb9, 0x6d, 0x68, 0x5a, 0xf5, 0x07,
	0x03, 0x2a, 0x49, 0x86, 0x98, 0x81, 0x2a, 0x97, 0xb9, 0xd6, 0x5e, 0xbf, 0xc4, 0x2a, 0xcc, 0xf1,
	0x2d, 0x95, 0xc2, 0x2e, 0xde, 0xce, 0x6d, 0x0d, 0xf3, 0x59, 0x82, 0xe0, 0x7e, 0x6e, 0x9e, 0x2a,
	0x2f, 0xb2, 0x63, 0x7e, 0x63, 0x40, 0x25, 0x49, 0x9e, 0x32, 0x89, 0xe5, 0x12, 0xce, 0x4c, 0x62,
	0xf9, 0x1c, 0x10, 0xdf, 0x56, 0x89, 0xbd, 0x8a, 0xd7, 0x13, 0x89, 0x69, 0xe2, 0xd2, 0x88, 0x5e,
	0x60, 0x99, 0xc8, 0xdf, 0x0d, 0xb8, 0x9e, 0xc3, 0xe2, 0xd0, 0xf7, 0x5e, 0x18, 0x67, 0x9c, 0x37,
	0xd6, 0xb6, 0x26, 0x31, 0x0d, 0xf3, 0x7a, 0x47, 0xe5, 0x75, 0x0f, 0xbf, 0xf9, 0xa2, 0xbc, 0xcc,
	0x67, 0x49, 0xa6, 0x99, 0x06, 0x2e, 0xc9, 0xb3, 0x32, 0xc0, 0xe5, 0x52, 0xcb, 0x0c, 0x70, 0xf9,
	0x64, 0x2d, 0x02, 0xae, 0x76, 0x29, 0x70, 0x3f, 0x87, 0x72, 0xf4, 0x48, 0x17, 0xb6, 0x7c, 0x7a,
	0xb4, 0xa4, 0x5f, 0x75, 0x7c, 0x6f, 0xb2, 0x1e, 0x47, 0x68, 0x69, 0x3c, 0x1d, 0x26, 0x63, 0xfe,
	0xd9, 0x80, 0x4a, 0x92, 0xe2, 0x64, 0xa7, 0x40, 0x1e, 0x35, 0xcb, 0x00, 0x91, 0xcf, 0x93, 0x70,
	0x7b, 0xb2, 0xd4, 0xd6, 0xf1, 0x8d, 0x28, 0x35, 0x5b, 0x39, 0x4a, 0x80, 0xd4, 0x87, 0x59, 0x4d,
	0xa9, 0x26, 0x9e, 0x89, 0x49, 0x06, 0x86, 0x6f, 0x3f, 0x6f, 0x55, 0x3a, 0x0b, 0x99, 0xa8, 0x4b,
	0xa8, 0x12, 0x45, 0x1d, 0x68, 0xff, 0x7f, 0x8d, 0xfb, 0x22, 0x3e, 0x95, 0xfc, 0xbe, 0x48, 0x11,
	0xb6, 0x82, 0xbe, 0xc8, 0x9c, 0xd4, 0xa3, 0xc9, 0xe0, 0xa8, 0xe3, 0xb5, 0x44, 0xe3, 0x84, 0xe4,
	0xce, 0x1c, 0x29, 0xaf, 0x12, 0x92, 0xdf, 0x1a, 0xb0, 0x30, 0xce, 0xd7, 0x0a, 0x91, 0x79, 0x2d,
	0x95, 0x58, 0x1e, 0xc9, 0x9b, 0x78, 0x48, 0xe2, 0xd5, 0x44, 0x5a, 0x81, 0x72, 0x34, 0xf2, 0x07,
	0x32, 0xa3, 0x3f, 0x19, 0x8a, 0x41, 0x66, 0x69, 0x59, 0x51, 0x66, 0x77, 0xb3, 0x99, 0x15, 0xd2,
	0x95, 0x89, 0xfb, 0x08, 0xd5, 0xa2, 0x0c, 0xfb, 0xda, 0x83, 0x79, 0x41, 0x55, 0x1e, 0xfc, 0xab,
	0xf4, 0xbc, 0xf5, 0xcf, 0x12, 0xfa, 0x87, 0x01, 0xab, 0x47, 0x32, 0x74, 0x5d, 0x9e, 0x4f, 0x3d,
	0x64, 0x2c, 0xf5, 0xd6, 0xd1, 0x01, 0xde, 0x07, 0xd0, 0x9a, 0xc7, 0xd4, 0xee, 0xa3, 0xdb, 0x7d,
	0x21, 0xbc, 0xe0, 0xbe, 0x69, 0x8e, 0xfd, 0x1b, 0x58, 0xe5, 0xdc, 0x20, 0x2c, 0xfc, 0xd0, 0xff,
	0x27, 0xae, 0x08, 0x6a, 0xf7, 0xdf, 0xd5, 0xe5, 0xd8, 0x7c, 0xb8, 0x75, 0x24, 0x39, 0x9f, 0x74,
	0x73, 0xc8, 0x6c, 0x2a, 0xd9, 0xd6, 0x3b, 0x13, 0x7a, 0x32, 0x3b, 0x03, 0xde, 0x31, 0x87, 0x44,
	0xcd, 0xfd, 0xc3, 0x83, 0xf6, 0xfe, 0x07, 0xc7, 0xfb, 0x4d, 0xf1, 0xa9, 0xd8, 0x9b, 0xda, 0x6d,
	0xee, 0xd4, 0x96, 0xa8, 0xeb, 0x30, 0x97, 0xee, 0x85, 0xc0, 0x11, 0xb6, 0x55, 0x32, 0x4a, 0x7b,
	0x4b, 0xc4, 0xf3, 0x06, 0xe1, 0xb3, 0x67, 0xfe, 0x34, 0xe0, 0xee, 0xfd, 0x8c, 0xe4, 0xe3, 0x87,
	0xf0, 0x5a, 0x02, 0xb9, 0x95, 0x72, 0xa9, 0x76, 0xf5, 0xa3, 0x86, 0x4a, 0xb2, 0xd1, 0x3a, 0x3a,
	0x68, 0xbc, 0x4f, 0xcf, 0xeb, 0x25, 0xb8, 0x19, 0xc3, 0x79, 0xbd, 0x5c, 0xaa, 0x2d, 0x4a, 0x53,
	0xee, 0xb3, 0xcf, 0x94, 0xa3, 0x7a, 0xa9, 0xb3, 0x94, 0xc6, 0xbf, 0x33, 0xab, 0xb2, 0x7e, 0xe3,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x03, 0xd5, 0x43, 0x4c, 0xdc, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// User login given email and password
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Get user consent information
	Consent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ConsentResponse, error)
	// New user registration
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Get oauth google url
	OauthGoogle(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*OauthGoogleURL, error)
	// Oauth google callback
	CallbackOauthGoogle(ctx context.Context, in *CallbackGoogleRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Resend register email verification
	ResendEmailVerification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ResendEmailVerificationResponse, error)
	// Verify user registration
	VerifyRegister(ctx context.Context, in *VerifyRegisterRequest, opts ...grpc.CallOption) (*VerifyRegisterResponse, error)
	// Trigger to reset user password due to forgotten password
	ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordResponse, error)
	// Verify forget password token upon forget password action
	ForgetPasswordVerif(ctx context.Context, in *ForgetPasswordVerifRequest, opts ...grpc.CallOption) (*ForgetPasswordVerifResponse, error)
	// Update user password upon forget password action
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error)
	// User info after user logged in.
	UserInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserInfoResponse, error)
	// Change user password after user logged in.
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	// Logout user after user logged in
	Logout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*LogoutResponse, error)
	// UpdateUserInfo updates user info (name, address, contact)
	UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error)
	// GetSignedURL gets the sign url to gain access to uploads files on google cloud storage
	GetSignedURL(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetSignedURLResponse, error)
	// GetAssessmentHistory gets user assessments history.
	GetAssessmentHistory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAssessmentHistoryResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Consent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ConsentResponse, error) {
	out := new(ConsentResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/Consent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) OauthGoogle(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*OauthGoogleURL, error) {
	out := new(OauthGoogleURL)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/OauthGoogle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CallbackOauthGoogle(ctx context.Context, in *CallbackGoogleRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/CallbackOauthGoogle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResendEmailVerification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ResendEmailVerificationResponse, error) {
	out := new(ResendEmailVerificationResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/ResendEmailVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyRegister(ctx context.Context, in *VerifyRegisterRequest, opts ...grpc.CallOption) (*VerifyRegisterResponse, error) {
	out := new(VerifyRegisterResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/VerifyRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordResponse, error) {
	out := new(ForgetPasswordResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/ForgetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ForgetPasswordVerif(ctx context.Context, in *ForgetPasswordVerifRequest, opts ...grpc.CallOption) (*ForgetPasswordVerifResponse, error) {
	out := new(ForgetPasswordVerifResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/ForgetPasswordVerif", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error) {
	out := new(UpdatePasswordResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Logout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error) {
	out := new(UpdateUserInfoResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/UpdateUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetSignedURL(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetSignedURLResponse, error) {
	out := new(GetSignedURLResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/GetSignedURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAssessmentHistory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAssessmentHistoryResponse, error) {
	out := new(GetAssessmentHistoryResponse)
	err := c.cc.Invoke(ctx, "/prixa.user.v1.UserService/GetAssessmentHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// User login given email and password
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Get user consent information
	Consent(context.Context, *empty.Empty) (*ConsentResponse, error)
	// New user registration
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Get oauth google url
	OauthGoogle(context.Context, *empty.Empty) (*OauthGoogleURL, error)
	// Oauth google callback
	CallbackOauthGoogle(context.Context, *CallbackGoogleRequest) (*LoginResponse, error)
	// Resend register email verification
	ResendEmailVerification(context.Context, *empty.Empty) (*ResendEmailVerificationResponse, error)
	// Verify user registration
	VerifyRegister(context.Context, *VerifyRegisterRequest) (*VerifyRegisterResponse, error)
	// Trigger to reset user password due to forgotten password
	ForgetPassword(context.Context, *ForgetPasswordRequest) (*ForgetPasswordResponse, error)
	// Verify forget password token upon forget password action
	ForgetPasswordVerif(context.Context, *ForgetPasswordVerifRequest) (*ForgetPasswordVerifResponse, error)
	// Update user password upon forget password action
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error)
	// User info after user logged in.
	UserInfo(context.Context, *empty.Empty) (*UserInfoResponse, error)
	// Change user password after user logged in.
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	// Logout user after user logged in
	Logout(context.Context, *empty.Empty) (*LogoutResponse, error)
	// UpdateUserInfo updates user info (name, address, contact)
	UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*UpdateUserInfoResponse, error)
	// GetSignedURL gets the sign url to gain access to uploads files on google cloud storage
	GetSignedURL(context.Context, *empty.Empty) (*GetSignedURLResponse, error)
	// GetAssessmentHistory gets user assessments history.
	GetAssessmentHistory(context.Context, *empty.Empty) (*GetAssessmentHistoryResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) Consent(ctx context.Context, req *empty.Empty) (*ConsentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consent not implemented")
}
func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServiceServer) OauthGoogle(ctx context.Context, req *empty.Empty) (*OauthGoogleURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OauthGoogle not implemented")
}
func (*UnimplementedUserServiceServer) CallbackOauthGoogle(ctx context.Context, req *CallbackGoogleRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallbackOauthGoogle not implemented")
}
func (*UnimplementedUserServiceServer) ResendEmailVerification(ctx context.Context, req *empty.Empty) (*ResendEmailVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendEmailVerification not implemented")
}
func (*UnimplementedUserServiceServer) VerifyRegister(ctx context.Context, req *VerifyRegisterRequest) (*VerifyRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyRegister not implemented")
}
func (*UnimplementedUserServiceServer) ForgetPassword(ctx context.Context, req *ForgetPasswordRequest) (*ForgetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgetPassword not implemented")
}
func (*UnimplementedUserServiceServer) ForgetPasswordVerif(ctx context.Context, req *ForgetPasswordVerifRequest) (*ForgetPasswordVerifResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgetPasswordVerif not implemented")
}
func (*UnimplementedUserServiceServer) UpdatePassword(ctx context.Context, req *UpdatePasswordRequest) (*UpdatePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (*UnimplementedUserServiceServer) UserInfo(ctx context.Context, req *empty.Empty) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedUserServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedUserServiceServer) Logout(ctx context.Context, req *empty.Empty) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUserInfo(ctx context.Context, req *UpdateUserInfoRequest) (*UpdateUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserInfo not implemented")
}
func (*UnimplementedUserServiceServer) GetSignedURL(ctx context.Context, req *empty.Empty) (*GetSignedURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignedURL not implemented")
}
func (*UnimplementedUserServiceServer) GetAssessmentHistory(ctx context.Context, req *empty.Empty) (*GetAssessmentHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssessmentHistory not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Consent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Consent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/Consent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Consent(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_OauthGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).OauthGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/OauthGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).OauthGoogle(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CallbackOauthGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackGoogleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CallbackOauthGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/CallbackOauthGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CallbackOauthGoogle(ctx, req.(*CallbackGoogleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResendEmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResendEmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/ResendEmailVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResendEmailVerification(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/VerifyRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyRegister(ctx, req.(*VerifyRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ForgetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ForgetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/ForgetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ForgetPassword(ctx, req.(*ForgetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ForgetPasswordVerif_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordVerifRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ForgetPasswordVerif(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/ForgetPasswordVerif",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ForgetPasswordVerif(ctx, req.(*ForgetPasswordVerifRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Logout(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/UpdateUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserInfo(ctx, req.(*UpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetSignedURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetSignedURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/GetSignedURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetSignedURL(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAssessmentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAssessmentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.user.v1.UserService/GetAssessmentHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAssessmentHistory(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prixa.user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "Consent",
			Handler:    _UserService_Consent_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "OauthGoogle",
			Handler:    _UserService_OauthGoogle_Handler,
		},
		{
			MethodName: "CallbackOauthGoogle",
			Handler:    _UserService_CallbackOauthGoogle_Handler,
		},
		{
			MethodName: "ResendEmailVerification",
			Handler:    _UserService_ResendEmailVerification_Handler,
		},
		{
			MethodName: "VerifyRegister",
			Handler:    _UserService_VerifyRegister_Handler,
		},
		{
			MethodName: "ForgetPassword",
			Handler:    _UserService_ForgetPassword_Handler,
		},
		{
			MethodName: "ForgetPasswordVerif",
			Handler:    _UserService_ForgetPasswordVerif_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _UserService_UpdatePassword_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _UserService_UserInfo_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserService_ChangePassword_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserService_Logout_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _UserService_UpdateUserInfo_Handler,
		},
		{
			MethodName: "GetSignedURL",
			Handler:    _UserService_GetSignedURL_Handler,
		},
		{
			MethodName: "GetAssessmentHistory",
			Handler:    _UserService_GetAssessmentHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/v1/User.proto",
}
