// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/analytic/v1/Analytic.proto

package prixa_analytic_v1

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/golang/protobuf/ptypes/any"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *TrackArticleRequest) Validate() error {
	return nil
}
func (this *EventLog) Validate() error {
	if this.Date != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Date); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Date", err)
		}
	}
	if this.Metadata != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Metadata); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Metadata", err)
		}
	}
	return nil
}
