// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/analytic/v1/Analytic.proto

package prixa_analytics_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventLog struct {
	LogID                string               `protobuf:"bytes,1,opt,name=logID,proto3" json:"logID,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	PrixaAPIKey          string               `protobuf:"bytes,3,opt,name=prixaAPIKey,proto3" json:"prixaAPIKey,omitempty"`
	Environment          string               `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	PartnerID            string               `protobuf:"bytes,5,opt,name=partnerID,proto3" json:"partnerID,omitempty"`
	PartnerName          string               `protobuf:"bytes,6,opt,name=partnerName,proto3" json:"partnerName,omitempty"`
	Ip                   string               `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	UserID               string               `protobuf:"bytes,8,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string               `protobuf:"bytes,9,opt,name=userName,proto3" json:"userName,omitempty"`
	UserAgent            string               `protobuf:"bytes,10,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Type                 string               `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Hostname             string               `protobuf:"bytes,12,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Description          string               `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Metadata             *any.Any             `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventLog) Reset()         { *m = EventLog{} }
func (m *EventLog) String() string { return proto.CompactTextString(m) }
func (*EventLog) ProtoMessage()    {}
func (*EventLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_7501e1ee92099508, []int{0}
}

func (m *EventLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLog.Unmarshal(m, b)
}
func (m *EventLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLog.Marshal(b, m, deterministic)
}
func (m *EventLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLog.Merge(m, src)
}
func (m *EventLog) XXX_Size() int {
	return xxx_messageInfo_EventLog.Size(m)
}
func (m *EventLog) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLog.DiscardUnknown(m)
}

var xxx_messageInfo_EventLog proto.InternalMessageInfo

func (m *EventLog) GetLogID() string {
	if m != nil {
		return m.LogID
	}
	return ""
}

func (m *EventLog) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *EventLog) GetPrixaAPIKey() string {
	if m != nil {
		return m.PrixaAPIKey
	}
	return ""
}

func (m *EventLog) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *EventLog) GetPartnerID() string {
	if m != nil {
		return m.PartnerID
	}
	return ""
}

func (m *EventLog) GetPartnerName() string {
	if m != nil {
		return m.PartnerName
	}
	return ""
}

func (m *EventLog) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *EventLog) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *EventLog) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *EventLog) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *EventLog) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EventLog) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *EventLog) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EventLog) GetMetadata() *any.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type NalarEvent struct {
	EventLog             *EventLog `protobuf:"bytes,1,opt,name=eventLog,proto3" json:"eventLog,omitempty"`
	Latitude             float32   `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitue             float32   `protobuf:"fixed32,3,opt,name=longitue,proto3" json:"longitue,omitempty"`
	City                 string    `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Region               string    `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	SessionID            string    `protobuf:"bytes,6,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NalarEvent) Reset()         { *m = NalarEvent{} }
func (m *NalarEvent) String() string { return proto.CompactTextString(m) }
func (*NalarEvent) ProtoMessage()    {}
func (*NalarEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7501e1ee92099508, []int{1}
}

func (m *NalarEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NalarEvent.Unmarshal(m, b)
}
func (m *NalarEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NalarEvent.Marshal(b, m, deterministic)
}
func (m *NalarEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NalarEvent.Merge(m, src)
}
func (m *NalarEvent) XXX_Size() int {
	return xxx_messageInfo_NalarEvent.Size(m)
}
func (m *NalarEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NalarEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NalarEvent proto.InternalMessageInfo

func (m *NalarEvent) GetEventLog() *EventLog {
	if m != nil {
		return m.EventLog
	}
	return nil
}

func (m *NalarEvent) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *NalarEvent) GetLongitue() float32 {
	if m != nil {
		return m.Longitue
	}
	return 0
}

func (m *NalarEvent) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *NalarEvent) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *NalarEvent) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func init() {
	proto.RegisterType((*EventLog)(nil), "prixa.analytics.v1.EventLog")
	proto.RegisterType((*NalarEvent)(nil), "prixa.analytics.v1.NalarEvent")
}

func init() {
	proto.RegisterFile("proto/analytic/v1/Analytic.proto", fileDescriptor_7501e1ee92099508)
}

var fileDescriptor_7501e1ee92099508 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xcd, 0x6a, 0x1b, 0x31,
	0x10, 0xc6, 0x8e, 0xe3, 0xae, 0xe5, 0x36, 0x07, 0x11, 0x8a, 0x6a, 0x02, 0x35, 0x39, 0xe5, 0xa4,
	0x6d, 0xd2, 0x4b, 0xaf, 0x06, 0xf7, 0x60, 0x5a, 0x42, 0x59, 0xfa, 0x02, 0x8a, 0x3d, 0xdd, 0x0a,
	0x76, 0x25, 0x21, 0x8d, 0x97, 0xee, 0xab, 0xf5, 0x09, 0xfa, 0x58, 0x45, 0x23, 0xed, 0xda, 0xc4,
	0xb7, 0xf9, 0x7e, 0xfc, 0x69, 0x76, 0x3e, 0xb3, 0xb5, 0xf3, 0x16, 0x6d, 0xa9, 0x8c, 0x6a, 0x7a,
	0xd4, 0xfb, 0xb2, 0x7b, 0x2c, 0x37, 0x79, 0x96, 0x24, 0x71, 0xee, 0xbc, 0xfe, 0xa3, 0xe4, 0xe0,
	0x08, 0xb2, 0x7b, 0x5c, 0x7d, 0xac, 0xad, 0xad, 0x1b, 0x28, 0xc9, 0xf1, 0x72, 0xfc, 0x55, 0xa2,
	0x6e, 0x21, 0xa0, 0x6a, 0x5d, 0xfa, 0xd1, 0xea, 0xc3, 0x6b, 0x83, 0x32, 0x7d, 0x92, 0xee, 0xff,
	0x5e, 0xb1, 0xe2, 0x6b, 0x07, 0x06, 0xbf, 0xdb, 0x9a, 0xdf, 0xb2, 0xeb, 0xc6, 0xd6, 0xbb, 0xad,
	0x98, 0xac, 0x27, 0x0f, 0x8b, 0x2a, 0x01, 0x2e, 0xd9, 0xec, 0xa0, 0x10, 0xc4, 0x74, 0x3d, 0x79,
	0x58, 0x3e, 0xad, 0x64, 0x0a, 0x93, 0x43, 0x98, 0xfc, 0x39, 0xbc, 0x56, 0x91, 0x8f, 0xaf, 0xd9,
	0x92, 0x96, 0xdc, 0xfc, 0xd8, 0x7d, 0x83, 0x5e, 0x5c, 0x51, 0xd6, 0x39, 0x15, 0x1d, 0x60, 0x3a,
	0xed, 0xad, 0x69, 0xc1, 0xa0, 0x98, 0x25, 0xc7, 0x19, 0xc5, 0xef, 0xd8, 0xc2, 0x29, 0x8f, 0x06,
	0xfc, 0x6e, 0x2b, 0xae, 0x49, 0x3f, 0x11, 0xf4, 0x42, 0x02, 0xcf, 0xaa, 0x05, 0x31, 0xcf, 0x2f,
	0x9c, 0x28, 0x7e, 0xc3, 0xa6, 0xda, 0x89, 0x37, 0x24, 0x4c, 0xb5, 0xe3, 0xef, 0xd9, 0xfc, 0x18,
	0x28, 0xac, 0x20, 0x2e, 0x23, 0xbe, 0x62, 0x45, 0x9c, 0x28, 0x66, 0x41, 0xca, 0x88, 0xe3, 0x0e,
	0x71, 0xde, 0xd4, 0x71, 0x47, 0x96, 0x76, 0x18, 0x09, 0xce, 0xd9, 0x0c, 0x7b, 0x07, 0x62, 0x49,
	0x02, 0xcd, 0x31, 0xed, 0xb7, 0x0d, 0x68, 0x62, 0xda, 0xdb, 0x94, 0x36, 0xe0, 0xb8, 0xf3, 0x01,
	0xc2, 0xde, 0x6b, 0x87, 0xda, 0x1a, 0xf1, 0x2e, 0xed, 0x7c, 0x46, 0xf1, 0x4f, 0xac, 0x68, 0x01,
	0xd5, 0x41, 0xa1, 0x12, 0x37, 0x74, 0xeb, 0xdb, 0x8b, 0x5b, 0x6f, 0x4c, 0x5f, 0x8d, 0xae, 0xfb,
	0x7f, 0x13, 0xc6, 0x9e, 0x55, 0xa3, 0x3c, 0x35, 0xc8, 0xbf, 0xb0, 0x02, 0x72, 0x95, 0xd4, 0xe0,
	0xf2, 0xe9, 0x4e, 0x5e, 0xfe, 0x5d, 0xe4, 0x50, 0x77, 0x35, 0xba, 0xe3, 0xe2, 0x8d, 0x42, 0x8d,
	0xc7, 0x43, 0xaa, 0x79, 0x5a, 0x8d, 0x98, 0x34, 0x6b, 0x6a, 0x8d, 0x47, 0xa0, 0x2e, 0xa3, 0x96,
	0x71, 0x3c, 0xc2, 0x5e, 0x63, 0x9f, 0x1b, 0xa4, 0x39, 0x9e, 0xda, 0x43, 0x1d, 0xbf, 0x31, 0xf5,
	0x96, 0x51, 0x3c, 0x67, 0x80, 0x10, 0xb4, 0x35, 0xbb, 0x6d, 0xae, 0xec, 0x44, 0xbc, 0xcc, 0xe9,
	0x13, 0x3f, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x2f, 0x88, 0x0c, 0x02, 0x03, 0x00, 0x00,
}
