// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/partner/v1/Timestamp.proto

// Timestamp.proto defines the DataTimestamp message
// DataTimestamp contains 2 fields, createdAt, and updatedAt

package prixa_partner_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataTimestamp struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DataTimestamp) Reset()         { *m = DataTimestamp{} }
func (m *DataTimestamp) String() string { return proto.CompactTextString(m) }
func (*DataTimestamp) ProtoMessage()    {}
func (*DataTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_919e6e38fc869228, []int{0}
}

func (m *DataTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTimestamp.Unmarshal(m, b)
}
func (m *DataTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTimestamp.Marshal(b, m, deterministic)
}
func (m *DataTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTimestamp.Merge(m, src)
}
func (m *DataTimestamp) XXX_Size() int {
	return xxx_messageInfo_DataTimestamp.Size(m)
}
func (m *DataTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_DataTimestamp proto.InternalMessageInfo

func (m *DataTimestamp) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DataTimestamp) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*DataTimestamp)(nil), "prixa.partner.v1.DataTimestamp")
}

func init() { proto.RegisterFile("proto/partner/v1/Timestamp.proto", fileDescriptor_919e6e38fc869228) }

var fileDescriptor_919e6e38fc869228 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0x2c, 0x2a, 0xc9, 0x4b, 0x2d, 0xd2, 0x2f, 0x33, 0xd4, 0x0f, 0xc9, 0xcc,
	0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0xd0, 0x03, 0x4b, 0x09, 0x09, 0x14, 0x14, 0x65, 0x56, 0x24,
	0xea, 0x41, 0x55, 0xe8, 0x95, 0x19, 0x4a, 0xc9, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83,
	0xe5, 0x93, 0x4a, 0xd3, 0xf4, 0x4b, 0x50, 0xb5, 0x28, 0x35, 0x33, 0x72, 0xf1, 0xba, 0x24, 0x96,
	0x24, 0xc2, 0x8d, 0x12, 0xb2, 0xe0, 0xe2, 0x4c, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x71, 0x2c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0x18, 0xa3, 0x07, 0x33, 0x46, 0x0f,
	0xae, 0x3c, 0x08, 0xa1, 0x18, 0xa4, 0xb3, 0xb4, 0x20, 0x05, 0xaa, 0x93, 0x89, 0xb0, 0x4e, 0xb8,
	0xe2, 0x24, 0x36, 0xb0, 0xb4, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x41, 0x3a, 0x79, 0x4c, 0xe3,
	0x00, 0x00, 0x00,
}
