// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/diagnostic/v1/Diagnostic.proto

package prixa_diagnostic_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BotConversationRequest struct {
	SessionId            string     `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Reply                *ReplyData `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BotConversationRequest) Reset()         { *m = BotConversationRequest{} }
func (m *BotConversationRequest) String() string { return proto.CompactTextString(m) }
func (*BotConversationRequest) ProtoMessage()    {}
func (*BotConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{0}
}

func (m *BotConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotConversationRequest.Unmarshal(m, b)
}
func (m *BotConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotConversationRequest.Marshal(b, m, deterministic)
}
func (m *BotConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotConversationRequest.Merge(m, src)
}
func (m *BotConversationRequest) XXX_Size() int {
	return xxx_messageInfo_BotConversationRequest.Size(m)
}
func (m *BotConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotConversationRequest proto.InternalMessageInfo

func (m *BotConversationRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *BotConversationRequest) GetReply() *ReplyData {
	if m != nil {
		return m.Reply
	}
	return nil
}

type ReplyData struct {
	Tag                  string               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type                 string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string               `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Preconditions        []*PreconditionsData `protobuf:"bytes,4,rep,name=preconditions,proto3" json:"preconditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReplyData) Reset()         { *m = ReplyData{} }
func (m *ReplyData) String() string { return proto.CompactTextString(m) }
func (*ReplyData) ProtoMessage()    {}
func (*ReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{1}
}

func (m *ReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyData.Unmarshal(m, b)
}
func (m *ReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyData.Marshal(b, m, deterministic)
}
func (m *ReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyData.Merge(m, src)
}
func (m *ReplyData) XXX_Size() int {
	return xxx_messageInfo_ReplyData.Size(m)
}
func (m *ReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyData proto.InternalMessageInfo

func (m *ReplyData) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ReplyData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ReplyData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ReplyData) GetPreconditions() []*PreconditionsData {
	if m != nil {
		return m.Preconditions
	}
	return nil
}

type PreconditionsDataRequest struct {
	Data                 []*PreconditionsDataRequestProp `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *PreconditionsDataRequest) Reset()         { *m = PreconditionsDataRequest{} }
func (m *PreconditionsDataRequest) String() string { return proto.CompactTextString(m) }
func (*PreconditionsDataRequest) ProtoMessage()    {}
func (*PreconditionsDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{2}
}

func (m *PreconditionsDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreconditionsDataRequest.Unmarshal(m, b)
}
func (m *PreconditionsDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreconditionsDataRequest.Marshal(b, m, deterministic)
}
func (m *PreconditionsDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreconditionsDataRequest.Merge(m, src)
}
func (m *PreconditionsDataRequest) XXX_Size() int {
	return xxx_messageInfo_PreconditionsDataRequest.Size(m)
}
func (m *PreconditionsDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PreconditionsDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PreconditionsDataRequest proto.InternalMessageInfo

func (m *PreconditionsDataRequest) GetData() []*PreconditionsDataRequestProp {
	if m != nil {
		return m.Data
	}
	return nil
}

type PreconditionsDataRequestProp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values               string   `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreconditionsDataRequestProp) Reset()         { *m = PreconditionsDataRequestProp{} }
func (m *PreconditionsDataRequestProp) String() string { return proto.CompactTextString(m) }
func (*PreconditionsDataRequestProp) ProtoMessage()    {}
func (*PreconditionsDataRequestProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{3}
}

func (m *PreconditionsDataRequestProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreconditionsDataRequestProp.Unmarshal(m, b)
}
func (m *PreconditionsDataRequestProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreconditionsDataRequestProp.Marshal(b, m, deterministic)
}
func (m *PreconditionsDataRequestProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreconditionsDataRequestProp.Merge(m, src)
}
func (m *PreconditionsDataRequestProp) XXX_Size() int {
	return xxx_messageInfo_PreconditionsDataRequestProp.Size(m)
}
func (m *PreconditionsDataRequestProp) XXX_DiscardUnknown() {
	xxx_messageInfo_PreconditionsDataRequestProp.DiscardUnknown(m)
}

var xxx_messageInfo_PreconditionsDataRequestProp proto.InternalMessageInfo

func (m *PreconditionsDataRequestProp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PreconditionsDataRequestProp) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

type BotConversationResponse struct {
	SessionId             string       `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Result                *ResultData  `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ProgressBarPercentage float32      `protobuf:"fixed32,3,opt,name=progressBarPercentage,proto3" json:"progressBarPercentage,omitempty"`
	LogEvents             []*LogEvents `protobuf:"bytes,4,rep,name=logEvents,proto3" json:"logEvents,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *BotConversationResponse) Reset()         { *m = BotConversationResponse{} }
func (m *BotConversationResponse) String() string { return proto.CompactTextString(m) }
func (*BotConversationResponse) ProtoMessage()    {}
func (*BotConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{4}
}

func (m *BotConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotConversationResponse.Unmarshal(m, b)
}
func (m *BotConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotConversationResponse.Marshal(b, m, deterministic)
}
func (m *BotConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotConversationResponse.Merge(m, src)
}
func (m *BotConversationResponse) XXX_Size() int {
	return xxx_messageInfo_BotConversationResponse.Size(m)
}
func (m *BotConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BotConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BotConversationResponse proto.InternalMessageInfo

func (m *BotConversationResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *BotConversationResponse) GetResult() *ResultData {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *BotConversationResponse) GetProgressBarPercentage() float32 {
	if m != nil {
		return m.ProgressBarPercentage
	}
	return 0
}

func (m *BotConversationResponse) GetLogEvents() []*LogEvents {
	if m != nil {
		return m.LogEvents
	}
	return nil
}

type ResultData struct {
	Messages             *MessagesData        `protobuf:"bytes,1,opt,name=messages,proto3" json:"messages,omitempty"`
	Actions              *ActionData          `protobuf:"bytes,2,opt,name=actions,proto3" json:"actions,omitempty"`
	Preconditions        []*PreconditionsData `protobuf:"bytes,3,rep,name=preconditions,proto3" json:"preconditions,omitempty"`
	CurrentState         string               `protobuf:"bytes,4,opt,name=currentState,proto3" json:"currentState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResultData) Reset()         { *m = ResultData{} }
func (m *ResultData) String() string { return proto.CompactTextString(m) }
func (*ResultData) ProtoMessage()    {}
func (*ResultData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{5}
}

func (m *ResultData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultData.Unmarshal(m, b)
}
func (m *ResultData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultData.Marshal(b, m, deterministic)
}
func (m *ResultData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultData.Merge(m, src)
}
func (m *ResultData) XXX_Size() int {
	return xxx_messageInfo_ResultData.Size(m)
}
func (m *ResultData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultData.DiscardUnknown(m)
}

var xxx_messageInfo_ResultData proto.InternalMessageInfo

func (m *ResultData) GetMessages() *MessagesData {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *ResultData) GetActions() *ActionData {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *ResultData) GetPreconditions() []*PreconditionsData {
	if m != nil {
		return m.Preconditions
	}
	return nil
}

func (m *ResultData) GetCurrentState() string {
	if m != nil {
		return m.CurrentState
	}
	return ""
}

type MessagesData struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Media                string   `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
	SourceURL            string   `protobuf:"bytes,4,opt,name=sourceURL,proto3" json:"sourceURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesData) Reset()         { *m = MessagesData{} }
func (m *MessagesData) String() string { return proto.CompactTextString(m) }
func (*MessagesData) ProtoMessage()    {}
func (*MessagesData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{6}
}

func (m *MessagesData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesData.Unmarshal(m, b)
}
func (m *MessagesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesData.Marshal(b, m, deterministic)
}
func (m *MessagesData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesData.Merge(m, src)
}
func (m *MessagesData) XXX_Size() int {
	return xxx_messageInfo_MessagesData.Size(m)
}
func (m *MessagesData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesData.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesData proto.InternalMessageInfo

func (m *MessagesData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *MessagesData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MessagesData) GetMedia() string {
	if m != nil {
		return m.Media
	}
	return ""
}

func (m *MessagesData) GetSourceURL() string {
	if m != nil {
		return m.SourceURL
	}
	return ""
}

type ActionData struct {
	Type                 string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                []*ValueData         `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	DiagnosisResult      *DiagnosisResultData `protobuf:"bytes,3,opt,name=diagnosisResult,proto3" json:"diagnosisResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ActionData) Reset()         { *m = ActionData{} }
func (m *ActionData) String() string { return proto.CompactTextString(m) }
func (*ActionData) ProtoMessage()    {}
func (*ActionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{7}
}

func (m *ActionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionData.Unmarshal(m, b)
}
func (m *ActionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionData.Marshal(b, m, deterministic)
}
func (m *ActionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionData.Merge(m, src)
}
func (m *ActionData) XXX_Size() int {
	return xxx_messageInfo_ActionData.Size(m)
}
func (m *ActionData) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionData.DiscardUnknown(m)
}

var xxx_messageInfo_ActionData proto.InternalMessageInfo

func (m *ActionData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ActionData) GetValue() []*ValueData {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ActionData) GetDiagnosisResult() *DiagnosisResultData {
	if m != nil {
		return m.DiagnosisResult
	}
	return nil
}

type ValueData struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueData) Reset()         { *m = ValueData{} }
func (m *ValueData) String() string { return proto.CompactTextString(m) }
func (*ValueData) ProtoMessage()    {}
func (*ValueData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{8}
}

func (m *ValueData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueData.Unmarshal(m, b)
}
func (m *ValueData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueData.Marshal(b, m, deterministic)
}
func (m *ValueData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueData.Merge(m, src)
}
func (m *ValueData) XXX_Size() int {
	return xxx_messageInfo_ValueData.Size(m)
}
func (m *ValueData) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueData.DiscardUnknown(m)
}

var xxx_messageInfo_ValueData proto.InternalMessageInfo

func (m *ValueData) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ValueData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ValueData) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ValueData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DiagnosisResultData struct {
	User                 *UserData           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UserDetails          *UserDetailsData    `protobuf:"bytes,2,opt,name=userDetails,proto3" json:"userDetails,omitempty"`
	Profiles             []*ProfileData      `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Symptoms             []*SymptomDesc      `protobuf:"bytes,4,rep,name=symptoms,proto3" json:"symptoms,omitempty"`
	Diseases             []*PotentialDisease `protobuf:"bytes,5,rep,name=diseases,proto3" json:"diseases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DiagnosisResultData) Reset()         { *m = DiagnosisResultData{} }
func (m *DiagnosisResultData) String() string { return proto.CompactTextString(m) }
func (*DiagnosisResultData) ProtoMessage()    {}
func (*DiagnosisResultData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{9}
}

func (m *DiagnosisResultData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosisResultData.Unmarshal(m, b)
}
func (m *DiagnosisResultData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosisResultData.Marshal(b, m, deterministic)
}
func (m *DiagnosisResultData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosisResultData.Merge(m, src)
}
func (m *DiagnosisResultData) XXX_Size() int {
	return xxx_messageInfo_DiagnosisResultData.Size(m)
}
func (m *DiagnosisResultData) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosisResultData.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosisResultData proto.InternalMessageInfo

func (m *DiagnosisResultData) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *DiagnosisResultData) GetUserDetails() *UserDetailsData {
	if m != nil {
		return m.UserDetails
	}
	return nil
}

func (m *DiagnosisResultData) GetProfiles() []*ProfileData {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *DiagnosisResultData) GetSymptoms() []*SymptomDesc {
	if m != nil {
		return m.Symptoms
	}
	return nil
}

func (m *DiagnosisResultData) GetDiseases() []*PotentialDisease {
	if m != nil {
		return m.Diseases
	}
	return nil
}

type UserDetailsData struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	IsObese              bool     `protobuf:"varint,3,opt,name=isObese,proto3" json:"isObese,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetailsData) Reset()         { *m = UserDetailsData{} }
func (m *UserDetailsData) String() string { return proto.CompactTextString(m) }
func (*UserDetailsData) ProtoMessage()    {}
func (*UserDetailsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{10}
}

func (m *UserDetailsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailsData.Unmarshal(m, b)
}
func (m *UserDetailsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailsData.Marshal(b, m, deterministic)
}
func (m *UserDetailsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailsData.Merge(m, src)
}
func (m *UserDetailsData) XXX_Size() int {
	return xxx_messageInfo_UserDetailsData.Size(m)
}
func (m *UserDetailsData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailsData.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailsData proto.InternalMessageInfo

func (m *UserDetailsData) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserDetailsData) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UserDetailsData) GetIsObese() bool {
	if m != nil {
		return m.IsObese
	}
	return false
}

type ProfileData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameIndo             string   `protobuf:"bytes,3,opt,name=nameIndo,proto3" json:"nameIndo,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Order                int32    `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileData) Reset()         { *m = ProfileData{} }
func (m *ProfileData) String() string { return proto.CompactTextString(m) }
func (*ProfileData) ProtoMessage()    {}
func (*ProfileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{11}
}

func (m *ProfileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileData.Unmarshal(m, b)
}
func (m *ProfileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileData.Marshal(b, m, deterministic)
}
func (m *ProfileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileData.Merge(m, src)
}
func (m *ProfileData) XXX_Size() int {
	return xxx_messageInfo_ProfileData.Size(m)
}
func (m *ProfileData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileData.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileData proto.InternalMessageInfo

func (m *ProfileData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProfileData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileData) GetNameIndo() string {
	if m != nil {
		return m.NameIndo
	}
	return ""
}

func (m *ProfileData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProfileData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProfileData) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type SymptomDesc struct {
	SymptomID            string   `protobuf:"bytes,1,opt,name=symptomID,proto3" json:"symptomID,omitempty"`
	SymptomName          string   `protobuf:"bytes,2,opt,name=symptomName,proto3" json:"symptomName,omitempty"`
	PropNames            []string `protobuf:"bytes,3,rep,name=propNames,proto3" json:"propNames,omitempty"`
	Chief                bool     `protobuf:"varint,4,opt,name=chief,proto3" json:"chief,omitempty"`
	SymptomsTriage       []string `protobuf:"bytes,5,rep,name=symptomsTriage,proto3" json:"symptomsTriage,omitempty"`
	Answer               string   `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SymptomDesc) Reset()         { *m = SymptomDesc{} }
func (m *SymptomDesc) String() string { return proto.CompactTextString(m) }
func (*SymptomDesc) ProtoMessage()    {}
func (*SymptomDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{12}
}

func (m *SymptomDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymptomDesc.Unmarshal(m, b)
}
func (m *SymptomDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymptomDesc.Marshal(b, m, deterministic)
}
func (m *SymptomDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymptomDesc.Merge(m, src)
}
func (m *SymptomDesc) XXX_Size() int {
	return xxx_messageInfo_SymptomDesc.Size(m)
}
func (m *SymptomDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_SymptomDesc.DiscardUnknown(m)
}

var xxx_messageInfo_SymptomDesc proto.InternalMessageInfo

func (m *SymptomDesc) GetSymptomID() string {
	if m != nil {
		return m.SymptomID
	}
	return ""
}

func (m *SymptomDesc) GetSymptomName() string {
	if m != nil {
		return m.SymptomName
	}
	return ""
}

func (m *SymptomDesc) GetPropNames() []string {
	if m != nil {
		return m.PropNames
	}
	return nil
}

func (m *SymptomDesc) GetChief() bool {
	if m != nil {
		return m.Chief
	}
	return false
}

func (m *SymptomDesc) GetSymptomsTriage() []string {
	if m != nil {
		return m.SymptomsTriage
	}
	return nil
}

func (m *SymptomDesc) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type PotentialDisease struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Likeliness           string        `protobuf:"bytes,4,opt,name=likeliness,proto3" json:"likeliness,omitempty"`
	Score                float32       `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	Url                  string        `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Triage               *TriageResult `protobuf:"bytes,7,opt,name=triage,proto3" json:"triage,omitempty"`
	Labs                 []*LabInfo    `protobuf:"bytes,8,rep,name=labs,proto3" json:"labs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PotentialDisease) Reset()         { *m = PotentialDisease{} }
func (m *PotentialDisease) String() string { return proto.CompactTextString(m) }
func (*PotentialDisease) ProtoMessage()    {}
func (*PotentialDisease) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{13}
}

func (m *PotentialDisease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotentialDisease.Unmarshal(m, b)
}
func (m *PotentialDisease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotentialDisease.Marshal(b, m, deterministic)
}
func (m *PotentialDisease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotentialDisease.Merge(m, src)
}
func (m *PotentialDisease) XXX_Size() int {
	return xxx_messageInfo_PotentialDisease.Size(m)
}
func (m *PotentialDisease) XXX_DiscardUnknown() {
	xxx_messageInfo_PotentialDisease.DiscardUnknown(m)
}

var xxx_messageInfo_PotentialDisease proto.InternalMessageInfo

func (m *PotentialDisease) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PotentialDisease) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PotentialDisease) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PotentialDisease) GetLikeliness() string {
	if m != nil {
		return m.Likeliness
	}
	return ""
}

func (m *PotentialDisease) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *PotentialDisease) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PotentialDisease) GetTriage() *TriageResult {
	if m != nil {
		return m.Triage
	}
	return nil
}

func (m *PotentialDisease) GetLabs() []*LabInfo {
	if m != nil {
		return m.Labs
	}
	return nil
}

type TriageResult struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameIndo             string   `protobuf:"bytes,3,opt,name=nameIndo,proto3" json:"nameIndo,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriageResult) Reset()         { *m = TriageResult{} }
func (m *TriageResult) String() string { return proto.CompactTextString(m) }
func (*TriageResult) ProtoMessage()    {}
func (*TriageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{14}
}

func (m *TriageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriageResult.Unmarshal(m, b)
}
func (m *TriageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriageResult.Marshal(b, m, deterministic)
}
func (m *TriageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriageResult.Merge(m, src)
}
func (m *TriageResult) XXX_Size() int {
	return xxx_messageInfo_TriageResult.Size(m)
}
func (m *TriageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TriageResult.DiscardUnknown(m)
}

var xxx_messageInfo_TriageResult proto.InternalMessageInfo

func (m *TriageResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TriageResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TriageResult) GetNameIndo() string {
	if m != nil {
		return m.NameIndo
	}
	return ""
}

func (m *TriageResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type LabInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku                  string   `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Diseases             []string `protobuf:"bytes,4,rep,name=diseases,proto3" json:"diseases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabInfo) Reset()         { *m = LabInfo{} }
func (m *LabInfo) String() string { return proto.CompactTextString(m) }
func (*LabInfo) ProtoMessage()    {}
func (*LabInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{15}
}

func (m *LabInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabInfo.Unmarshal(m, b)
}
func (m *LabInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabInfo.Marshal(b, m, deterministic)
}
func (m *LabInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabInfo.Merge(m, src)
}
func (m *LabInfo) XXX_Size() int {
	return xxx_messageInfo_LabInfo.Size(m)
}
func (m *LabInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LabInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LabInfo proto.InternalMessageInfo

func (m *LabInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LabInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LabInfo) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *LabInfo) GetDiseases() []string {
	if m != nil {
		return m.Diseases
	}
	return nil
}

type PreconditionsData struct {
	Id                           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                         string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	NameIndo                     string   `protobuf:"bytes,3,opt,name=nameIndo,proto3" json:"nameIndo,omitempty"`
	PreconditionsDescription     string   `protobuf:"bytes,4,opt,name=preconditionsDescription,proto3" json:"preconditionsDescription,omitempty"`
	PreconditionsDescriptionCopy string   `protobuf:"bytes,5,opt,name=preconditionsDescriptionCopy,proto3" json:"preconditionsDescriptionCopy,omitempty"`
	AgeMonth                     int64    `protobuf:"varint,6,opt,name=ageMonth,proto3" json:"ageMonth,omitempty"`
	AgeYear                      int64    `protobuf:"varint,7,opt,name=ageYear,proto3" json:"ageYear,omitempty"`
	Weight                       float32  `protobuf:"fixed32,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Height                       float32  `protobuf:"fixed32,9,opt,name=height,proto3" json:"height,omitempty"`
	Name                         string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *PreconditionsData) Reset()         { *m = PreconditionsData{} }
func (m *PreconditionsData) String() string { return proto.CompactTextString(m) }
func (*PreconditionsData) ProtoMessage()    {}
func (*PreconditionsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{16}
}

func (m *PreconditionsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreconditionsData.Unmarshal(m, b)
}
func (m *PreconditionsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreconditionsData.Marshal(b, m, deterministic)
}
func (m *PreconditionsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreconditionsData.Merge(m, src)
}
func (m *PreconditionsData) XXX_Size() int {
	return xxx_messageInfo_PreconditionsData.Size(m)
}
func (m *PreconditionsData) XXX_DiscardUnknown() {
	xxx_messageInfo_PreconditionsData.DiscardUnknown(m)
}

var xxx_messageInfo_PreconditionsData proto.InternalMessageInfo

func (m *PreconditionsData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PreconditionsData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PreconditionsData) GetNameIndo() string {
	if m != nil {
		return m.NameIndo
	}
	return ""
}

func (m *PreconditionsData) GetPreconditionsDescription() string {
	if m != nil {
		return m.PreconditionsDescription
	}
	return ""
}

func (m *PreconditionsData) GetPreconditionsDescriptionCopy() string {
	if m != nil {
		return m.PreconditionsDescriptionCopy
	}
	return ""
}

func (m *PreconditionsData) GetAgeMonth() int64 {
	if m != nil {
		return m.AgeMonth
	}
	return 0
}

func (m *PreconditionsData) GetAgeYear() int64 {
	if m != nil {
		return m.AgeYear
	}
	return 0
}

func (m *PreconditionsData) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *PreconditionsData) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PreconditionsData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LogEvents struct {
	Answer               string   `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	ApplicationId        string   `protobuf:"bytes,2,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	PartnerId            string   `protobuf:"bytes,3,opt,name=partnerId,proto3" json:"partnerId,omitempty"`
	PrixaSessionId       string   `protobuf:"bytes,4,opt,name=prixaSessionId,proto3" json:"prixaSessionId,omitempty"`
	PrixaUserId          string   `protobuf:"bytes,5,opt,name=prixaUserId,proto3" json:"prixaUserId,omitempty"`
	Question             string   `protobuf:"bytes,6,opt,name=question,proto3" json:"question,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEvents) Reset()         { *m = LogEvents{} }
func (m *LogEvents) String() string { return proto.CompactTextString(m) }
func (*LogEvents) ProtoMessage()    {}
func (*LogEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{17}
}

func (m *LogEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEvents.Unmarshal(m, b)
}
func (m *LogEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEvents.Marshal(b, m, deterministic)
}
func (m *LogEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEvents.Merge(m, src)
}
func (m *LogEvents) XXX_Size() int {
	return xxx_messageInfo_LogEvents.Size(m)
}
func (m *LogEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEvents.DiscardUnknown(m)
}

var xxx_messageInfo_LogEvents proto.InternalMessageInfo

func (m *LogEvents) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *LogEvents) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *LogEvents) GetPartnerId() string {
	if m != nil {
		return m.PartnerId
	}
	return ""
}

func (m *LogEvents) GetPrixaSessionId() string {
	if m != nil {
		return m.PrixaSessionId
	}
	return ""
}

func (m *LogEvents) GetPrixaUserId() string {
	if m != nil {
		return m.PrixaUserId
	}
	return ""
}

func (m *LogEvents) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

type CreatePrixaSessionRequest struct {
	PartnerId            string    `protobuf:"bytes,1,opt,name=partnerId,proto3" json:"partnerId,omitempty"`
	PartnerAppId         string    `protobuf:"bytes,2,opt,name=partnerAppId,proto3" json:"partnerAppId,omitempty"`
	UserData             *UserData `protobuf:"bytes,3,opt,name=userData,proto3" json:"userData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePrixaSessionRequest) Reset()         { *m = CreatePrixaSessionRequest{} }
func (m *CreatePrixaSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePrixaSessionRequest) ProtoMessage()    {}
func (*CreatePrixaSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{18}
}

func (m *CreatePrixaSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePrixaSessionRequest.Unmarshal(m, b)
}
func (m *CreatePrixaSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePrixaSessionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePrixaSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePrixaSessionRequest.Merge(m, src)
}
func (m *CreatePrixaSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePrixaSessionRequest.Size(m)
}
func (m *CreatePrixaSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePrixaSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePrixaSessionRequest proto.InternalMessageInfo

func (m *CreatePrixaSessionRequest) GetPartnerId() string {
	if m != nil {
		return m.PartnerId
	}
	return ""
}

func (m *CreatePrixaSessionRequest) GetPartnerAppId() string {
	if m != nil {
		return m.PartnerAppId
	}
	return ""
}

func (m *CreatePrixaSessionRequest) GetUserData() *UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type CreatePrixaSessionResponse struct {
	SessionId            string    `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	UserData             *UserData `protobuf:"bytes,2,opt,name=userData,proto3" json:"userData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePrixaSessionResponse) Reset()         { *m = CreatePrixaSessionResponse{} }
func (m *CreatePrixaSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePrixaSessionResponse) ProtoMessage()    {}
func (*CreatePrixaSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{19}
}

func (m *CreatePrixaSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePrixaSessionResponse.Unmarshal(m, b)
}
func (m *CreatePrixaSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePrixaSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreatePrixaSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePrixaSessionResponse.Merge(m, src)
}
func (m *CreatePrixaSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePrixaSessionResponse.Size(m)
}
func (m *CreatePrixaSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePrixaSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePrixaSessionResponse proto.InternalMessageInfo

func (m *CreatePrixaSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *CreatePrixaSessionResponse) GetUserData() *UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type UserData struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname             string           `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Gender               string           `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthdate            string           `protobuf:"bytes,4,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Weight               float32          `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Height               float32          `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	Insurance            *InsuranceStatus `protobuf:"bytes,7,opt,name=insurance,proto3" json:"insurance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{20}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserData) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *UserData) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserData) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *UserData) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *UserData) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *UserData) GetInsurance() *InsuranceStatus {
	if m != nil {
		return m.Insurance
	}
	return nil
}

type InsuranceStatus struct {
	HaveInsurance        bool     `protobuf:"varint,1,opt,name=haveInsurance,proto3" json:"haveInsurance,omitempty"`
	PlanToHaveInsurance  bool     `protobuf:"varint,2,opt,name=planToHaveInsurance,proto3" json:"planToHaveInsurance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsuranceStatus) Reset()         { *m = InsuranceStatus{} }
func (m *InsuranceStatus) String() string { return proto.CompactTextString(m) }
func (*InsuranceStatus) ProtoMessage()    {}
func (*InsuranceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{21}
}

func (m *InsuranceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsuranceStatus.Unmarshal(m, b)
}
func (m *InsuranceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsuranceStatus.Marshal(b, m, deterministic)
}
func (m *InsuranceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsuranceStatus.Merge(m, src)
}
func (m *InsuranceStatus) XXX_Size() int {
	return xxx_messageInfo_InsuranceStatus.Size(m)
}
func (m *InsuranceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InsuranceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InsuranceStatus proto.InternalMessageInfo

func (m *InsuranceStatus) GetHaveInsurance() bool {
	if m != nil {
		return m.HaveInsurance
	}
	return false
}

func (m *InsuranceStatus) GetPlanToHaveInsurance() bool {
	if m != nil {
		return m.PlanToHaveInsurance
	}
	return false
}

type SendEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SessionId            string   `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{22}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendEmailRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SendEmailRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type SendEmailResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{23}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendSurveyRequest struct {
	ApplicationId        string   `protobuf:"bytes,1,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	Feedback             string   `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	PartnerId            string   `protobuf:"bytes,3,opt,name=partnerId,proto3" json:"partnerId,omitempty"`
	Rating               int32    `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	SessionId            string   `protobuf:"bytes,5,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	UserId               string   `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSurveyRequest) Reset()         { *m = SendSurveyRequest{} }
func (m *SendSurveyRequest) String() string { return proto.CompactTextString(m) }
func (*SendSurveyRequest) ProtoMessage()    {}
func (*SendSurveyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{24}
}

func (m *SendSurveyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSurveyRequest.Unmarshal(m, b)
}
func (m *SendSurveyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSurveyRequest.Marshal(b, m, deterministic)
}
func (m *SendSurveyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSurveyRequest.Merge(m, src)
}
func (m *SendSurveyRequest) XXX_Size() int {
	return xxx_messageInfo_SendSurveyRequest.Size(m)
}
func (m *SendSurveyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSurveyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSurveyRequest proto.InternalMessageInfo

func (m *SendSurveyRequest) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *SendSurveyRequest) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

func (m *SendSurveyRequest) GetPartnerId() string {
	if m != nil {
		return m.PartnerId
	}
	return ""
}

func (m *SendSurveyRequest) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *SendSurveyRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SendSurveyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type FeedbackContentResponse struct {
	Question             string   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Instruction          string   `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Choices              []string `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedbackContentResponse) Reset()         { *m = FeedbackContentResponse{} }
func (m *FeedbackContentResponse) String() string { return proto.CompactTextString(m) }
func (*FeedbackContentResponse) ProtoMessage()    {}
func (*FeedbackContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{25}
}

func (m *FeedbackContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedbackContentResponse.Unmarshal(m, b)
}
func (m *FeedbackContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedbackContentResponse.Marshal(b, m, deterministic)
}
func (m *FeedbackContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedbackContentResponse.Merge(m, src)
}
func (m *FeedbackContentResponse) XXX_Size() int {
	return xxx_messageInfo_FeedbackContentResponse.Size(m)
}
func (m *FeedbackContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedbackContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedbackContentResponse proto.InternalMessageInfo

func (m *FeedbackContentResponse) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *FeedbackContentResponse) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *FeedbackContentResponse) GetChoices() []string {
	if m != nil {
		return m.Choices
	}
	return nil
}

type SendFeedbackRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PartnerId            string   `protobuf:"bytes,2,opt,name=partnerId,proto3" json:"partnerId,omitempty"`
	ApplicationId        string   `protobuf:"bytes,3,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	SessionId            string   `protobuf:"bytes,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	SymptomId            string   `protobuf:"bytes,5,opt,name=symptomId,proto3" json:"symptomId,omitempty"`
	Question             string   `protobuf:"bytes,6,opt,name=question,proto3" json:"question,omitempty"`
	Feedbacks            []string `protobuf:"bytes,7,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
	Detail               string   `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendFeedbackRequest) Reset()         { *m = SendFeedbackRequest{} }
func (m *SendFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*SendFeedbackRequest) ProtoMessage()    {}
func (*SendFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{26}
}

func (m *SendFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFeedbackRequest.Unmarshal(m, b)
}
func (m *SendFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *SendFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFeedbackRequest.Merge(m, src)
}
func (m *SendFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_SendFeedbackRequest.Size(m)
}
func (m *SendFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendFeedbackRequest proto.InternalMessageInfo

func (m *SendFeedbackRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SendFeedbackRequest) GetPartnerId() string {
	if m != nil {
		return m.PartnerId
	}
	return ""
}

func (m *SendFeedbackRequest) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *SendFeedbackRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SendFeedbackRequest) GetSymptomId() string {
	if m != nil {
		return m.SymptomId
	}
	return ""
}

func (m *SendFeedbackRequest) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *SendFeedbackRequest) GetFeedbacks() []string {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

func (m *SendFeedbackRequest) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type SendFeedbackResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendFeedbackResponse) Reset()         { *m = SendFeedbackResponse{} }
func (m *SendFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*SendFeedbackResponse) ProtoMessage()    {}
func (*SendFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_793ea97929c08cdd, []int{27}
}

func (m *SendFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFeedbackResponse.Unmarshal(m, b)
}
func (m *SendFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *SendFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFeedbackResponse.Merge(m, src)
}
func (m *SendFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_SendFeedbackResponse.Size(m)
}
func (m *SendFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendFeedbackResponse proto.InternalMessageInfo

func (m *SendFeedbackResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*BotConversationRequest)(nil), "prixa.diagnostic.v1.BotConversationRequest")
	proto.RegisterType((*ReplyData)(nil), "prixa.diagnostic.v1.ReplyData")
	proto.RegisterType((*PreconditionsDataRequest)(nil), "prixa.diagnostic.v1.PreconditionsDataRequest")
	proto.RegisterType((*PreconditionsDataRequestProp)(nil), "prixa.diagnostic.v1.PreconditionsDataRequestProp")
	proto.RegisterType((*BotConversationResponse)(nil), "prixa.diagnostic.v1.BotConversationResponse")
	proto.RegisterType((*ResultData)(nil), "prixa.diagnostic.v1.ResultData")
	proto.RegisterType((*MessagesData)(nil), "prixa.diagnostic.v1.MessagesData")
	proto.RegisterType((*ActionData)(nil), "prixa.diagnostic.v1.ActionData")
	proto.RegisterType((*ValueData)(nil), "prixa.diagnostic.v1.ValueData")
	proto.RegisterType((*DiagnosisResultData)(nil), "prixa.diagnostic.v1.DiagnosisResultData")
	proto.RegisterType((*UserDetailsData)(nil), "prixa.diagnostic.v1.UserDetailsData")
	proto.RegisterType((*ProfileData)(nil), "prixa.diagnostic.v1.ProfileData")
	proto.RegisterType((*SymptomDesc)(nil), "prixa.diagnostic.v1.SymptomDesc")
	proto.RegisterType((*PotentialDisease)(nil), "prixa.diagnostic.v1.PotentialDisease")
	proto.RegisterType((*TriageResult)(nil), "prixa.diagnostic.v1.TriageResult")
	proto.RegisterType((*LabInfo)(nil), "prixa.diagnostic.v1.LabInfo")
	proto.RegisterType((*PreconditionsData)(nil), "prixa.diagnostic.v1.PreconditionsData")
	proto.RegisterType((*LogEvents)(nil), "prixa.diagnostic.v1.LogEvents")
	proto.RegisterType((*CreatePrixaSessionRequest)(nil), "prixa.diagnostic.v1.CreatePrixaSessionRequest")
	proto.RegisterType((*CreatePrixaSessionResponse)(nil), "prixa.diagnostic.v1.CreatePrixaSessionResponse")
	proto.RegisterType((*UserData)(nil), "prixa.diagnostic.v1.UserData")
	proto.RegisterType((*InsuranceStatus)(nil), "prixa.diagnostic.v1.InsuranceStatus")
	proto.RegisterType((*SendEmailRequest)(nil), "prixa.diagnostic.v1.SendEmailRequest")
	proto.RegisterType((*SendEmailResponse)(nil), "prixa.diagnostic.v1.SendEmailResponse")
	proto.RegisterType((*SendSurveyRequest)(nil), "prixa.diagnostic.v1.SendSurveyRequest")
	proto.RegisterType((*FeedbackContentResponse)(nil), "prixa.diagnostic.v1.FeedbackContentResponse")
	proto.RegisterType((*SendFeedbackRequest)(nil), "prixa.diagnostic.v1.SendFeedbackRequest")
	proto.RegisterType((*SendFeedbackResponse)(nil), "prixa.diagnostic.v1.SendFeedbackResponse")
}

func init() {
	proto.RegisterFile("proto/diagnostic/v1/Diagnostic.proto", fileDescriptor_793ea97929c08cdd)
}

var fileDescriptor_793ea97929c08cdd = []byte{
	// 1846 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4f, 0x6f, 0x1c, 0x49,
	0x15, 0x57, 0xf7, 0xfc, 0xf1, 0xcc, 0x1b, 0x6f, 0xe2, 0x94, 0xbd, 0xc9, 0xec, 0xac, 0x37, 0x31,
	0x25, 0x6f, 0x64, 0x96, 0xdd, 0x99, 0xd8, 0x04, 0x50, 0xa2, 0xe5, 0x10, 0xc7, 0x09, 0x58, 0xca,
	0x42, 0xd4, 0xde, 0x5d, 0x81, 0xf6, 0x54, 0xd3, 0x5d, 0x9e, 0x29, 0xb9, 0xa7, 0xbb, 0xa9, 0xaa,
	0x9e, 0x60, 0x6e, 0x1b, 0x71, 0x45, 0x42, 0x42, 0x48, 0x70, 0xe1, 0x03, 0xf0, 0x05, 0x38, 0xf3,
	0x01, 0x56, 0x1c, 0xf8, 0x00, 0x20, 0xb4, 0x17, 0xbe, 0x01, 0x47, 0x54, 0x7f, 0xfa, 0xef, 0xf4,
	0x38, 0x46, 0x08, 0x4e, 0x53, 0xef, 0xd5, 0x7b, 0xf5, 0xde, 0xfb, 0xbd, 0x3f, 0x55, 0xd3, 0xb0,
	0x9f, 0xf0, 0x58, 0xc6, 0x93, 0x80, 0x91, 0x59, 0x14, 0x0b, 0xc9, 0xfc, 0xc9, 0xf2, 0x70, 0x72,
	0x92, 0x53, 0x63, 0xbd, 0x8d, 0xb6, 0x13, 0xce, 0x7e, 0x4e, 0xc6, 0x85, 0xd4, 0x78, 0x79, 0x38,
	0x7a, 0x77, 0x16, 0xc7, 0xb3, 0x90, 0x4e, 0xb4, 0xc8, 0x34, 0x3d, 0x9f, 0xd0, 0x45, 0x22, 0x2f,
	0x8d, 0xc6, 0x68, 0xd7, 0x6e, 0x92, 0x84, 0x4d, 0x48, 0x14, 0xc5, 0x92, 0x48, 0x16, 0x47, 0xc2,
	0xee, 0x7e, 0x77, 0xc6, 0xe4, 0x3c, 0x9d, 0x8e, 0xfd, 0x78, 0x31, 0x59, 0xbc, 0x62, 0xf2, 0x22,
	0x7e, 0x35, 0x99, 0xc5, 0x1f, 0xe9, 0xcd, 0x8f, 0x96, 0x24, 0x64, 0x01, 0x91, 0x31, 0x17, 0x93,
	0x7c, 0x69, 0xf4, 0x70, 0x08, 0xb7, 0x8f, 0x63, 0xf9, 0x34, 0x8e, 0x96, 0x94, 0x0b, 0x7d, 0xa2,
	0x47, 0x7f, 0x96, 0x52, 0x21, 0xd1, 0x2e, 0xf4, 0x05, 0x15, 0x82, 0xc5, 0xd1, 0x69, 0x30, 0x74,
	0xf6, 0x9c, 0x83, 0xbe, 0x57, 0x30, 0xd0, 0x43, 0xe8, 0x70, 0x9a, 0x84, 0x97, 0x43, 0x77, 0xcf,
	0x39, 0x18, 0x1c, 0xdd, 0x1d, 0x37, 0xc4, 0x33, 0xf6, 0x94, 0xc4, 0x09, 0x91, 0xc4, 0x33, 0xc2,
	0xf8, 0xb7, 0x0e, 0xf4, 0x73, 0x26, 0xda, 0x82, 0x96, 0x24, 0x33, 0x7b, 0xb6, 0x5a, 0x22, 0x04,
	0x6d, 0x79, 0x99, 0x50, 0x7d, 0x68, 0xdf, 0xd3, 0x6b, 0xb4, 0x03, 0x9d, 0x25, 0x09, 0x53, 0x3a,
	0x6c, 0x69, 0xa6, 0x21, 0xd0, 0x0b, 0x78, 0x2b, 0xe1, 0xd4, 0x8f, 0xa3, 0x80, 0x69, 0x18, 0x86,
	0xed, 0xbd, 0xd6, 0xc1, 0xe0, 0xe8, 0x7e, 0xa3, 0x1f, 0x2f, 0xcb, 0x92, 0xda, 0x9f, 0xaa, 0x32,
	0x26, 0x30, 0x5c, 0x95, 0xb1, 0x38, 0x3c, 0x83, 0xb6, 0x22, 0x87, 0x8e, 0x36, 0x70, 0x78, 0x4d,
	0x03, 0x46, 0xf9, 0x25, 0x8f, 0x13, 0x4f, 0xab, 0xe3, 0xe7, 0xb0, 0x7b, 0x95, 0x14, 0xba, 0x01,
	0x2e, 0xcb, 0x70, 0x76, 0x59, 0x80, 0x6e, 0x43, 0x57, 0x47, 0x2a, 0x2c, 0x18, 0x96, 0xc2, 0x5f,
	0x3b, 0x70, 0x67, 0x25, 0x63, 0x22, 0x89, 0x23, 0x41, 0xdf, 0x90, 0xb2, 0xef, 0x41, 0x97, 0x53,
	0x91, 0x86, 0xd2, 0xe6, 0xec, 0xde, 0x9a, 0x9c, 0x29, 0x11, 0xed, 0x9d, 0x15, 0x47, 0x0f, 0xe1,
	0xed, 0x84, 0xc7, 0x33, 0x4e, 0x85, 0x38, 0x26, 0xfc, 0x25, 0xe5, 0x3e, 0x8d, 0x24, 0x99, 0x99,
	0x8c, 0xb8, 0x5e, 0xf3, 0x26, 0xfa, 0x18, 0xfa, 0x61, 0x3c, 0x7b, 0xb6, 0xa4, 0x91, 0xcc, 0xb2,
	0xd3, 0x5c, 0x25, 0x2f, 0x32, 0x29, 0xaf, 0x50, 0xc0, 0xff, 0x72, 0x00, 0x0a, 0x57, 0xd0, 0xf7,
	0xa1, 0xb7, 0xa0, 0x42, 0x90, 0x19, 0x15, 0x3a, 0xb0, 0xc1, 0xd1, 0x37, 0x1a, 0xcf, 0xfa, 0xc4,
	0x0a, 0x69, 0xff, 0x73, 0x15, 0xf4, 0x08, 0x36, 0x88, 0x6f, 0xea, 0xe4, 0xaa, 0xd8, 0x9f, 0x68,
	0x19, 0xad, 0x9b, 0xc9, 0xaf, 0x16, 0x5a, 0xeb, 0xbf, 0x28, 0x34, 0x84, 0x61, 0xd3, 0x4f, 0x39,
	0xa7, 0x91, 0x3c, 0x93, 0x44, 0xd2, 0x61, 0x5b, 0x27, 0xa9, 0xc2, 0xc3, 0xbf, 0x80, 0xcd, 0x72,
	0x18, 0x45, 0x03, 0x38, 0xe5, 0x06, 0xd8, 0x83, 0x41, 0x40, 0x85, 0xcf, 0x59, 0xa2, 0x4e, 0xb6,
	0x45, 0x52, 0x66, 0x29, 0xbd, 0x05, 0x0d, 0x18, 0xc9, 0x1a, 0x47, 0x13, 0xba, 0x46, 0xe2, 0x94,
	0xfb, 0xf4, 0x33, 0xef, 0x85, 0x35, 0x5f, 0x30, 0xf0, 0x1f, 0x1d, 0x80, 0x02, 0x85, 0xbc, 0x1f,
	0x9d, 0x52, 0x3f, 0x3e, 0xcc, 0xdc, 0x71, 0xaf, 0xc8, 0xe9, 0xe7, 0x4a, 0xc2, 0x74, 0xbe, 0x71,
	0xd7, 0x83, 0x9b, 0x56, 0x82, 0x09, 0x93, 0x57, 0xed, 0xd6, 0xe0, 0xe8, 0xa0, 0x51, 0xff, 0xa4,
	0x2a, 0xab, 0x4f, 0xaa, 0x1f, 0x80, 0x2f, 0xa0, 0x9f, 0xdb, 0x51, 0xd1, 0x86, 0x64, 0x4a, 0xc3,
	0x0c, 0x25, 0x4d, 0x14, 0xd8, 0xb9, 0x65, 0xec, 0xec, 0xe0, 0x69, 0x15, 0x83, 0xa7, 0x86, 0x66,
	0x7b, 0x05, 0x4d, 0xfc, 0x17, 0x17, 0xb6, 0x1b, 0xbc, 0x42, 0x87, 0xd0, 0x4e, 0x05, 0xe5, 0xb6,
	0x2a, 0xdf, 0x6b, 0x8c, 0xe6, 0x33, 0x41, 0xb9, 0x0e, 0x41, 0x8b, 0xa2, 0xe7, 0x30, 0x50, 0xbf,
	0x27, 0x54, 0x12, 0x16, 0x66, 0x15, 0xb9, 0xbf, 0x5e, 0xd3, 0xc8, 0xe9, 0x03, 0xca, 0x8a, 0xe8,
	0x63, 0xe8, 0x25, 0x3c, 0x3e, 0x67, 0x21, 0xcd, 0xaa, 0x72, 0x6f, 0x4d, 0x55, 0x6a, 0x21, 0xd3,
	0x13, 0x99, 0x86, 0xd2, 0x16, 0x97, 0x8b, 0x44, 0xc6, 0x8b, 0xac, 0x3d, 0x9b, 0xb5, 0xcf, 0x8c,
	0xd0, 0x09, 0x15, 0xbe, 0x97, 0x6b, 0xa0, 0x27, 0xd0, 0x0b, 0x98, 0xa0, 0x44, 0x50, 0x31, 0xec,
	0x68, 0xed, 0xf7, 0x9b, 0x6d, 0xc7, 0x92, 0x46, 0x92, 0x91, 0xf0, 0xc4, 0x48, 0x7b, 0xb9, 0x1a,
	0xfe, 0x02, 0x6e, 0xd6, 0xc2, 0x53, 0x89, 0x51, 0x73, 0x45, 0x61, 0xd9, 0xf1, 0xd4, 0x52, 0x95,
	0xeb, 0x39, 0xe3, 0x42, 0x46, 0x64, 0x91, 0x25, 0xb1, 0x60, 0xa0, 0x21, 0x6c, 0x30, 0xf1, 0xe3,
	0x29, 0x15, 0x66, 0x16, 0xf5, 0xbc, 0x8c, 0xc4, 0xbf, 0x77, 0x60, 0x50, 0x8a, 0x7b, 0x65, 0xbc,
	0x22, 0x68, 0x97, 0x8e, 0xd4, 0x6b, 0x34, 0x82, 0x9e, 0xfa, 0x3d, 0x8d, 0x82, 0xd8, 0xd6, 0x46,
	0x4e, 0xbf, 0xb9, 0x40, 0xf2, 0x5e, 0xe9, 0x54, 0xef, 0xae, 0x98, 0x07, 0x94, 0x0f, 0xbb, 0x3a,
	0x22, 0x43, 0xe0, 0x3f, 0x3b, 0x30, 0x28, 0xa1, 0xaa, 0x5b, 0xd2, 0x90, 0xa7, 0x27, 0xf9, 0xd8,
	0xce, 0x18, 0xca, 0xb2, 0x25, 0x7e, 0x54, 0x38, 0x5c, 0x66, 0x29, 0xfd, 0x84, 0xc7, 0x89, 0x5a,
	0x9b, 0x42, 0xe8, 0x7b, 0x05, 0x43, 0xf9, 0xe0, 0xcf, 0x19, 0x3d, 0xd7, 0x3e, 0xf7, 0x3c, 0x43,
	0xa0, 0xfb, 0x70, 0x23, 0xcb, 0xe5, 0xa7, 0x9c, 0x29, 0xd0, 0x3b, 0x5a, 0xb1, 0xc6, 0x55, 0xd7,
	0x10, 0x89, 0xc4, 0x2b, 0x1b, 0x42, 0xdf, 0xb3, 0x14, 0xfe, 0x95, 0x0b, 0x5b, 0xf5, 0xdc, 0x5e,
	0x0b, 0xe4, 0x1a, 0x90, 0xad, 0x55, 0x20, 0xef, 0x02, 0x84, 0xec, 0x82, 0x86, 0x2c, 0xa2, 0x42,
	0x58, 0xa4, 0x4b, 0x1c, 0x15, 0x90, 0xf0, 0x63, 0x6e, 0x90, 0x76, 0x3d, 0x43, 0xa8, 0xd2, 0x49,
	0x79, 0x68, 0xbd, 0x54, 0x4b, 0xf4, 0x08, 0xba, 0xd2, 0x84, 0xb6, 0x71, 0xc5, 0x8d, 0x61, 0xe2,
	0x34, 0x0d, 0xed, 0x59, 0x05, 0xf4, 0x00, 0xda, 0x21, 0x99, 0x8a, 0x61, 0x4f, 0x57, 0xf6, 0x6e,
	0xf3, 0xb5, 0x45, 0xa6, 0xa7, 0xd1, 0x79, 0xec, 0x69, 0x49, 0x9c, 0xc0, 0x66, 0xf9, 0xa4, 0xff,
	0x7d, 0xbd, 0xe1, 0x2f, 0x60, 0xc3, 0xba, 0x70, 0x2d, 0x63, 0x5b, 0xd0, 0x12, 0x17, 0x69, 0x36,
	0xf3, 0xc4, 0x45, 0xaa, 0xcc, 0xe7, 0x2d, 0xdc, 0xd6, 0xc9, 0x2f, 0x7a, 0xf3, 0x2b, 0x17, 0x6e,
	0xad, 0x5c, 0x66, 0x4d, 0x76, 0x56, 0x9e, 0x6b, 0x57, 0x05, 0xf5, 0x18, 0x86, 0x95, 0xeb, 0xf0,
	0x64, 0x25, 0xc2, 0xb5, 0xfb, 0xe8, 0x18, 0x76, 0xd7, 0xed, 0x3d, 0x8d, 0x93, 0x4b, 0xdb, 0x76,
	0x57, 0xca, 0x28, 0xdf, 0xc8, 0x8c, 0x7e, 0x12, 0x47, 0x72, 0xae, 0x0b, 0xa5, 0xe5, 0xe5, 0xb4,
	0x1a, 0x25, 0x64, 0x46, 0x7f, 0x4a, 0x09, 0xd7, 0xe5, 0xd2, 0xf2, 0x32, 0x52, 0xb5, 0xc0, 0x2b,
	0xca, 0x66, 0x73, 0x39, 0xec, 0xe9, 0x82, 0xb3, 0x94, 0xe2, 0xcf, 0x0d, 0xbf, 0x6f, 0xf8, 0x86,
	0xca, 0xd1, 0x87, 0x02, 0x7d, 0xfc, 0x95, 0x03, 0xfd, 0xfc, 0x9d, 0x53, 0x6a, 0x2a, 0xa7, 0xdc,
	0x54, 0x68, 0x1f, 0xde, 0x22, 0x49, 0x12, 0x32, 0x5f, 0x3f, 0xeb, 0x4e, 0x03, 0x0b, 0x6c, 0x95,
	0xa9, 0xdb, 0x9d, 0x70, 0x19, 0x51, 0x7e, 0x1a, 0x58, 0x88, 0x0b, 0x86, 0x6a, 0x6c, 0x5d, 0xad,
	0x67, 0xf9, 0x43, 0xd0, 0x20, 0x5b, 0xe3, 0xaa, 0x02, 0xd3, 0x1c, 0x35, 0x82, 0x4f, 0x03, 0x0b,
	0x5f, 0x99, 0xa5, 0xd0, 0xd2, 0xcf, 0x53, 0x95, 0x1d, 0xd3, 0x56, 0x39, 0x8d, 0x7f, 0xe7, 0xc0,
	0x3b, 0x4f, 0x39, 0x25, 0x92, 0xbe, 0x2c, 0x1d, 0x5b, 0xfa, 0xeb, 0x50, 0x78, 0xe8, 0xd4, 0x3d,
	0xc4, 0xb0, 0x69, 0x89, 0x27, 0x49, 0x92, 0x07, 0x59, 0xe1, 0xa1, 0x47, 0xd0, 0x4b, 0xed, 0xa5,
	0x69, 0xdf, 0x09, 0x6f, 0xb8, 0x59, 0x73, 0x71, 0x9c, 0xc2, 0xa8, 0xc9, 0xb3, 0x6b, 0x3d, 0x91,
	0xcb, 0x66, 0xdd, 0xff, 0xcc, 0xec, 0xdf, 0x1d, 0xe8, 0x65, 0xec, 0x95, 0x46, 0x19, 0x41, 0xef,
	0x3c, 0x0d, 0xc3, 0x52, 0x53, 0xe6, 0xb4, 0x2a, 0x86, 0x19, 0x8d, 0xd4, 0x25, 0x61, 0x72, 0x69,
	0x29, 0xe5, 0xe9, 0x94, 0x71, 0x39, 0x0f, 0x8a, 0x77, 0x62, 0xc1, 0x28, 0x15, 0x65, 0x67, 0x4d,
	0x51, 0x76, 0x2b, 0x45, 0x79, 0x0c, 0x7d, 0x16, 0x89, 0x94, 0x93, 0xc8, 0xcf, 0xe6, 0x61, 0xf3,
	0x8b, 0xe3, 0x34, 0x93, 0x52, 0x8f, 0xd1, 0x54, 0x78, 0x85, 0x1a, 0x66, 0x70, 0xb3, 0xb6, 0xab,
	0x2a, 0x76, 0x4e, 0x96, 0x34, 0x67, 0xeb, 0x98, 0x7b, 0x5e, 0x95, 0x89, 0x1e, 0xc0, 0x76, 0x12,
	0x92, 0xe8, 0xd3, 0xf8, 0x87, 0x15, 0x59, 0x57, 0xcb, 0x36, 0x6d, 0xe1, 0x29, 0x6c, 0x9d, 0xd1,
	0x28, 0x78, 0xb6, 0x20, 0x2c, 0xcc, 0xaa, 0x6a, 0x07, 0x3a, 0x54, 0xd1, 0xd9, 0x0b, 0x4f, 0x13,
	0xd5, 0x84, 0xba, 0xf5, 0x84, 0x8e, 0x4c, 0x42, 0x35, 0xf0, 0x76, 0x1a, 0x65, 0x34, 0xfe, 0x0e,
	0xdc, 0x2a, 0xd9, 0xb0, 0xf5, 0xb1, 0x07, 0x1b, 0xf6, 0x5f, 0x83, 0x31, 0x73, 0xdc, 0xfd, 0xc7,
	0xdf, 0xee, 0xb9, 0x3f, 0x71, 0xbc, 0x8c, 0x8d, 0xff, 0xe9, 0x18, 0xbd, 0xb3, 0x94, 0x2f, 0xe9,
	0x65, 0xe6, 0xdc, 0x87, 0xf5, 0xd6, 0xad, 0x6a, 0xd7, 0x5a, 0x18, 0x43, 0xef, 0x9c, 0xd2, 0x60,
	0x4a, 0xfc, 0x0b, 0xe3, 0x73, 0x2e, 0x98, 0xf3, 0xd1, 0xfe, 0x4a, 0x9b, 0xe7, 0x42, 0xa5, 0x66,
	0xba, 0x0d, 0x5d, 0x4e, 0x24, 0x8b, 0x66, 0xba, 0x44, 0x3a, 0x9e, 0xa5, 0x94, 0x76, 0x01, 0x4b,
	0xa7, 0xaa, 0x5d, 0xc0, 0x73, 0x17, 0xba, 0xa9, 0xe9, 0xff, 0x6e, 0x45, 0xc4, 0x72, 0xf1, 0x97,
	0x0e, 0xdc, 0x79, 0x6e, 0x1d, 0x7a, 0x1a, 0x47, 0xea, 0xba, 0xcf, 0x91, 0xc2, 0xa5, 0xf1, 0x50,
	0x0d, 0x36, 0xe7, 0xa3, 0x03, 0x18, 0xb0, 0x48, 0x48, 0x9e, 0xfa, 0xc5, 0x9f, 0x94, 0x5c, 0xac,
	0xbc, 0xa5, 0xc6, 0xaf, 0x3f, 0x8f, 0x99, 0x9f, 0xbf, 0x60, 0x32, 0x12, 0xff, 0xc9, 0x85, 0x6d,
	0x85, 0x77, 0xe6, 0x47, 0x86, 0x78, 0xe1, 0xbb, 0xd3, 0xe4, 0x7b, 0x15, 0x3f, 0x77, 0x1d, 0x7e,
	0x2b, 0x79, 0x6b, 0x5d, 0x95, 0xb7, 0x0a, 0xaa, 0xed, 0x75, 0xa8, 0xee, 0x17, 0xef, 0xb9, 0x55,
	0xec, 0xb3, 0x8d, 0x0a, 0x7e, 0xdd, 0x35, 0xf8, 0xa9, 0xd7, 0xaf, 0x0d, 0x5b, 0x0c, 0x37, 0xcc,
	0xcb, 0x2e, 0x67, 0x28, 0x04, 0x02, 0xfd, 0x78, 0xd6, 0x17, 0x53, 0x09, 0x01, 0xc3, 0xc5, 0x0f,
	0x60, 0xa7, 0x0a, 0x9c, 0xcd, 0xdc, 0x10, 0x36, 0x44, 0xea, 0xfb, 0xea, 0x75, 0x65, 0xda, 0x35,
	0x23, 0x8f, 0xfe, 0xb0, 0x01, 0xb7, 0x8a, 0x4f, 0x55, 0x67, 0x94, 0x2f, 0x99, 0x4f, 0xd1, 0x6b,
	0x07, 0x6e, 0xd6, 0x3e, 0x39, 0xa0, 0x6f, 0x35, 0x0e, 0x8f, 0xe6, 0x4f, 0x49, 0xa3, 0x0f, 0xaf,
	0x27, 0x6c, 0xdc, 0xc3, 0x3b, 0xaf, 0xff, 0xfa, 0xf5, 0x6f, 0xdc, 0x1b, 0xb8, 0x3f, 0x59, 0x1e,
	0x4e, 0xb4, 0xe2, 0x63, 0xe7, 0x03, 0xf4, 0x4b, 0x07, 0x6e, 0xd5, 0x34, 0x3e, 0x3f, 0xfa, 0x3f,
	0xb9, 0x71, 0x54, 0xb8, 0xf1, 0x6b, 0x07, 0xd0, 0xea, 0xf5, 0x82, 0xc6, 0x8d, 0x47, 0xaf, 0xbd,
	0x21, 0x47, 0x93, 0x6b, 0xcb, 0x5b, 0x6f, 0xde, 0xd1, 0xde, 0x6c, 0xe3, 0x1b, 0x39, 0x28, 0x13,
	0x55, 0xe7, 0xca, 0xa5, 0x2f, 0x1d, 0xe8, 0xe7, 0x83, 0x0c, 0x35, 0xff, 0x0d, 0xab, 0x0f, 0xd3,
	0xd1, 0xfd, 0x37, 0x89, 0x59, 0xbb, 0xef, 0x6b, 0xbb, 0xf7, 0xf0, 0x48, 0xd9, 0xf5, 0x4b, 0x38,
	0x4d, 0x94, 0xd8, 0x44, 0xd0, 0x28, 0x50, 0x3e, 0x30, 0x80, 0x62, 0x26, 0xa2, 0xf5, 0x87, 0x57,
	0x86, 0xe6, 0xe8, 0xf6, 0xd8, 0x7c, 0xd3, 0x1c, 0x67, 0x1f, 0x3c, 0xc7, 0xcf, 0x16, 0x89, 0xbc,
	0xc4, 0xef, 0x6a, 0xa3, 0x6f, 0xe3, 0xad, 0x22, 0x58, 0xa1, 0x15, 0x95, 0xa9, 0x25, 0xa0, 0x1f,
	0x50, 0x59, 0x9b, 0x4a, 0x68, 0xcd, 0x51, 0x6b, 0x72, 0xbe, 0x66, 0xa6, 0xe1, 0x91, 0x36, 0xbc,
	0x83, 0x50, 0x61, 0x38, 0x9f, 0xc7, 0xaf, 0x1d, 0xd8, 0x2c, 0xb7, 0x13, 0x3a, 0x58, 0x1b, 0x65,
	0x6d, 0x54, 0x8d, 0xbe, 0x79, 0x0d, 0x49, 0xeb, 0xc1, 0x7b, 0xda, 0x83, 0x3b, 0xb8, 0xc1, 0x83,
	0xc7, 0xce, 0x07, 0xd3, 0xae, 0x0e, 0xef, 0xdb, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x4d,
	0x8d, 0x9d, 0x65, 0x16, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiagnosticServiceClient is the client API for DiagnosticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiagnosticServiceClient interface {
	BotConversation(ctx context.Context, in *BotConversationRequest, opts ...grpc.CallOption) (*BotConversationResponse, error)
	BotConversationV2(ctx context.Context, in *BotConversationRequest, opts ...grpc.CallOption) (*BotConversationResponse, error)
	CreatePrixaSession(ctx context.Context, in *CreatePrixaSessionRequest, opts ...grpc.CallOption) (*CreatePrixaSessionResponse, error)
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	SendSurvey(ctx context.Context, in *SendSurveyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetFeedbackContent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FeedbackContentResponse, error)
	SendFeedback(ctx context.Context, in *SendFeedbackRequest, opts ...grpc.CallOption) (*SendFeedbackResponse, error)
}

type diagnosticServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiagnosticServiceClient(cc *grpc.ClientConn) DiagnosticServiceClient {
	return &diagnosticServiceClient{cc}
}

func (c *diagnosticServiceClient) BotConversation(ctx context.Context, in *BotConversationRequest, opts ...grpc.CallOption) (*BotConversationResponse, error) {
	out := new(BotConversationResponse)
	err := c.cc.Invoke(ctx, "/prixa.diagnostic.v1.DiagnosticService/BotConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticServiceClient) BotConversationV2(ctx context.Context, in *BotConversationRequest, opts ...grpc.CallOption) (*BotConversationResponse, error) {
	out := new(BotConversationResponse)
	err := c.cc.Invoke(ctx, "/prixa.diagnostic.v1.DiagnosticService/BotConversationV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticServiceClient) CreatePrixaSession(ctx context.Context, in *CreatePrixaSessionRequest, opts ...grpc.CallOption) (*CreatePrixaSessionResponse, error) {
	out := new(CreatePrixaSessionResponse)
	err := c.cc.Invoke(ctx, "/prixa.diagnostic.v1.DiagnosticService/CreatePrixaSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/prixa.diagnostic.v1.DiagnosticService/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticServiceClient) SendSurvey(ctx context.Context, in *SendSurveyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/prixa.diagnostic.v1.DiagnosticService/SendSurvey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticServiceClient) GetFeedbackContent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FeedbackContentResponse, error) {
	out := new(FeedbackContentResponse)
	err := c.cc.Invoke(ctx, "/prixa.diagnostic.v1.DiagnosticService/GetFeedbackContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticServiceClient) SendFeedback(ctx context.Context, in *SendFeedbackRequest, opts ...grpc.CallOption) (*SendFeedbackResponse, error) {
	out := new(SendFeedbackResponse)
	err := c.cc.Invoke(ctx, "/prixa.diagnostic.v1.DiagnosticService/SendFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticServiceServer is the server API for DiagnosticService service.
type DiagnosticServiceServer interface {
	BotConversation(context.Context, *BotConversationRequest) (*BotConversationResponse, error)
	BotConversationV2(context.Context, *BotConversationRequest) (*BotConversationResponse, error)
	CreatePrixaSession(context.Context, *CreatePrixaSessionRequest) (*CreatePrixaSessionResponse, error)
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	SendSurvey(context.Context, *SendSurveyRequest) (*empty.Empty, error)
	GetFeedbackContent(context.Context, *empty.Empty) (*FeedbackContentResponse, error)
	SendFeedback(context.Context, *SendFeedbackRequest) (*SendFeedbackResponse, error)
}

// UnimplementedDiagnosticServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiagnosticServiceServer struct {
}

func (*UnimplementedDiagnosticServiceServer) BotConversation(ctx context.Context, req *BotConversationRequest) (*BotConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BotConversation not implemented")
}
func (*UnimplementedDiagnosticServiceServer) BotConversationV2(ctx context.Context, req *BotConversationRequest) (*BotConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BotConversationV2 not implemented")
}
func (*UnimplementedDiagnosticServiceServer) CreatePrixaSession(ctx context.Context, req *CreatePrixaSessionRequest) (*CreatePrixaSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrixaSession not implemented")
}
func (*UnimplementedDiagnosticServiceServer) SendEmail(ctx context.Context, req *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (*UnimplementedDiagnosticServiceServer) SendSurvey(ctx context.Context, req *SendSurveyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSurvey not implemented")
}
func (*UnimplementedDiagnosticServiceServer) GetFeedbackContent(ctx context.Context, req *empty.Empty) (*FeedbackContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackContent not implemented")
}
func (*UnimplementedDiagnosticServiceServer) SendFeedback(ctx context.Context, req *SendFeedbackRequest) (*SendFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFeedback not implemented")
}

func RegisterDiagnosticServiceServer(s *grpc.Server, srv DiagnosticServiceServer) {
	s.RegisterService(&_DiagnosticService_serviceDesc, srv)
}

func _DiagnosticService_BotConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).BotConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.diagnostic.v1.DiagnosticService/BotConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).BotConversation(ctx, req.(*BotConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticService_BotConversationV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).BotConversationV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.diagnostic.v1.DiagnosticService/BotConversationV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).BotConversationV2(ctx, req.(*BotConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticService_CreatePrixaSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrixaSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).CreatePrixaSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.diagnostic.v1.DiagnosticService/CreatePrixaSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).CreatePrixaSession(ctx, req.(*CreatePrixaSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.diagnostic.v1.DiagnosticService/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticService_SendSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).SendSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.diagnostic.v1.DiagnosticService/SendSurvey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).SendSurvey(ctx, req.(*SendSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticService_GetFeedbackContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).GetFeedbackContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.diagnostic.v1.DiagnosticService/GetFeedbackContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).GetFeedbackContent(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticService_SendFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).SendFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prixa.diagnostic.v1.DiagnosticService/SendFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).SendFeedback(ctx, req.(*SendFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiagnosticService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prixa.diagnostic.v1.DiagnosticService",
	HandlerType: (*DiagnosticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BotConversation",
			Handler:    _DiagnosticService_BotConversation_Handler,
		},
		{
			MethodName: "BotConversationV2",
			Handler:    _DiagnosticService_BotConversationV2_Handler,
		},
		{
			MethodName: "CreatePrixaSession",
			Handler:    _DiagnosticService_CreatePrixaSession_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _DiagnosticService_SendEmail_Handler,
		},
		{
			MethodName: "SendSurvey",
			Handler:    _DiagnosticService_SendSurvey_Handler,
		},
		{
			MethodName: "GetFeedbackContent",
			Handler:    _DiagnosticService_GetFeedbackContent_Handler,
		},
		{
			MethodName: "SendFeedback",
			Handler:    _DiagnosticService_SendFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/diagnostic/v1/Diagnostic.proto",
}
